// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

// Call a callable Python object without any arguments
//
// llgo:link (*Object).CallNoArgs C.PyObject_CallNoArgs
func (self *Object) CallNoArgs() *Object {
	return self
}

// Call a callable Python object 'callable' with arguments given by the
// tuple 'args' and keywords arguments given by the dictionary 'kwargs'.
//
// 'args' must not be NULL, use an empty tuple if no arguments are
// needed. If no named arguments are needed, 'kwargs' can be NULL.
//
// This is the equivalent of the Python expression:
// callable(*args, **kwargs).
//
// llgo:link (*Object).Call C.PyObject_Call
func (self *Object) Call(args *Object, kwargs *Object) *Object {
	return self
}

// Call a callable Python object 'callable', with arguments given by the
// tuple 'args'.  If no arguments are needed, then 'args' can be NULL.
//
// Returns the result of the call on success, or NULL on failure.
//
// This is the equivalent of the Python expression:
// callable(*args).
//
// llgo:link (*Object).ObjectCallObject C.PyObject_CallObject
func (self *Object) ObjectCallObject(args *Object) *Object {
	return self
}

// Call a callable Python object, callable, with a variable number of C
// arguments. The C arguments are described using a mkvalue-style format
// string.
//
// The format may be NULL, indicating that no arguments are provided.
//
// Returns the result of the call on success, or NULL on failure.
//
// This is the equivalent of the Python expression:
// callable(arg1, arg2, ...).
//
// llgo:link (*Object).CallFunction C.PyObject_CallFunction
func (self *Object) CallFunction(format *c.Char, __llgo_va_list ...any) *Object {
	return self
}

// Call the method named 'name' of object 'obj' with a variable number of
// C arguments.  The C arguments are described by a mkvalue format string.
//
// The format can be NULL, indicating that no arguments are provided.
//
// Returns the result of the call on success, or NULL on failure.
//
// This is the equivalent of the Python expression:
// obj.name(arg1, arg2, ...).
//
// llgo:link (*Object).CallMethod C.PyObject_CallMethod
func (self *Object) CallMethod(name *c.Char, format *c.Char, __llgo_va_list ...any) *Object {
	return self
}

// Call a callable Python object 'callable' with a variable number of C
// arguments. The C arguments are provided as PyObject* values, terminated
// by a NULL.
//
// Returns the result of the call on success, or NULL on failure.
//
// This is the equivalent of the Python expression:
// callable(arg1, arg2, ...).
//
// llgo:link (*Object).CallFunctionObjArgs C.PyObject_CallFunctionObjArgs
func (self *Object) CallFunctionObjArgs(__llgo_va_list ...any) *Object {
	return self
}

// Call the method named 'name' of object 'obj' with a variable number of
// C arguments.  The C arguments are provided as PyObject* values, terminated
// by NULL.
//
// Returns the result of the call on success, or NULL on failure.
//
// This is the equivalent of the Python expression: obj.name(*args).
//
// llgo:link (*Object).CallMethodObjArgs C.PyObject_CallMethodObjArgs
func (self *Object) CallMethodObjArgs(name *Object, __llgo_va_list ...any) *Object {
	return self
}

// Given a vectorcall nargsf argument, return the actual number of arguments.
// (For use outside the limited API, this is re-defined as a static inline
// function in cpython/abstract.h)
//
//go:linkname Vectorcall_NARGS C.PyVectorcall_NARGS
func Vectorcall_NARGS(nargsf c.SizeT) SsizeT

type Vectorcall struct {
	X_object
}

func (self *Object) AsVectorcall() *Vectorcall {
	return (*Vectorcall)(unsafe.Pointer(self))
}

// Call "callable" (which must support vectorcall) with positional arguments
// "tuple" and keyword arguments "dict". "dict" may also be NULL
//
// llgo:link (*Vectorcall).Call C.PyVectorcall_Call
func (self *Vectorcall) Call(tuple *Object, dict *Object) *Object {
	return nil
}

// Perform a PEP 590-style vector call on 'callable'
//
// llgo:link (*Object).Vectorcall C.PyObject_Vectorcall
func (self *Object) Vectorcall(args **Object, nargsf c.SizeT, kwnames *Object) *Object {
	return self
}

// Call the method 'name' on args[0] with arguments in args[1..nargsf-1].
//
// llgo:link (*Object).VectorcallMethod C.PyObject_VectorcallMethod
func (self *Object) VectorcallMethod(args **Object, nargsf c.SizeT, kwnames *Object) *Object {
	return self
}

// Get the type of an object.
//
// On success, returns a type object corresponding to the object type of object
// 'o'. On failure, returns NULL.
//
// This is equivalent to the Python expression: type(o)
//
// llgo:link (*Object).Type C.PyObject_Type
func (self *Object) Type() *Object {
	return self
}

// Return the size of object 'o'.  If the object 'o' provides both sequence and
// mapping protocols, the sequence size is returned.
//
// On error, -1 is returned.
//
// This is the equivalent to the Python expression: len(o)
//
// llgo:link (*Object).Size C.PyObject_Size
func (self *Object) Size() SsizeT {
	return 0
}

// llgo:link (*Object).Length C.PyObject_Length
func (self *Object) Length() SsizeT {
	return 0
}

// Return element of 'o' corresponding to the object 'key'. Return NULL
// on failure.
//
// This is the equivalent of the Python expression: o[key]
//
// llgo:link (*Object).Item C.PyObject_GetItem
func (self *Object) Item(key *Object) *Object {
	return self
}

// Map the object 'key' to the value 'v' into 'o'.
//
// Raise an exception and return -1 on failure; return 0 on success.
//
// This is the equivalent of the Python statement: o[key]=v.
//
// llgo:link (*Object).SetItem C.PyObject_SetItem
func (self *Object) SetItem(key *Object, v *Object) c.Int {
	return 0
}

// Remove the mapping for the string 'key' from the object 'o'.
// Returns -1 on failure.
//
// This is equivalent to the Python statement: del o[key].
//
// llgo:link (*Object).DelItemString C.PyObject_DelItemString
func (self *Object) DelItemString(key *c.Char) c.Int {
	return 0
}

// Delete the mapping for the object 'key' from the object 'o'.
// Returns -1 on failure.
//
// This is the equivalent of the Python statement: del o[key].
//
// llgo:link (*Object).DelItem C.PyObject_DelItem
func (self *Object) DelItem(key *Object) c.Int {
	return 0
}

// Takes an arbitrary object and returns the result of calling
// obj.__format__(format_spec).
//
// llgo:link (*Object).Format C.PyObject_Format
func (self *Object) Format(format_spec *Object) *Object {
	return self
}

// Takes an object and returns an iterator for it.
// This is typically a new iterator but if the argument is an iterator, this
// returns itself.
//
// llgo:link (*Object).Iter C.PyObject_GetIter
func (self *Object) Iter() *Object {
	return self
}

// Takes an AsyncIterable object and returns an AsyncIterator for it.
// This is typically a new iterator but if the argument is an AsyncIterator,
// this returns itself.
//
// llgo:link (*Object).AIter C.PyObject_GetAIter
func (self *Object) AIter() *Object {
	return self
}

type Iter struct {
	X_object
}

func (self *Object) AsIter() *Iter {
	return (*Iter)(unsafe.Pointer(self))
}

// Returns non-zero if the object 'obj' provides iterator protocols, and 0 otherwise.
//
// This function always succeeds.
//
// llgo:link (*Iter).Check C.PyIter_Check
func (self *Iter) Check() c.Int {
	return 0
}

type AIter struct {
	X_object
}

func (self *Object) AsAIter() *AIter {
	return (*AIter)(unsafe.Pointer(self))
}

// Returns non-zero if the object 'obj' provides AsyncIterator protocols, and 0 otherwise.
//
// This function always succeeds.
//
// llgo:link (*AIter).Check C.PyAIter_Check
func (self *AIter) Check() c.Int {
	return 0
}

// Return 1 and set 'item' to the next item of 'iter' on success.
// Return 0 and set 'item' to NULL when there are no remaining values.
// Return -1, set 'item' to NULL and set an exception on error.
//
// llgo:link (*Iter).NextItem C.PyIter_NextItem
func (self *Iter) NextItem(item **Object) c.Int {
	return 0
}

// Takes an iterator object and calls its tp_iternext slot,
// returning the next value.
//
// If the iterator is exhausted, this returns NULL without setting an
// exception.
//
// NULL with an exception means an error occurred.
//
// Prefer PyIter_NextItem() instead.
//
// llgo:link (*Iter).Next C.PyIter_Next
func (self *Iter) Next() *Object {
	return nil
}

// Takes generator, coroutine or iterator object and sends the value into it.
// Returns:
// - PYGEN_RETURN (0) if generator has returned.
// 'result' parameter is filled with return value
// - PYGEN_ERROR (-1) if exception was raised.
// 'result' parameter is NULL
// - PYGEN_NEXT (1) if generator has yielded.
// 'result' parameter is filled with yielded value.
//
// llgo:link (*Iter).Send C.PyIter_Send
func (self *Iter) Send(_llcppg_param2 *Object, _llcppg_param3 **Object) SendResult {
	return 0
}

type Number struct {
	X_object
}

func (self *Object) AsNumber() *Number {
	return (*Number)(unsafe.Pointer(self))
}

// Returns 1 if the object 'o' provides numeric protocols, and 0 otherwise.
//
// This function always succeeds.
//
// llgo:link (*Number).Check C.PyNumber_Check
func (self *Number) Check() c.Int {
	return 0
}

// Returns the result of adding o1 and o2, or NULL on failure.
//
// This is the equivalent of the Python expression: o1 + o2.
//
// llgo:link (*Number).Add C.PyNumber_Add
func (self *Number) Add(o2 *Object) *Object {
	return nil
}

// Returns the result of subtracting o2 from o1, or NULL on failure.
//
// This is the equivalent of the Python expression: o1 - o2.
//
// llgo:link (*Number).Subtract C.PyNumber_Subtract
func (self *Number) Subtract(o2 *Object) *Object {
	return nil
}

// Returns the result of multiplying o1 and o2, or NULL on failure.
//
// This is the equivalent of the Python expression: o1 * o2.
//
// llgo:link (*Number).Multiply C.PyNumber_Multiply
func (self *Number) Multiply(o2 *Object) *Object {
	return nil
}

// This is the equivalent of the Python expression: o1 @ o2.
//
// llgo:link (*Number).MatrixMultiply C.PyNumber_MatrixMultiply
func (self *Number) MatrixMultiply(o2 *Object) *Object {
	return nil
}

// Returns the result of dividing o1 by o2 giving an integral result,
// or NULL on failure.
//
// This is the equivalent of the Python expression: o1 // o2.
//
// llgo:link (*Number).FloorDivide C.PyNumber_FloorDivide
func (self *Number) FloorDivide(o2 *Object) *Object {
	return nil
}

// Returns the result of dividing o1 by o2 giving a float result, or NULL on
// failure.
//
// This is the equivalent of the Python expression: o1 / o2.
//
// llgo:link (*Number).TrueDivide C.PyNumber_TrueDivide
func (self *Number) TrueDivide(o2 *Object) *Object {
	return nil
}

// Returns the remainder of dividing o1 by o2, or NULL on failure.
//
// This is the equivalent of the Python expression: o1 % o2.
//
// llgo:link (*Number).Remainder C.PyNumber_Remainder
func (self *Number) Remainder(o2 *Object) *Object {
	return nil
}

// See the built-in function divmod.
//
// Returns NULL on failure.
//
// This is the equivalent of the Python expression: divmod(o1, o2).
//
// llgo:link (*Number).Divmod C.PyNumber_Divmod
func (self *Number) Divmod(o2 *Object) *Object {
	return nil
}

// See the built-in function pow. Returns NULL on failure.
//
// This is the equivalent of the Python expression: pow(o1, o2, o3),
// where o3 is optional.
//
// llgo:link (*Number).Power C.PyNumber_Power
func (self *Number) Power(o2 *Object, o3 *Object) *Object {
	return nil
}

// Returns the negation of o on success, or NULL on failure.
//
// This is the equivalent of the Python expression: -o.
//
// llgo:link (*Number).Negative C.PyNumber_Negative
func (self *Number) Negative() *Object {
	return nil
}

// Returns the positive of o on success, or NULL on failure.
//
// This is the equivalent of the Python expression: +o.
//
// llgo:link (*Number).Positive C.PyNumber_Positive
func (self *Number) Positive() *Object {
	return nil
}

// Returns the absolute value of 'o', or NULL on failure.
//
// This is the equivalent of the Python expression: abs(o).
//
// llgo:link (*Number).Absolute C.PyNumber_Absolute
func (self *Number) Absolute() *Object {
	return nil
}

// Returns the bitwise negation of 'o' on success, or NULL on failure.
//
// This is the equivalent of the Python expression: ~o.
//
// llgo:link (*Number).Invert C.PyNumber_Invert
func (self *Number) Invert() *Object {
	return nil
}

// Returns the result of left shifting o1 by o2 on success, or NULL on failure.
//
// This is the equivalent of the Python expression: o1 << o2.
//
// llgo:link (*Number).Lshift C.PyNumber_Lshift
func (self *Number) Lshift(o2 *Object) *Object {
	return nil
}

// Returns the result of right shifting o1 by o2 on success, or NULL on
// failure.
//
// This is the equivalent of the Python expression: o1 >> o2.
//
// llgo:link (*Number).Rshift C.PyNumber_Rshift
func (self *Number) Rshift(o2 *Object) *Object {
	return nil
}

// Returns the result of bitwise and of o1 and o2 on success, or NULL on
// failure.
//
// This is the equivalent of the Python expression: o1 & o2.
//
// llgo:link (*Number).And C.PyNumber_And
func (self *Number) And(o2 *Object) *Object {
	return nil
}

// Returns the bitwise exclusive or of o1 by o2 on success, or NULL on failure.
//
// This is the equivalent of the Python expression: o1 ^ o2.
//
// llgo:link (*Number).Xor C.PyNumber_Xor
func (self *Number) Xor(o2 *Object) *Object {
	return nil
}

// Returns the result of bitwise or on o1 and o2 on success, or NULL on
// failure.
//
// This is the equivalent of the Python expression: o1 | o2.
//
// llgo:link (*Number).Or C.PyNumber_Or
func (self *Number) Or(o2 *Object) *Object {
	return nil
}

type Index struct {
	X_object
}

func (self *Object) AsIndex() *Index {
	return (*Index)(unsafe.Pointer(self))
}

// Returns 1 if obj is an index integer (has the nb_index slot of the
// tp_as_number structure filled in), and 0 otherwise.
//
// llgo:link (*Index).Check C.PyIndex_Check
func (self *Index) Check() c.Int {
	return 0
}

// Returns the object 'o' converted to a Python int, or NULL with an exception
// raised on failure.
//
// llgo:link (*Number).Index C.PyNumber_Index
func (self *Number) Index() *Object {
	return nil
}

// Returns the object 'o' converted to Py_ssize_t by going through
// PyNumber_Index() first.
//
// If an overflow error occurs while converting the int to Py_ssize_t, then the
// second argument 'exc' is the error-type to return.  If it is NULL, then the
// overflow error is cleared and the value is clipped.
//
// llgo:link (*Number).AsSsizeT C.PyNumber_AsSsize_t
func (self *Number) AsSsizeT(exc *Object) SsizeT {
	return 0
}

// Returns the object 'o' converted to an integer object on success, or NULL
// on failure.
//
// This is the equivalent of the Python expression: int(o).
//
// llgo:link (*Number).Long C.PyNumber_Long
func (self *Number) Long() *Object {
	return nil
}

// Returns the object 'o' converted to a float object on success, or NULL
// on failure.
//
// This is the equivalent of the Python expression: float(o).
//
// llgo:link (*Number).Float C.PyNumber_Float
func (self *Number) Float() *Object {
	return nil
}

// Returns the result of adding o2 to o1, possibly in-place, or NULL
// on failure.
//
// This is the equivalent of the Python expression: o1 += o2.
//
// llgo:link (*Number).InPlaceAdd C.PyNumber_InPlaceAdd
func (self *Number) InPlaceAdd(o2 *Object) *Object {
	return nil
}

// Returns the result of subtracting o2 from o1, possibly in-place or
// NULL on failure.
//
// This is the equivalent of the Python expression: o1 -= o2.
//
// llgo:link (*Number).InPlaceSubtract C.PyNumber_InPlaceSubtract
func (self *Number) InPlaceSubtract(o2 *Object) *Object {
	return nil
}

// Returns the result of multiplying o1 by o2, possibly in-place, or NULL on
// failure.
//
// This is the equivalent of the Python expression: o1 *= o2.
//
// llgo:link (*Number).InPlaceMultiply C.PyNumber_InPlaceMultiply
func (self *Number) InPlaceMultiply(o2 *Object) *Object {
	return nil
}

// This is the equivalent of the Python expression: o1 @= o2.
//
// llgo:link (*Number).InPlaceMatrixMultiply C.PyNumber_InPlaceMatrixMultiply
func (self *Number) InPlaceMatrixMultiply(o2 *Object) *Object {
	return nil
}

// Returns the result of dividing o1 by o2 giving an integral result, possibly
// in-place, or NULL on failure.
//
// This is the equivalent of the Python expression: o1 /= o2.
//
// llgo:link (*Number).InPlaceFloorDivide C.PyNumber_InPlaceFloorDivide
func (self *Number) InPlaceFloorDivide(o2 *Object) *Object {
	return nil
}

// Returns the result of dividing o1 by o2 giving a float result, possibly
// in-place, or null on failure.
//
// This is the equivalent of the Python expression: o1 /= o2.
//
// llgo:link (*Number).InPlaceTrueDivide C.PyNumber_InPlaceTrueDivide
func (self *Number) InPlaceTrueDivide(o2 *Object) *Object {
	return nil
}

// Returns the remainder of dividing o1 by o2, possibly in-place, or NULL on
// failure.
//
// This is the equivalent of the Python expression: o1 %= o2.
//
// llgo:link (*Number).InPlaceRemainder C.PyNumber_InPlaceRemainder
func (self *Number) InPlaceRemainder(o2 *Object) *Object {
	return nil
}

// Returns the result of raising o1 to the power of o2, possibly in-place,
// or NULL on failure.
//
// This is the equivalent of the Python expression: o1 **= o2,
// or o1 = pow(o1, o2, o3) if o3 is present.
//
// llgo:link (*Number).InPlacePower C.PyNumber_InPlacePower
func (self *Number) InPlacePower(o2 *Object, o3 *Object) *Object {
	return nil
}

// Returns the result of left shifting o1 by o2, possibly in-place, or NULL
// on failure.
//
// This is the equivalent of the Python expression: o1 <<= o2.
//
// llgo:link (*Number).InPlaceLshift C.PyNumber_InPlaceLshift
func (self *Number) InPlaceLshift(o2 *Object) *Object {
	return nil
}

// Returns the result of right shifting o1 by o2, possibly in-place or NULL
// on failure.
//
// This is the equivalent of the Python expression: o1 >>= o2.
//
// llgo:link (*Number).InPlaceRshift C.PyNumber_InPlaceRshift
func (self *Number) InPlaceRshift(o2 *Object) *Object {
	return nil
}

// Returns the result of bitwise and of o1 and o2, possibly in-place, or NULL
// on failure.
//
// This is the equivalent of the Python expression: o1 &= o2.
//
// llgo:link (*Number).InPlaceAnd C.PyNumber_InPlaceAnd
func (self *Number) InPlaceAnd(o2 *Object) *Object {
	return nil
}

// Returns the bitwise exclusive or of o1 by o2, possibly in-place, or NULL
// on failure.
//
// This is the equivalent of the Python expression: o1 ^= o2.
//
// llgo:link (*Number).InPlaceXor C.PyNumber_InPlaceXor
func (self *Number) InPlaceXor(o2 *Object) *Object {
	return nil
}

// Returns the result of bitwise or of o1 and o2, possibly in-place,
// or NULL on failure.
//
// This is the equivalent of the Python expression: o1 |= o2.
//
// llgo:link (*Number).InPlaceOr C.PyNumber_InPlaceOr
func (self *Number) InPlaceOr(o2 *Object) *Object {
	return nil
}

// Returns the integer n converted to a string with a base, with a base
// marker of 0b, 0o or 0x prefixed if applicable.
//
// If n is not an int object, it is converted with PyNumber_Index first.
//
// llgo:link (*Number).ToBase C.PyNumber_ToBase
func (self *Number) ToBase(base c.Int) *Object {
	return nil
}

type Sequence struct {
	X_object
}

func (self *Object) AsSequence() *Sequence {
	return (*Sequence)(unsafe.Pointer(self))
}

// Return 1 if the object provides sequence protocol, and zero
// otherwise.
//
// This function always succeeds.
//
// llgo:link (*Sequence).Check C.PySequence_Check
func (self *Sequence) Check() c.Int {
	return 0
}

// Return the size of sequence object o, or -1 on failure.
//
// llgo:link (*Sequence).Size C.PySequence_Size
func (self *Sequence) Size() SsizeT {
	return 0
}

// llgo:link (*Sequence).Length C.PySequence_Length
func (self *Sequence) Length() SsizeT {
	return 0
}

// Return the concatenation of o1 and o2 on success, and NULL on failure.
//
// This is the equivalent of the Python expression: o1 + o2.
//
// llgo:link (*Sequence).Concat C.PySequence_Concat
func (self *Sequence) Concat(o2 *Object) *Object {
	return nil
}

// Return the result of repeating sequence object 'o' 'count' times,
// or NULL on failure.
//
// This is the equivalent of the Python expression: o * count.
//
// llgo:link (*Sequence).Repeat C.PySequence_Repeat
func (self *Sequence) Repeat(count SsizeT) *Object {
	return nil
}

// Return the ith element of o, or NULL on failure.
//
// This is the equivalent of the Python expression: o[i].
//
// llgo:link (*Sequence).Item C.PySequence_GetItem
func (self *Sequence) Item(i SsizeT) *Object {
	return nil
}

// Return the slice of sequence object o between i1 and i2, or NULL on failure.
//
// This is the equivalent of the Python expression: o[i1:i2].
//
// llgo:link (*Sequence).Slice C.PySequence_GetSlice
func (self *Sequence) Slice(i1 SsizeT, i2 SsizeT) *Object {
	return nil
}

// Assign object 'v' to the ith element of the sequence 'o'. Raise an exception
// and return -1 on failure; return 0 on success.
//
// This is the equivalent of the Python statement o[i] = v.
//
// llgo:link (*Sequence).SetItem C.PySequence_SetItem
func (self *Sequence) SetItem(i SsizeT, v *Object) c.Int {
	return 0
}

// Delete the 'i'-th element of the sequence 'v'. Returns -1 on failure.
//
// This is the equivalent of the Python statement: del o[i].
//
// llgo:link (*Sequence).DelItem C.PySequence_DelItem
func (self *Sequence) DelItem(i SsizeT) c.Int {
	return 0
}

// Assign the sequence object 'v' to the slice in sequence object 'o',
// from 'i1' to 'i2'. Returns -1 on failure.
//
// This is the equivalent of the Python statement: o[i1:i2] = v.
//
// llgo:link (*Sequence).SetSlice C.PySequence_SetSlice
func (self *Sequence) SetSlice(i1 SsizeT, i2 SsizeT, v *Object) c.Int {
	return 0
}

// Delete the slice in sequence object 'o' from 'i1' to 'i2'.
// Returns -1 on failure.
//
// This is the equivalent of the Python statement: del o[i1:i2].
//
// llgo:link (*Sequence).DelSlice C.PySequence_DelSlice
func (self *Sequence) DelSlice(i1 SsizeT, i2 SsizeT) c.Int {
	return 0
}

// Returns the sequence 'o' as a tuple on success, and NULL on failure.
//
// This is equivalent to the Python expression: tuple(o).
//
// llgo:link (*Sequence).Tuple C.PySequence_Tuple
func (self *Sequence) Tuple() *Object {
	return nil
}

// Returns the sequence 'o' as a list on success, and NULL on failure.
// This is equivalent to the Python expression: list(o)
//
// llgo:link (*Sequence).List C.PySequence_List
func (self *Sequence) List() *Object {
	return nil
}

// Return the sequence 'o' as a list, unless it's already a tuple or list.
//
// Use PySequence_Fast_GET_ITEM to access the members of this list, and
// PySequence_Fast_GET_SIZE to get its length.
//
// Returns NULL on failure.  If the object does not support iteration, raises a
// TypeError exception with 'm' as the message text.
//
// llgo:link (*Sequence).Fast C.PySequence_Fast
func (self *Sequence) Fast(m *c.Char) *Object {
	return nil
}

// Return the number of occurrences on value on 'o', that is, return
// the number of keys for which o[key] == value.
//
// On failure, return -1.  This is equivalent to the Python expression:
// o.count(value).
//
// llgo:link (*Sequence).Count C.PySequence_Count
func (self *Sequence) Count(value *Object) SsizeT {
	return 0
}

// Return 1 if 'ob' is in the sequence 'seq'; 0 if 'ob' is not in the sequence
// 'seq'; -1 on error.
//
// Use __contains__ if possible, else _PySequence_IterSearch().
//
// llgo:link (*Sequence).Contains C.PySequence_Contains
func (self *Sequence) Contains(ob *Object) c.Int {
	return 0
}

// Determine if the sequence 'o' contains 'value'. If an item in 'o' is equal
// to 'value', return 1, otherwise return 0. On error, return -1.
//
// This is equivalent to the Python expression: value in o.
//
// llgo:link (*Sequence).In C.PySequence_In
func (self *Sequence) In(value *Object) c.Int {
	return 0
}

// Return the first index for which o[i] == value.
// On error, return -1.
//
// This is equivalent to the Python expression: o.index(value).
//
// llgo:link (*Sequence).Index C.PySequence_Index
func (self *Sequence) Index(value *Object) SsizeT {
	return 0
}

// Append sequence 'o2' to sequence 'o1', in-place when possible. Return the
// resulting object, which could be 'o1', or NULL on failure.
//
// This is the equivalent of the Python expression: o1 += o2.
//
// llgo:link (*Sequence).InPlaceConcat C.PySequence_InPlaceConcat
func (self *Sequence) InPlaceConcat(o2 *Object) *Object {
	return nil
}

// Repeat sequence 'o' by 'count', in-place when possible. Return the resulting
// object, which could be 'o', or NULL on failure.
//
// This is the equivalent of the Python expression: o1 *= count.
//
// llgo:link (*Sequence).InPlaceRepeat C.PySequence_InPlaceRepeat
func (self *Sequence) InPlaceRepeat(count SsizeT) *Object {
	return nil
}

type Mapping struct {
	X_object
}

func (self *Object) AsMapping() *Mapping {
	return (*Mapping)(unsafe.Pointer(self))
}

// Return 1 if the object provides mapping protocol, and 0 otherwise.
//
// This function always succeeds.
//
// llgo:link (*Mapping).Check C.PyMapping_Check
func (self *Mapping) Check() c.Int {
	return 0
}

// Returns the number of keys in mapping object 'o' on success, and -1 on
// failure. This is equivalent to the Python expression: len(o).
//
// llgo:link (*Mapping).Size C.PyMapping_Size
func (self *Mapping) Size() SsizeT {
	return 0
}

// llgo:link (*Mapping).Length C.PyMapping_Length
func (self *Mapping) Length() SsizeT {
	return 0
}

// On success, return 1 if the mapping object 'o' has the key 'key',
// and 0 otherwise.
//
// This is equivalent to the Python expression: key in o.
//
// This function always succeeds.
//
// llgo:link (*Mapping).HasKeyString C.PyMapping_HasKeyString
func (self *Mapping) HasKeyString(key *c.Char) c.Int {
	return 0
}

// Return 1 if the mapping object has the key 'key', and 0 otherwise.
//
// This is equivalent to the Python expression: key in o.
//
// This function always succeeds.
//
// llgo:link (*Mapping).HasKey C.PyMapping_HasKey
func (self *Mapping) HasKey(key *Object) c.Int {
	return 0
}

// Return 1 if the mapping object has the key 'key', and 0 otherwise.
// This is equivalent to the Python expression: key in o.
// On failure, return -1.
//
// llgo:link (*Mapping).HasKeyWithError C.PyMapping_HasKeyWithError
func (self *Mapping) HasKeyWithError(key *Object) c.Int {
	return 0
}

// Return 1 if the mapping object has the key 'key', and 0 otherwise.
// This is equivalent to the Python expression: key in o.
// On failure, return -1.
//
// llgo:link (*Mapping).HasKeyStringWithError C.PyMapping_HasKeyStringWithError
func (self *Mapping) HasKeyStringWithError(key *c.Char) c.Int {
	return 0
}

// On success, return a list of the keys in mapping object 'o'.
// On failure, return NULL.
//
// llgo:link (*Mapping).Keys C.PyMapping_Keys
func (self *Mapping) Keys() *Object {
	return nil
}

// On success, return a list of the values in mapping object 'o'.
// On failure, return NULL.
//
// llgo:link (*Mapping).Values C.PyMapping_Values
func (self *Mapping) Values() *Object {
	return nil
}

// On success, return a list of the items in mapping object 'o',
// where each item is a tuple containing a key-value pair. On failure, return
// NULL.
//
// llgo:link (*Mapping).Items C.PyMapping_Items
func (self *Mapping) Items() *Object {
	return nil
}

// Return element of 'o' corresponding to the string 'key' or NULL on failure.
//
// This is the equivalent of the Python expression: o[key].
//
// llgo:link (*Mapping).ItemString C.PyMapping_GetItemString
func (self *Mapping) ItemString(key *c.Char) *Object {
	return nil
}

// llgo:link (*Mapping).OptionalItem C.PyMapping_GetOptionalItem
func (self *Mapping) OptionalItem(_llcppg_param2 *Object, _llcppg_param3 **Object) c.Int {
	return 0
}

// llgo:link (*Mapping).OptionalItemString C.PyMapping_GetOptionalItemString
func (self *Mapping) OptionalItemString(_llcppg_param2 *c.Char, _llcppg_param3 **Object) c.Int {
	return 0
}

// Map the string 'key' to the value 'v' in the mapping 'o'.
// Returns -1 on failure.
//
// This is the equivalent of the Python statement: o[key]=v.
//
// llgo:link (*Mapping).SetItemString C.PyMapping_SetItemString
func (self *Mapping) SetItemString(key *c.Char, value *Object) c.Int {
	return 0
}

// isinstance(object, typeorclass)
//
// llgo:link (*Object).IsInstance C.PyObject_IsInstance
func (self *Object) IsInstance(typeorclass *Object) c.Int {
	return 0
}

// issubclass(object, typeorclass)
//
// llgo:link (*Object).IsSubclass C.PyObject_IsSubclass
func (self *Object) IsSubclass(typeorclass *Object) c.Int {
	return 0
}

// Like PyObject_CallMethod(), but expect a _Py_Identifier*
// as the method name.
//
//go:linkname X_ObjectCallMethodId C._PyObject_CallMethodId
func X_ObjectCallMethodId(obj *Object, name *X_Identifier, format *c.Char, __llgo_va_list ...any) *Object

// Convert keyword arguments from the FASTCALL (stack: C array, kwnames: tuple)
// format to a Python dictionary ("kwargs" dict).
//
// The type of kwnames keys is not checked. The final function getting
// arguments is responsible to check if all keys are strings, for example using
// PyArg_ParseTupleAndKeywords() or PyArg_ValidateKeywordArguments().
//
// Duplicate keys are merged using the last value. If duplicate keys must raise
// an exception, the caller is responsible to implement an explicit keys on
// kwnames.
//
//go:linkname X_StackAsDict C._PyStack_AsDict
func X_StackAsDict(values **Object, kwnames *Object) *Object

// llgo:link (*Vectorcall).Function C.PyVectorcall_Function
func (self *Vectorcall) Function() Vectorcallfunc {
	return nil
}

// Same as PyObject_Vectorcall except that keyword arguments are passed as
// dict, which may be NULL if there are no keyword arguments.
//
// llgo:link (*Object).VectorcallDict C.PyObject_VectorcallDict
func (self *Object) VectorcallDict(args **Object, nargsf c.SizeT, kwargs *Object) *Object {
	return self
}

// llgo:link (*Object).CallOneArg C.PyObject_CallOneArg
func (self *Object) CallOneArg(arg *Object) *Object {
	return self
}

// Guess the size of object 'o' using len(o) or o.__length_hint__().
// If neither of those return a non-negative value, then return the default
// value.  If one of the calls fails, this function returns -1.
//
// llgo:link (*Object).LengthHint C.PyObject_LengthHint
func (self *Object) LengthHint(_llcppg_param2 SsizeT) SsizeT {
	return 0
}
