// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

// Call a callable Python object without any arguments
//
// llgo:link (*Object).CallNoArgs C.PyObject_CallNoArgs
func (self *Object) CallNoArgs() *Object {
	return self
}

// Call a callable Python object 'callable' with arguments given by the
// tuple 'args' and keywords arguments given by the dictionary 'kwargs'.
//
// 'args' must not be NULL, use an empty tuple if no arguments are
// needed. If no named arguments are needed, 'kwargs' can be NULL.
//
// This is the equivalent of the Python expression:
// callable(*args, **kwargs).
//
// llgo:link (*Object).Call C.PyObject_Call
func (self *Object) Call(args *Object, kwargs *Object) *Object {
	return self
}

// Call a callable Python object 'callable', with arguments given by the
// tuple 'args'.  If no arguments are needed, then 'args' can be NULL.
//
// Returns the result of the call on success, or NULL on failure.
//
// This is the equivalent of the Python expression:
// callable(*args).
//
// llgo:link (*Object).ObjectCallObject C.PyObject_CallObject
func (self *Object) ObjectCallObject(args *Object) *Object {
	return self
}

// Call a callable Python object, callable, with a variable number of C
// arguments. The C arguments are described using a mkvalue-style format
// string.
//
// The format may be NULL, indicating that no arguments are provided.
//
// Returns the result of the call on success, or NULL on failure.
//
// This is the equivalent of the Python expression:
// callable(arg1, arg2, ...).
//
// llgo:link (*Object).CallFunction C.PyObject_CallFunction
func (self *Object) CallFunction(format *c.Char, __llgo_va_list ...any) *Object {
	return self
}

// Call the method named 'name' of object 'obj' with a variable number of
// C arguments.  The C arguments are described by a mkvalue format string.
//
// The format can be NULL, indicating that no arguments are provided.
//
// Returns the result of the call on success, or NULL on failure.
//
// This is the equivalent of the Python expression:
// obj.name(arg1, arg2, ...).
//
// llgo:link (*Object).CallMethod C.PyObject_CallMethod
func (self *Object) CallMethod(name *c.Char, format *c.Char, __llgo_va_list ...any) *Object {
	return self
}

// Call a callable Python object 'callable' with a variable number of C
// arguments. The C arguments are provided as PyObject* values, terminated
// by a NULL.
//
// Returns the result of the call on success, or NULL on failure.
//
// This is the equivalent of the Python expression:
// callable(arg1, arg2, ...).
//
// llgo:link (*Object).CallFunctionObjArgs C.PyObject_CallFunctionObjArgs
func (self *Object) CallFunctionObjArgs(__llgo_va_list ...any) *Object {
	return self
}

// Call the method named 'name' of object 'obj' with a variable number of
// C arguments.  The C arguments are provided as PyObject* values, terminated
// by NULL.
//
// Returns the result of the call on success, or NULL on failure.
//
// This is the equivalent of the Python expression: obj.name(*args).
//
// llgo:link (*Object).CallMethodObjArgs C.PyObject_CallMethodObjArgs
func (self *Object) CallMethodObjArgs(name *Object, __llgo_va_list ...any) *Object {
	return self
}

// Given a vectorcall nargsf argument, return the actual number of arguments.
// (For use outside the limited API, this is re-defined as a static inline
// function in cpython/abstract.h)
//
//go:linkname Vectorcall_NARGS C.PyVectorcall_NARGS
func Vectorcall_NARGS(nargsf c.SizeT) SsizeT

// Call "callable" (which must support vectorcall) with positional arguments
// "tuple" and keyword arguments "dict". "dict" may also be NULL
//
//go:linkname VectorcallCall C.PyVectorcall_Call
func VectorcallCall(callable *Object, tuple *Object, dict *Object) *Object

// Perform a PEP 590-style vector call on 'callable'
//
// llgo:link (*Object).Vectorcall C.PyObject_Vectorcall
func (self *Object) Vectorcall(args **Object, nargsf c.SizeT, kwnames *Object) *Object {
	return self
}

// Call the method 'name' on args[0] with arguments in args[1..nargsf-1].
//
// llgo:link (*Object).VectorcallMethod C.PyObject_VectorcallMethod
func (self *Object) VectorcallMethod(args **Object, nargsf c.SizeT, kwnames *Object) *Object {
	return self
}

// Get the type of an object.
//
// On success, returns a type object corresponding to the object type of object
// 'o'. On failure, returns NULL.
//
// This is equivalent to the Python expression: type(o)
//
// llgo:link (*Object).Type C.PyObject_Type
func (self *Object) Type() *Object {
	return self
}

// Return the size of object 'o'.  If the object 'o' provides both sequence and
// mapping protocols, the sequence size is returned.
//
// On error, -1 is returned.
//
// This is the equivalent to the Python expression: len(o)
//
// llgo:link (*Object).Size C.PyObject_Size
func (self *Object) Size() SsizeT {
	return 0
}

// llgo:link (*Object).Length C.PyObject_Length
func (self *Object) Length() SsizeT {
	return 0
}

// Return element of 'o' corresponding to the object 'key'. Return NULL
// on failure.
//
// This is the equivalent of the Python expression: o[key]
//
// llgo:link (*Object).Item C.PyObject_GetItem
func (self *Object) Item(key *Object) *Object {
	return self
}

// Map the object 'key' to the value 'v' into 'o'.
//
// Raise an exception and return -1 on failure; return 0 on success.
//
// This is the equivalent of the Python statement: o[key]=v.
//
// llgo:link (*Object).SetItem C.PyObject_SetItem
func (self *Object) SetItem(key *Object, v *Object) c.Int {
	return 0
}

// Remove the mapping for the string 'key' from the object 'o'.
// Returns -1 on failure.
//
// This is equivalent to the Python statement: del o[key].
//
// llgo:link (*Object).DelItemString C.PyObject_DelItemString
func (self *Object) DelItemString(key *c.Char) c.Int {
	return 0
}

// Delete the mapping for the object 'key' from the object 'o'.
// Returns -1 on failure.
//
// This is the equivalent of the Python statement: del o[key].
//
// llgo:link (*Object).DelItem C.PyObject_DelItem
func (self *Object) DelItem(key *Object) c.Int {
	return 0
}

// Takes an arbitrary object and returns the result of calling
// obj.__format__(format_spec).
//
// llgo:link (*Object).Format C.PyObject_Format
func (self *Object) Format(format_spec *Object) *Object {
	return self
}

// Takes an object and returns an iterator for it.
// This is typically a new iterator but if the argument is an iterator, this
// returns itself.
//
// llgo:link (*Object).Iter C.PyObject_GetIter
func (self *Object) Iter() *Object {
	return self
}

// Takes an AsyncIterable object and returns an AsyncIterator for it.
// This is typically a new iterator but if the argument is an AsyncIterator,
// this returns itself.
//
// llgo:link (*Object).AIter C.PyObject_GetAIter
func (self *Object) AIter() *Object {
	return self
}

// Returns non-zero if the object 'obj' provides iterator protocols, and 0 otherwise.
//
// This function always succeeds.
//
//go:linkname IterCheck C.PyIter_Check
func IterCheck(_llcppg_param1 *Object) c.Int

// Returns non-zero if the object 'obj' provides AsyncIterator protocols, and 0 otherwise.
//
// This function always succeeds.
//
//go:linkname AIterCheck C.PyAIter_Check
func AIterCheck(_llcppg_param1 *Object) c.Int

// Return 1 and set 'item' to the next item of 'iter' on success.
// Return 0 and set 'item' to NULL when there are no remaining values.
// Return -1, set 'item' to NULL and set an exception on error.
//
//go:linkname IterNextItem C.PyIter_NextItem
func IterNextItem(iter *Object, item **Object) c.Int

// Takes an iterator object and calls its tp_iternext slot,
// returning the next value.
//
// If the iterator is exhausted, this returns NULL without setting an
// exception.
//
// NULL with an exception means an error occurred.
//
// Prefer PyIter_NextItem() instead.
//
//go:linkname IterNext C.PyIter_Next
func IterNext(_llcppg_param1 *Object) *Object

// Takes generator, coroutine or iterator object and sends the value into it.
// Returns:
// - PYGEN_RETURN (0) if generator has returned.
// 'result' parameter is filled with return value
// - PYGEN_ERROR (-1) if exception was raised.
// 'result' parameter is NULL
// - PYGEN_NEXT (1) if generator has yielded.
// 'result' parameter is filled with yielded value.
//
//go:linkname IterSend C.PyIter_Send
func IterSend(_llcppg_param1 *Object, _llcppg_param2 *Object, _llcppg_param3 **Object) SendResult

// Returns 1 if the object 'o' provides numeric protocols, and 0 otherwise.
//
// This function always succeeds.
//
//go:linkname NumberCheck C.PyNumber_Check
func NumberCheck(o *Object) c.Int

// Returns the result of adding o1 and o2, or NULL on failure.
//
// This is the equivalent of the Python expression: o1 + o2.
//
//go:linkname NumberAdd C.PyNumber_Add
func NumberAdd(o1 *Object, o2 *Object) *Object

// Returns the result of subtracting o2 from o1, or NULL on failure.
//
// This is the equivalent of the Python expression: o1 - o2.
//
//go:linkname NumberSubtract C.PyNumber_Subtract
func NumberSubtract(o1 *Object, o2 *Object) *Object

// Returns the result of multiplying o1 and o2, or NULL on failure.
//
// This is the equivalent of the Python expression: o1 * o2.
//
//go:linkname NumberMultiply C.PyNumber_Multiply
func NumberMultiply(o1 *Object, o2 *Object) *Object

// This is the equivalent of the Python expression: o1 @ o2.
//
//go:linkname NumberMatrixMultiply C.PyNumber_MatrixMultiply
func NumberMatrixMultiply(o1 *Object, o2 *Object) *Object

// Returns the result of dividing o1 by o2 giving an integral result,
// or NULL on failure.
//
// This is the equivalent of the Python expression: o1 // o2.
//
//go:linkname NumberFloorDivide C.PyNumber_FloorDivide
func NumberFloorDivide(o1 *Object, o2 *Object) *Object

// Returns the result of dividing o1 by o2 giving a float result, or NULL on
// failure.
//
// This is the equivalent of the Python expression: o1 / o2.
//
//go:linkname NumberTrueDivide C.PyNumber_TrueDivide
func NumberTrueDivide(o1 *Object, o2 *Object) *Object

// Returns the remainder of dividing o1 by o2, or NULL on failure.
//
// This is the equivalent of the Python expression: o1 % o2.
//
//go:linkname NumberRemainder C.PyNumber_Remainder
func NumberRemainder(o1 *Object, o2 *Object) *Object

// See the built-in function divmod.
//
// Returns NULL on failure.
//
// This is the equivalent of the Python expression: divmod(o1, o2).
//
//go:linkname NumberDivmod C.PyNumber_Divmod
func NumberDivmod(o1 *Object, o2 *Object) *Object

// See the built-in function pow. Returns NULL on failure.
//
// This is the equivalent of the Python expression: pow(o1, o2, o3),
// where o3 is optional.
//
//go:linkname NumberPower C.PyNumber_Power
func NumberPower(o1 *Object, o2 *Object, o3 *Object) *Object

// Returns the negation of o on success, or NULL on failure.
//
// This is the equivalent of the Python expression: -o.
//
//go:linkname NumberNegative C.PyNumber_Negative
func NumberNegative(o *Object) *Object

// Returns the positive of o on success, or NULL on failure.
//
// This is the equivalent of the Python expression: +o.
//
//go:linkname NumberPositive C.PyNumber_Positive
func NumberPositive(o *Object) *Object

// Returns the absolute value of 'o', or NULL on failure.
//
// This is the equivalent of the Python expression: abs(o).
//
//go:linkname NumberAbsolute C.PyNumber_Absolute
func NumberAbsolute(o *Object) *Object

// Returns the bitwise negation of 'o' on success, or NULL on failure.
//
// This is the equivalent of the Python expression: ~o.
//
//go:linkname NumberInvert C.PyNumber_Invert
func NumberInvert(o *Object) *Object

// Returns the result of left shifting o1 by o2 on success, or NULL on failure.
//
// This is the equivalent of the Python expression: o1 << o2.
//
//go:linkname NumberLshift C.PyNumber_Lshift
func NumberLshift(o1 *Object, o2 *Object) *Object

// Returns the result of right shifting o1 by o2 on success, or NULL on
// failure.
//
// This is the equivalent of the Python expression: o1 >> o2.
//
//go:linkname NumberRshift C.PyNumber_Rshift
func NumberRshift(o1 *Object, o2 *Object) *Object

// Returns the result of bitwise and of o1 and o2 on success, or NULL on
// failure.
//
// This is the equivalent of the Python expression: o1 & o2.
//
//go:linkname NumberAnd C.PyNumber_And
func NumberAnd(o1 *Object, o2 *Object) *Object

// Returns the bitwise exclusive or of o1 by o2 on success, or NULL on failure.
//
// This is the equivalent of the Python expression: o1 ^ o2.
//
//go:linkname NumberXor C.PyNumber_Xor
func NumberXor(o1 *Object, o2 *Object) *Object

// Returns the result of bitwise or on o1 and o2 on success, or NULL on
// failure.
//
// This is the equivalent of the Python expression: o1 | o2.
//
//go:linkname NumberOr C.PyNumber_Or
func NumberOr(o1 *Object, o2 *Object) *Object

// Returns 1 if obj is an index integer (has the nb_index slot of the
// tp_as_number structure filled in), and 0 otherwise.
//
//go:linkname IndexCheck C.PyIndex_Check
func IndexCheck(_llcppg_param1 *Object) c.Int

// Returns the object 'o' converted to a Python int, or NULL with an exception
// raised on failure.
//
//go:linkname NumberIndex C.PyNumber_Index
func NumberIndex(o *Object) *Object

// Returns the object 'o' converted to Py_ssize_t by going through
// PyNumber_Index() first.
//
// If an overflow error occurs while converting the int to Py_ssize_t, then the
// second argument 'exc' is the error-type to return.  If it is NULL, then the
// overflow error is cleared and the value is clipped.
//
//go:linkname NumberAsSsizeT C.PyNumber_AsSsize_t
func NumberAsSsizeT(o *Object, exc *Object) SsizeT

// Returns the object 'o' converted to an integer object on success, or NULL
// on failure.
//
// This is the equivalent of the Python expression: int(o).
//
//go:linkname NumberLong C.PyNumber_Long
func NumberLong(o *Object) *Object

// Returns the object 'o' converted to a float object on success, or NULL
// on failure.
//
// This is the equivalent of the Python expression: float(o).
//
//go:linkname NumberFloat C.PyNumber_Float
func NumberFloat(o *Object) *Object

// Returns the result of adding o2 to o1, possibly in-place, or NULL
// on failure.
//
// This is the equivalent of the Python expression: o1 += o2.
//
//go:linkname NumberInPlaceAdd C.PyNumber_InPlaceAdd
func NumberInPlaceAdd(o1 *Object, o2 *Object) *Object

// Returns the result of subtracting o2 from o1, possibly in-place or
// NULL on failure.
//
// This is the equivalent of the Python expression: o1 -= o2.
//
//go:linkname NumberInPlaceSubtract C.PyNumber_InPlaceSubtract
func NumberInPlaceSubtract(o1 *Object, o2 *Object) *Object

// Returns the result of multiplying o1 by o2, possibly in-place, or NULL on
// failure.
//
// This is the equivalent of the Python expression: o1 *= o2.
//
//go:linkname NumberInPlaceMultiply C.PyNumber_InPlaceMultiply
func NumberInPlaceMultiply(o1 *Object, o2 *Object) *Object

// This is the equivalent of the Python expression: o1 @= o2.
//
//go:linkname NumberInPlaceMatrixMultiply C.PyNumber_InPlaceMatrixMultiply
func NumberInPlaceMatrixMultiply(o1 *Object, o2 *Object) *Object

// Returns the result of dividing o1 by o2 giving an integral result, possibly
// in-place, or NULL on failure.
//
// This is the equivalent of the Python expression: o1 /= o2.
//
//go:linkname NumberInPlaceFloorDivide C.PyNumber_InPlaceFloorDivide
func NumberInPlaceFloorDivide(o1 *Object, o2 *Object) *Object

// Returns the result of dividing o1 by o2 giving a float result, possibly
// in-place, or null on failure.
//
// This is the equivalent of the Python expression: o1 /= o2.
//
//go:linkname NumberInPlaceTrueDivide C.PyNumber_InPlaceTrueDivide
func NumberInPlaceTrueDivide(o1 *Object, o2 *Object) *Object

// Returns the remainder of dividing o1 by o2, possibly in-place, or NULL on
// failure.
//
// This is the equivalent of the Python expression: o1 %= o2.
//
//go:linkname NumberInPlaceRemainder C.PyNumber_InPlaceRemainder
func NumberInPlaceRemainder(o1 *Object, o2 *Object) *Object

// Returns the result of raising o1 to the power of o2, possibly in-place,
// or NULL on failure.
//
// This is the equivalent of the Python expression: o1 **= o2,
// or o1 = pow(o1, o2, o3) if o3 is present.
//
//go:linkname NumberInPlacePower C.PyNumber_InPlacePower
func NumberInPlacePower(o1 *Object, o2 *Object, o3 *Object) *Object

// Returns the result of left shifting o1 by o2, possibly in-place, or NULL
// on failure.
//
// This is the equivalent of the Python expression: o1 <<= o2.
//
//go:linkname NumberInPlaceLshift C.PyNumber_InPlaceLshift
func NumberInPlaceLshift(o1 *Object, o2 *Object) *Object

// Returns the result of right shifting o1 by o2, possibly in-place or NULL
// on failure.
//
// This is the equivalent of the Python expression: o1 >>= o2.
//
//go:linkname NumberInPlaceRshift C.PyNumber_InPlaceRshift
func NumberInPlaceRshift(o1 *Object, o2 *Object) *Object

// Returns the result of bitwise and of o1 and o2, possibly in-place, or NULL
// on failure.
//
// This is the equivalent of the Python expression: o1 &= o2.
//
//go:linkname NumberInPlaceAnd C.PyNumber_InPlaceAnd
func NumberInPlaceAnd(o1 *Object, o2 *Object) *Object

// Returns the bitwise exclusive or of o1 by o2, possibly in-place, or NULL
// on failure.
//
// This is the equivalent of the Python expression: o1 ^= o2.
//
//go:linkname NumberInPlaceXor C.PyNumber_InPlaceXor
func NumberInPlaceXor(o1 *Object, o2 *Object) *Object

// Returns the result of bitwise or of o1 and o2, possibly in-place,
// or NULL on failure.
//
// This is the equivalent of the Python expression: o1 |= o2.
//
//go:linkname NumberInPlaceOr C.PyNumber_InPlaceOr
func NumberInPlaceOr(o1 *Object, o2 *Object) *Object

// Returns the integer n converted to a string with a base, with a base
// marker of 0b, 0o or 0x prefixed if applicable.
//
// If n is not an int object, it is converted with PyNumber_Index first.
//
//go:linkname NumberToBase C.PyNumber_ToBase
func NumberToBase(n *Object, base c.Int) *Object

// Return 1 if the object provides sequence protocol, and zero
// otherwise.
//
// This function always succeeds.
//
//go:linkname SequenceCheck C.PySequence_Check
func SequenceCheck(o *Object) c.Int

// Return the size of sequence object o, or -1 on failure.
//
//go:linkname SequenceSize C.PySequence_Size
func SequenceSize(o *Object) SsizeT

//go:linkname SequenceLength C.PySequence_Length
func SequenceLength(o *Object) SsizeT

// Return the concatenation of o1 and o2 on success, and NULL on failure.
//
// This is the equivalent of the Python expression: o1 + o2.
//
//go:linkname SequenceConcat C.PySequence_Concat
func SequenceConcat(o1 *Object, o2 *Object) *Object

// Return the result of repeating sequence object 'o' 'count' times,
// or NULL on failure.
//
// This is the equivalent of the Python expression: o * count.
//
//go:linkname SequenceRepeat C.PySequence_Repeat
func SequenceRepeat(o *Object, count SsizeT) *Object

// Return the ith element of o, or NULL on failure.
//
// This is the equivalent of the Python expression: o[i].
//
//go:linkname SequenceGetItem C.PySequence_GetItem
func SequenceGetItem(o *Object, i SsizeT) *Object

// Return the slice of sequence object o between i1 and i2, or NULL on failure.
//
// This is the equivalent of the Python expression: o[i1:i2].
//
//go:linkname SequenceGetSlice C.PySequence_GetSlice
func SequenceGetSlice(o *Object, i1 SsizeT, i2 SsizeT) *Object

// Assign object 'v' to the ith element of the sequence 'o'. Raise an exception
// and return -1 on failure; return 0 on success.
//
// This is the equivalent of the Python statement o[i] = v.
//
//go:linkname SequenceSetItem C.PySequence_SetItem
func SequenceSetItem(o *Object, i SsizeT, v *Object) c.Int

// Delete the 'i'-th element of the sequence 'v'. Returns -1 on failure.
//
// This is the equivalent of the Python statement: del o[i].
//
//go:linkname SequenceDelItem C.PySequence_DelItem
func SequenceDelItem(o *Object, i SsizeT) c.Int

// Assign the sequence object 'v' to the slice in sequence object 'o',
// from 'i1' to 'i2'. Returns -1 on failure.
//
// This is the equivalent of the Python statement: o[i1:i2] = v.
//
//go:linkname SequenceSetSlice C.PySequence_SetSlice
func SequenceSetSlice(o *Object, i1 SsizeT, i2 SsizeT, v *Object) c.Int

// Delete the slice in sequence object 'o' from 'i1' to 'i2'.
// Returns -1 on failure.
//
// This is the equivalent of the Python statement: del o[i1:i2].
//
//go:linkname SequenceDelSlice C.PySequence_DelSlice
func SequenceDelSlice(o *Object, i1 SsizeT, i2 SsizeT) c.Int

// Returns the sequence 'o' as a tuple on success, and NULL on failure.
//
// This is equivalent to the Python expression: tuple(o).
//
//go:linkname SequenceTuple C.PySequence_Tuple
func SequenceTuple(o *Object) *Object

// Returns the sequence 'o' as a list on success, and NULL on failure.
// This is equivalent to the Python expression: list(o)
//
//go:linkname SequenceList C.PySequence_List
func SequenceList(o *Object) *Object

// Return the sequence 'o' as a list, unless it's already a tuple or list.
//
// Use PySequence_Fast_GET_ITEM to access the members of this list, and
// PySequence_Fast_GET_SIZE to get its length.
//
// Returns NULL on failure.  If the object does not support iteration, raises a
// TypeError exception with 'm' as the message text.
//
//go:linkname SequenceFast C.PySequence_Fast
func SequenceFast(o *Object, m *c.Char) *Object

// Return the number of occurrences on value on 'o', that is, return
// the number of keys for which o[key] == value.
//
// On failure, return -1.  This is equivalent to the Python expression:
// o.count(value).
//
//go:linkname SequenceCount C.PySequence_Count
func SequenceCount(o *Object, value *Object) SsizeT

// Return 1 if 'ob' is in the sequence 'seq'; 0 if 'ob' is not in the sequence
// 'seq'; -1 on error.
//
// Use __contains__ if possible, else _PySequence_IterSearch().
//
//go:linkname SequenceContains C.PySequence_Contains
func SequenceContains(seq *Object, ob *Object) c.Int

// Determine if the sequence 'o' contains 'value'. If an item in 'o' is equal
// to 'value', return 1, otherwise return 0. On error, return -1.
//
// This is equivalent to the Python expression: value in o.
//
//go:linkname SequenceIn C.PySequence_In
func SequenceIn(o *Object, value *Object) c.Int

// Return the first index for which o[i] == value.
// On error, return -1.
//
// This is equivalent to the Python expression: o.index(value).
//
//go:linkname SequenceIndex C.PySequence_Index
func SequenceIndex(o *Object, value *Object) SsizeT

// Append sequence 'o2' to sequence 'o1', in-place when possible. Return the
// resulting object, which could be 'o1', or NULL on failure.
//
// This is the equivalent of the Python expression: o1 += o2.
//
//go:linkname SequenceInPlaceConcat C.PySequence_InPlaceConcat
func SequenceInPlaceConcat(o1 *Object, o2 *Object) *Object

// Repeat sequence 'o' by 'count', in-place when possible. Return the resulting
// object, which could be 'o', or NULL on failure.
//
// This is the equivalent of the Python expression: o1 *= count.
//
//go:linkname SequenceInPlaceRepeat C.PySequence_InPlaceRepeat
func SequenceInPlaceRepeat(o *Object, count SsizeT) *Object

// Return 1 if the object provides mapping protocol, and 0 otherwise.
//
// This function always succeeds.
//
//go:linkname MappingCheck C.PyMapping_Check
func MappingCheck(o *Object) c.Int

// Returns the number of keys in mapping object 'o' on success, and -1 on
// failure. This is equivalent to the Python expression: len(o).
//
//go:linkname MappingSize C.PyMapping_Size
func MappingSize(o *Object) SsizeT

//go:linkname MappingLength C.PyMapping_Length
func MappingLength(o *Object) SsizeT

// On success, return 1 if the mapping object 'o' has the key 'key',
// and 0 otherwise.
//
// This is equivalent to the Python expression: key in o.
//
// This function always succeeds.
//
//go:linkname MappingHasKeyString C.PyMapping_HasKeyString
func MappingHasKeyString(o *Object, key *c.Char) c.Int

// Return 1 if the mapping object has the key 'key', and 0 otherwise.
//
// This is equivalent to the Python expression: key in o.
//
// This function always succeeds.
//
//go:linkname MappingHasKey C.PyMapping_HasKey
func MappingHasKey(o *Object, key *Object) c.Int

// Return 1 if the mapping object has the key 'key', and 0 otherwise.
// This is equivalent to the Python expression: key in o.
// On failure, return -1.
//
//go:linkname MappingHasKeyWithError C.PyMapping_HasKeyWithError
func MappingHasKeyWithError(o *Object, key *Object) c.Int

// Return 1 if the mapping object has the key 'key', and 0 otherwise.
// This is equivalent to the Python expression: key in o.
// On failure, return -1.
//
//go:linkname MappingHasKeyStringWithError C.PyMapping_HasKeyStringWithError
func MappingHasKeyStringWithError(o *Object, key *c.Char) c.Int

// On success, return a list of the keys in mapping object 'o'.
// On failure, return NULL.
//
//go:linkname MappingKeys C.PyMapping_Keys
func MappingKeys(o *Object) *Object

// On success, return a list of the values in mapping object 'o'.
// On failure, return NULL.
//
//go:linkname MappingValues C.PyMapping_Values
func MappingValues(o *Object) *Object

// On success, return a list of the items in mapping object 'o',
// where each item is a tuple containing a key-value pair. On failure, return
// NULL.
//
//go:linkname MappingItems C.PyMapping_Items
func MappingItems(o *Object) *Object

// Return element of 'o' corresponding to the string 'key' or NULL on failure.
//
// This is the equivalent of the Python expression: o[key].
//
//go:linkname MappingGetItemString C.PyMapping_GetItemString
func MappingGetItemString(o *Object, key *c.Char) *Object

//go:linkname MappingGetOptionalItem C.PyMapping_GetOptionalItem
func MappingGetOptionalItem(_llcppg_param1 *Object, _llcppg_param2 *Object, _llcppg_param3 **Object) c.Int

//go:linkname MappingGetOptionalItemString C.PyMapping_GetOptionalItemString
func MappingGetOptionalItemString(_llcppg_param1 *Object, _llcppg_param2 *c.Char, _llcppg_param3 **Object) c.Int

// Map the string 'key' to the value 'v' in the mapping 'o'.
// Returns -1 on failure.
//
// This is the equivalent of the Python statement: o[key]=v.
//
//go:linkname MappingSetItemString C.PyMapping_SetItemString
func MappingSetItemString(o *Object, key *c.Char, value *Object) c.Int

// isinstance(object, typeorclass)
//
// llgo:link (*Object).IsInstance C.PyObject_IsInstance
func (self *Object) IsInstance(typeorclass *Object) c.Int {
	return 0
}

// issubclass(object, typeorclass)
//
// llgo:link (*Object).IsSubclass C.PyObject_IsSubclass
func (self *Object) IsSubclass(typeorclass *Object) c.Int {
	return 0
}

// Like PyObject_CallMethod(), but expect a _Py_Identifier*
// as the method name.
//
//go:linkname X_ObjectCallMethodId C._PyObject_CallMethodId
func X_ObjectCallMethodId(obj *Object, name *X_Identifier, format *c.Char, __llgo_va_list ...any) *Object

// Convert keyword arguments from the FASTCALL (stack: C array, kwnames: tuple)
// format to a Python dictionary ("kwargs" dict).
//
// The type of kwnames keys is not checked. The final function getting
// arguments is responsible to check if all keys are strings, for example using
// PyArg_ParseTupleAndKeywords() or PyArg_ValidateKeywordArguments().
//
// Duplicate keys are merged using the last value. If duplicate keys must raise
// an exception, the caller is responsible to implement an explicit keys on
// kwnames.
//
//go:linkname X_StackAsDict C._PyStack_AsDict
func X_StackAsDict(values **Object, kwnames *Object) *Object

//go:linkname VectorcallFunction C.PyVectorcall_Function
func VectorcallFunction(callable *Object) Vectorcallfunc

// Same as PyObject_Vectorcall except that keyword arguments are passed as
// dict, which may be NULL if there are no keyword arguments.
//
// llgo:link (*Object).VectorcallDict C.PyObject_VectorcallDict
func (self *Object) VectorcallDict(args **Object, nargsf c.SizeT, kwargs *Object) *Object {
	return self
}

// llgo:link (*Object).CallOneArg C.PyObject_CallOneArg
func (self *Object) CallOneArg(arg *Object) *Object {
	return self
}

// Guess the size of object 'o' using len(o) or o.__length_hint__().
// If neither of those return a non-negative value, then return the default
// value.  If one of the calls fails, this function returns -1.
//
// llgo:link (*Object).LengthHint C.PyObject_LengthHint
func (self *Object) LengthHint(_llcppg_param2 SsizeT) SsizeT {
	return 0
}
