// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

// llgo:type C
type AuditHookFunction = func(_llcppg_param1 *c.Char, _llcppg_param2 *Object, _llcppg_param3 unsafe.Pointer) c.Int

//go:linkname SysAudit C.PySys_Audit
func SysAudit(event *c.Char, argFormat *c.Char, __llgo_va_list ...any) c.Int

//go:linkname SysAuditTuple C.PySys_AuditTuple
func SysAuditTuple(event *c.Char, args *Object) c.Int

//go:linkname SysAddAuditHook C.PySys_AddAuditHook
func SysAddAuditHook(_llcppg_param1 AuditHookFunction, _llcppg_param2 unsafe.Pointer) c.Int
