// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

//go:linkname X_Py_FalseStruct C._Py_FalseStruct
var X_Py_FalseStruct PyLongObject

//go:linkname X_Py_TrueStruct C._Py_TrueStruct
var X_Py_TrueStruct PyLongObject

// llgo:link (*PyObject).Py_IsTrue C.Py_IsTrue
func (self *PyObject) Py_IsTrue() c.Int {
	return 0
}

// llgo:link (*PyObject).Py_IsFalse C.Py_IsFalse
func (self *PyObject) Py_IsFalse() c.Int {
	return 0
}

//go:linkname PyBool_FromLong C.PyBool_FromLong
func PyBool_FromLong(_llcppg_param1 c.Long) *PyObject
