// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

//go:linkname PyByteArray_Type C.PyByteArray_Type
var PyByteArray_Type PyTypeObject

//go:linkname PyByteArrayIter_Type C.PyByteArrayIter_Type
var PyByteArrayIter_Type PyTypeObject

// llgo:link (*PyObject).PyByteArray_FromObject C.PyByteArray_FromObject
func (self *PyObject) PyByteArray_FromObject() *PyObject {
	return self
}

// llgo:link (*PyObject).PyByteArray_Concat C.PyByteArray_Concat
func (self *PyObject) PyByteArray_Concat(_llcppg_param2 *PyObject) *PyObject {
	return self
}

//go:linkname PyByteArray_FromStringAndSize C.PyByteArray_FromStringAndSize
func PyByteArray_FromStringAndSize(_llcppg_param1 *c.Char, _llcppg_param2 PySsizeT) *PyObject

// llgo:link (*PyObject).PyByteArray_Size C.PyByteArray_Size
func (self *PyObject) PyByteArray_Size() PySsizeT {
	return 0
}

// llgo:link (*PyObject).PyByteArray_AsString C.PyByteArray_AsString
func (self *PyObject) PyByteArray_AsString() *c.Char {
	return nil
}

// llgo:link (*PyObject).PyByteArray_Resize C.PyByteArray_Resize
func (self *PyObject) PyByteArray_Resize(_llcppg_param2 PySsizeT) c.Int {
	return 0
}
