// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type PyCellObject struct {
	ObBase PyObject
	ObRef  *PyObject
}

//go:linkname PyCell_Type C.PyCell_Type
var PyCell_Type PyTypeObject

// llgo:link (*PyObject).PyCell_New C.PyCell_New
func (self *PyObject) PyCell_New() *PyObject {
	return self
}

// llgo:link (*PyObject).PyCell_Get C.PyCell_Get
func (self *PyObject) PyCell_Get() *PyObject {
	return self
}

// llgo:link (*PyObject).PyCell_Set C.PyCell_Set
func (self *PyObject) PyCell_Set(_llcppg_param2 *PyObject) c.Int {
	return 0
}
