// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

type CellObject struct {
	ObBase Object
	ObRef  *Object
}

//go:linkname CellType C.PyCell_Type
var CellType TypeObject

type Cell struct {
	X_object
}

func (self *Object) AsCell() *Cell {
	return (*Cell)(unsafe.Pointer(self))
}

// llgo:link (*Cell).New C.PyCell_New
func (self *Cell) New() *Object {
	return nil
}

// llgo:link (*Cell).Get C.PyCell_Get
func (self *Cell) Get() *Object {
	return nil
}

// llgo:link (*Cell).Set C.PyCell_Set
func (self *Cell) Set(_llcppg_param2 *Object) c.Int {
	return 0
}
