// Code generated by llcppg; DO NOT EDIT.

package py

import _ "unsafe"

type MethodObject struct {
	ObBase        Object
	ImFunc        *Object
	ImSelf        *Object
	ImWeakreflist *Object
	Vectorcall    Vectorcallfunc
}
type InstanceMethodObject struct {
	ObBase Object
	Func   *Object
}

//go:linkname MethodType C.PyMethod_Type
var MethodType TypeObject

// llgo:link (*MethodObject).New C.PyMethod_New
func (self *MethodObject) New(_llcppg_param2 *Object) *Object {
	return nil
}

// llgo:link (*MethodObject).Function C.PyMethod_Function
func (self *MethodObject) Function() *Object {
	return nil
}

// llgo:link (*MethodObject).Self C.PyMethod_Self
func (self *MethodObject) Self() *Object {
	return nil
}

//go:linkname InstanceMethodType C.PyInstanceMethod_Type
var InstanceMethodType TypeObject

// llgo:link (*InstanceMethodObject).New C.PyInstanceMethod_New
func (self *InstanceMethodObject) New() *Object {
	return nil
}

// llgo:link (*InstanceMethodObject).Function C.PyInstanceMethod_Function
func (self *InstanceMethodObject) Function() *Object {
	return nil
}
