// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

const SingleInput = 256
const FileInput = 257
const EvalInput = 258
const FuncTypeInput = 345
const CF_MASK = 33423360
const CF_MASK_OBSOLETE = 16
const CF_SOURCE_IS_UTF8 = 256
const CF_DONT_IMPLY_DEDENT = 512
const CF_ONLY_AST = 1024
const CF_IGNORE_COOKIE = 2048
const CF_TYPE_COMMENTS = 4096
const CF_ALLOW_TOP_LEVEL_AWAIT = 8192
const CF_ALLOW_INCOMPLETE_INPUT = 16384
const CF_OPTIMIZED_AST = 33792
const CF_COMPILE_MASK = 62976
const FUTURE_NESTED_SCOPES = "nested_scopes"
const FUTURE_GENERATORS = "generators"
const FUTURE_DIVISION = "division"
const FUTURE_ABSOLUTE_IMPORT = "absolute_import"
const FUTURE_WITH_STATEMENT = "with_statement"
const FUTURE_PRINT_FUNCTION = "print_function"
const FUTURE_UNICODE_LITERALS = "unicode_literals"
const FUTURE_BARRY_AS_BDFL = "barry_as_FLUFL"
const FUTURE_GENERATOR_STOP = "generator_stop"
const FUTURE_ANNOTATIONS = "annotations"

type CompilerFlags struct {
	CfFlags          c.Int
	CfFeatureVersion c.Int
}

//go:linkname CompileOpcodeStackEffect C.PyCompile_OpcodeStackEffect
func CompileOpcodeStackEffect(opcode c.Int, oparg c.Int) c.Int

//go:linkname CompileOpcodeStackEffectWithJump C.PyCompile_OpcodeStackEffectWithJump
func CompileOpcodeStackEffectWithJump(opcode c.Int, oparg c.Int, jump c.Int) c.Int
