// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

//go:linkname PyComplex_Type C.PyComplex_Type
var PyComplex_Type PyTypeObject

//go:linkname PyComplex_FromDoubles C.PyComplex_FromDoubles
func PyComplex_FromDoubles(real c.Double, imag c.Double) *PyObject

// llgo:link (*PyObject).PyComplex_RealAsDouble C.PyComplex_RealAsDouble
func (self *PyObject) PyComplex_RealAsDouble() c.Double {
	return 0
}

// llgo:link (*PyObject).PyComplex_ImagAsDouble C.PyComplex_ImagAsDouble
func (self *PyObject) PyComplex_ImagAsDouble() c.Double {
	return 0
}
