// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

const PySingleInput = 256
const PyFileInput = 257
const PyEvalInput = 258
const PyFuncTypeInput = 345
const PyCF_MASK = 33423360
const PyCF_MASK_OBSOLETE = 16
const PyCF_SOURCE_IS_UTF8 = 256
const PyCF_DONT_IMPLY_DEDENT = 512
const PyCF_ONLY_AST = 1024
const PyCF_IGNORE_COOKIE = 2048
const PyCF_TYPE_COMMENTS = 4096
const PyCF_ALLOW_TOP_LEVEL_AWAIT = 8192
const PyCF_ALLOW_INCOMPLETE_INPUT = 16384
const PyCF_OPTIMIZED_AST = 33792
const PyCF_COMPILE_MASK = 62976
const FUTURE_NESTED_SCOPES = "nested_scopes"
const FUTURE_GENERATORS = "generators"
const FUTURE_DIVISION = "division"
const FUTURE_ABSOLUTE_IMPORT = "absolute_import"
const FUTURE_WITH_STATEMENT = "with_statement"
const FUTURE_PRINT_FUNCTION = "print_function"
const FUTURE_UNICODE_LITERALS = "unicode_literals"
const FUTURE_BARRY_AS_BDFL = "barry_as_FLUFL"
const FUTURE_GENERATOR_STOP = "generator_stop"
const FUTURE_ANNOTATIONS = "annotations"

type PyCompilerFlags struct {
	CfFlags          c.Int
	CfFeatureVersion c.Int
}

//go:linkname PyCompile_OpcodeStackEffect C.PyCompile_OpcodeStackEffect
func PyCompile_OpcodeStackEffect(opcode c.Int, oparg c.Int) c.Int

//go:linkname PyCompile_OpcodeStackEffectWithJump C.PyCompile_OpcodeStackEffectWithJump
func PyCompile_OpcodeStackEffectWithJump(opcode c.Int, oparg c.Int, jump c.Int) c.Int
