// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type ContextEvent c.Uint

const
// The current context has switched to a different context.  The object
// passed to the watch callback is the now-current contextvars.Context
// object, or None if no context is current.
CONTEXT_SWITCHED ContextEvent = 1

type X_pycontextobject struct {
}
type Context = X_pycontextobject
type X_pycontextvarobject struct {
}
type ContextVar = X_pycontextvarobject
type X_pycontexttokenobject struct {
}
type ContextToken = X_pycontexttokenobject

// Context object watcher callback function.  The object passed to the callback
// is event-specific; see PyContextEvent for details.
//
// if the callback returns with an exception set, it must return -1. Otherwise
// it should return 0
//
// llgo:type C
type ContextWatchCallback = func(_llcppg_param1 ContextEvent, _llcppg_param2 *Object) c.Int

//go:linkname ContextType C.PyContext_Type
var ContextType TypeObject

//go:linkname ContextVarType C.PyContextVar_Type
var ContextVarType TypeObject

//go:linkname ContextTokenType C.PyContextToken_Type
var ContextTokenType TypeObject

//go:linkname ContextNew C.PyContext_New
func ContextNew() *Object

//go:linkname ContextCopy C.PyContext_Copy
func ContextCopy(_llcppg_param1 *Object) *Object

//go:linkname ContextCopyCurrent C.PyContext_CopyCurrent
func ContextCopyCurrent() *Object

//go:linkname ContextEnter C.PyContext_Enter
func ContextEnter(_llcppg_param1 *Object) c.Int

//go:linkname ContextExit C.PyContext_Exit
func ContextExit(_llcppg_param1 *Object) c.Int

// Register a per-interpreter callback that will be invoked for context object
// enter/exit events.
//
// Returns a handle that may be passed to PyContext_ClearWatcher on success,
// or -1 and sets and error if no more handles are available.
//
//go:linkname ContextAddWatcher C.PyContext_AddWatcher
func ContextAddWatcher(callback ContextWatchCallback) c.Int

// Clear the watcher associated with the watcher_id handle.
//
// Returns 0 on success or -1 if no watcher exists for the provided id.
//
//go:linkname ContextClearWatcher C.PyContext_ClearWatcher
func ContextClearWatcher(watcher_id c.Int) c.Int

// Create a new context variable.
//
// default_value can be NULL.
//
//go:linkname ContextVarNew C.PyContextVar_New
func ContextVarNew(name *c.Char, default_value *Object) *Object

// Get a value for the variable.
//
// Returns -1 if an error occurred during lookup.
//
// Returns 0 if value either was or was not found.
//
// If value was found, *value will point to it.
// If not, it will point to:
//
// - default_value, if not NULL;
// - the default value of "var", if not NULL;
// - NULL.
//
// '*value' will be a new ref, if not NULL.
//
//go:linkname ContextVarGet C.PyContextVar_Get
func ContextVarGet(var_ *Object, default_value *Object, value **Object) c.Int

// Set a new value for the variable.
// Returns NULL if an error occurs.
//
//go:linkname ContextVarSet C.PyContextVar_Set
func ContextVarSet(var_ *Object, value *Object) *Object

// Reset a variable to its previous value.
// Returns 0 on success, -1 on error.
//
//go:linkname ContextVarReset C.PyContextVar_Reset
func ContextVarReset(var_ *Object, token *Object) c.Int
