// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type X_odictobject struct {
}
type PyODictObject = X_odictobject

//go:linkname PyODict_Type C.PyODict_Type
var PyODict_Type PyTypeObject

//go:linkname PyODictIter_Type C.PyODictIter_Type
var PyODictIter_Type PyTypeObject

//go:linkname PyODictKeys_Type C.PyODictKeys_Type
var PyODictKeys_Type PyTypeObject

//go:linkname PyODictItems_Type C.PyODictItems_Type
var PyODictItems_Type PyTypeObject

//go:linkname PyODictValues_Type C.PyODictValues_Type
var PyODictValues_Type PyTypeObject

//go:linkname PyODict_New C.PyODict_New
func PyODict_New() *PyObject

// llgo:link (*PyObject).PyODict_SetItem C.PyODict_SetItem
func (self *PyObject) PyODict_SetItem(key *PyObject, item *PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyODict_DelItem C.PyODict_DelItem
func (self *PyObject) PyODict_DelItem(key *PyObject) c.Int {
	return 0
}
