// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const PyInterpreterConfig_DEFAULT_GIL = 0
const PyInterpreterConfig_SHARED_GIL = 1
const PyInterpreterConfig_OWN_GIL = 2
const X_PyInterpreterConfig_LEGACY_CHECK_MULTI_INTERP_EXTENSIONS = 0

type PyInterpreterConfig struct {
	UseMainObmalloc            c.Int
	AllowFork                  c.Int
	AllowExec                  c.Int
	AllowThreads               c.Int
	AllowDaemonThreads         c.Int
	CheckMultiInterpExtensions c.Int
	Gil                        c.Int
}

// llgo:type C
type AtexitDatacallbackfunc = func(_llcppg_param1 unsafe.Pointer)

//go:linkname Py_FrozenMain C.Py_FrozenMain
func Py_FrozenMain(argc c.Int, argv **c.Char) c.Int

// llgo:link (*PyPreConfig).Py_PreInitialize C.Py_PreInitialize
func (self *PyPreConfig) Py_PreInitialize() PyStatus {
	return PyStatus{}
}

// llgo:link (*PyPreConfig).Py_PreInitializeFromBytesArgs C.Py_PreInitializeFromBytesArgs
func (self *PyPreConfig) Py_PreInitializeFromBytesArgs(argc PySsizeT, argv **c.Char) PyStatus {
	return PyStatus{}
}

// llgo:link (*PyPreConfig).Py_PreInitializeFromArgs C.Py_PreInitializeFromArgs
func (self *PyPreConfig) Py_PreInitializeFromArgs(argc PySsizeT, argv **c.WcharT) PyStatus {
	return PyStatus{}
}

// llgo:link (*PyConfig).Py_InitializeFromConfig C.Py_InitializeFromConfig
func (self *PyConfig) Py_InitializeFromConfig() PyStatus {
	return PyStatus{}
}

//go:linkname Py_RunMain C.Py_RunMain
func Py_RunMain() c.Int

// llgo:link PyStatus.Py_ExitStatusException C.Py_ExitStatusException
func (self PyStatus) Py_ExitStatusException() {
}

//go:linkname Py_FdIsInteractive C.Py_FdIsInteractive
func Py_FdIsInteractive(_llcppg_param1 *c.FILE, _llcppg_param2 *c.Char) c.Int

//go:linkname Py_NewInterpreterFromConfig C.Py_NewInterpreterFromConfig
func Py_NewInterpreterFromConfig(tstate_p **PyThreadState, config *PyInterpreterConfig) PyStatus

// llgo:link (*PyInterpreterState).PyUnstable_AtExit C.PyUnstable_AtExit
func (self *PyInterpreterState) PyUnstable_AtExit(_llcppg_param2 AtexitDatacallbackfunc, _llcppg_param3 unsafe.Pointer) c.Int {
	return 0
}
