// Code generated by llcppg; DO NOT EDIT.

package py

import "github.com/goplus/lib/c"

type X_traceback struct {
	ObBase   PyObject
	TbNext   *PyTracebackObject
	TbFrame  *PyFrameObject
	TbLasti  c.Int
	TbLineno c.Int
}
type PyTracebackObject = X_traceback
