// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type PyContextEvent c.Uint

const Py_CONTEXT_SWITCHED PyContextEvent = 1

type X_pycontextobject struct {
}
type PyContext = X_pycontextobject
type X_pycontextvarobject struct {
}
type PyContextVar = X_pycontextvarobject
type X_pycontexttokenobject struct {
}
type PyContextToken = X_pycontexttokenobject

// llgo:type C
type PyContext_WatchCallback = func(_llcppg_param1 PyContextEvent, _llcppg_param2 *PyObject) c.Int

//go:linkname PyContext_Type C.PyContext_Type
var PyContext_Type PyTypeObject

//go:linkname PyContextVar_Type C.PyContextVar_Type
var PyContextVar_Type PyTypeObject

//go:linkname PyContextToken_Type C.PyContextToken_Type
var PyContextToken_Type PyTypeObject

//go:linkname PyContext_New C.PyContext_New
func PyContext_New() *PyObject

// llgo:link (*PyObject).PyContext_Copy C.PyContext_Copy
func (self *PyObject) PyContext_Copy() *PyObject {
	return self
}

//go:linkname PyContext_CopyCurrent C.PyContext_CopyCurrent
func PyContext_CopyCurrent() *PyObject

// llgo:link (*PyObject).PyContext_Enter C.PyContext_Enter
func (self *PyObject) PyContext_Enter() c.Int {
	return 0
}

// llgo:link (*PyObject).PyContext_Exit C.PyContext_Exit
func (self *PyObject) PyContext_Exit() c.Int {
	return 0
}

//go:linkname PyContext_AddWatcher C.PyContext_AddWatcher
func PyContext_AddWatcher(callback PyContext_WatchCallback) c.Int

//go:linkname PyContext_ClearWatcher C.PyContext_ClearWatcher
func PyContext_ClearWatcher(watcher_id c.Int) c.Int

//go:linkname PyContextVar_New C.PyContextVar_New
func PyContextVar_New(name *c.Char, default_value *PyObject) *PyObject

// llgo:link (*PyObject).PyContextVar_Get C.PyContextVar_Get
func (self *PyObject) PyContextVar_Get(default_value *PyObject, value **PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyContextVar_Set C.PyContextVar_Set
func (self *PyObject) PyContextVar_Set(value *PyObject) *PyObject {
	return self
}

// llgo:link (*PyObject).PyContextVar_Reset C.PyContextVar_Reset
func (self *PyObject) PyContextVar_Reset(token *PyObject) c.Int {
	return 0
}
