// Code generated by llcppg; DO NOT EDIT.

package py

import "github.com/goplus/lib/c"

type PyListObject struct {
	ObBase    PyVarObject
	ObItem    **PyObject
	Allocated PySsizeT
}

// llgo:link (*PyObject).PyList_Extend C.PyList_Extend
func (self *PyObject) PyList_Extend(iterable *PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyList_Clear C.PyList_Clear
func (self *PyObject) PyList_Clear() c.Int {
	return 0
}
