// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const PyLong_SHIFT = 30
const X_PyLong_DECIMAL_SHIFT = 9
const X_PyLong_SIGN_MASK = 3
const X_PyLong_NON_SIZE_BITS = 3

type X_longobject struct {
	ObBase    PyObject
	LongValue X_PyLongValue
}
type Digit = c.Uint32T
type Sdigit = c.Int32T
type Twodigits = c.Uint64T
type Stwodigits = c.Int64T
type X_PyLongValue struct {
	LvTag   c.UintptrT
	ObDigit [1]Digit
}
type PyLongLayout struct {
	BitsPerDigit    c.Uint8T
	DigitSize       c.Uint8T
	DigitsOrder     c.Int8T
	DigitEndianness c.Int8T
}
type PyLongExport struct {
	Value      c.Int64T
	Negative   c.Uint8T
	Ndigits    PySsizeT
	Digits     unsafe.Pointer
	X_reserved PyUintptrT
}
type PyLongWriter struct {
}

//go:linkname X_PyLong_New C._PyLong_New
func X_PyLong_New(_llcppg_param1 PySsizeT) *PyLongObject

// llgo:link (*PyLongObject).X_PyLong_Copy C._PyLong_Copy
func (self *PyLongObject) X_PyLong_Copy() *PyObject {
	return nil
}

//go:linkname X_PyLong_FromDigits C._PyLong_FromDigits
func X_PyLong_FromDigits(negative c.Int, digit_count PySsizeT, digits *Digit) *PyLongObject

//go:linkname PyLong_GetNativeLayout C.PyLong_GetNativeLayout
func PyLong_GetNativeLayout() *PyLongLayout

// llgo:link (*PyObject).PyLong_Export C.PyLong_Export
func (self *PyObject) PyLong_Export(export_long *PyLongExport) c.Int {
	return 0
}

// llgo:link (*PyLongExport).PyLong_FreeExport C.PyLong_FreeExport
func (self *PyLongExport) PyLong_FreeExport() {
}

//go:linkname PyLongWriter_Create C.PyLongWriter_Create
func PyLongWriter_Create(negative c.Int, ndigits PySsizeT, digits *unsafe.Pointer) *PyLongWriter

// llgo:link (*PyLongWriter).Finish C.PyLongWriter_Finish
func (self *PyLongWriter) Finish() *PyObject {
	return nil
}

// llgo:link (*PyLongWriter).Discard C.PyLongWriter_Discard
func (self *PyLongWriter) Discard() {
}
