// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const PyWrapperFlag_KEYWORDS = 1

// llgo:type C
type Wrapperfunc = func(_llcppg_param1 *PyObject, _llcppg_param2 *PyObject, _llcppg_param3 unsafe.Pointer) *PyObject

// llgo:type C
type WrapperfuncKwds = func(_llcppg_param1 *PyObject, _llcppg_param2 *PyObject, _llcppg_param3 unsafe.Pointer, _llcppg_param4 *PyObject) *PyObject
type Wrapperbase struct {
	Name       *c.Char
	Offset     c.Int
	Function   unsafe.Pointer
	Wrapper    Wrapperfunc
	Doc        *c.Char
	Flags      c.Int
	NameStrobj *PyObject
}
type PyDescrObject struct {
	ObBase    PyObject
	DType     *PyTypeObject
	DName     *PyObject
	DQualname *PyObject
}
type PyMethodDescrObject struct {
	DCommon    PyDescrObject
	DMethod    *PyMethodDef
	Vectorcall Vectorcallfunc
}
type PyMemberDescrObject struct {
	DCommon PyDescrObject
	DMember *PyMemberDef
}
type PyGetSetDescrObject struct {
	DCommon PyDescrObject
	DGetset *PyGetSetDef
}
type PyWrapperDescrObject struct {
	DCommon  PyDescrObject
	DBase    *Wrapperbase
	DWrapped unsafe.Pointer
}

// llgo:link (*PyTypeObject).PyDescr_NewWrapper C.PyDescr_NewWrapper
func (self *PyTypeObject) PyDescr_NewWrapper(_llcppg_param2 *Wrapperbase, _llcppg_param3 unsafe.Pointer) *PyObject {
	return nil
}

// llgo:link (*PyObject).PyDescr_IsData C.PyDescr_IsData
func (self *PyObject) PyDescr_IsData() c.Int {
	return 0
}
