// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type PyTupleObject struct {
	ObBase PyVarObject
	ObHash PyHashT
	ObItem [1]*PyObject
}

//go:linkname X_PyTuple_Resize C._PyTuple_Resize
func X_PyTuple_Resize(_llcppg_param1 **PyObject, _llcppg_param2 PySsizeT) c.Int
