// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

const PyUnstable_EXECUTABLE_KIND_SKIP = 0
const PyUnstable_EXECUTABLE_KIND_PY_FUNCTION = 1
const PyUnstable_EXECUTABLE_KIND_BUILTIN_FUNCTION = 3
const PyUnstable_EXECUTABLE_KIND_METHOD_DESCRIPTOR = 4
const PyUnstable_EXECUTABLE_KINDS = 5

type X_PyInterpreterFrame struct {
}

//go:linkname PyFrame_Type C.PyFrame_Type
var PyFrame_Type PyTypeObject

//go:linkname PyFrameLocalsProxy_Type C.PyFrameLocalsProxy_Type
var PyFrameLocalsProxy_Type PyTypeObject

// llgo:link (*PyFrameObject).PyFrame_GetBack C.PyFrame_GetBack
func (self *PyFrameObject) PyFrame_GetBack() *PyFrameObject {
	return self
}

// llgo:link (*PyFrameObject).PyFrame_GetLocals C.PyFrame_GetLocals
func (self *PyFrameObject) PyFrame_GetLocals() *PyObject {
	return nil
}

// llgo:link (*PyFrameObject).PyFrame_GetGlobals C.PyFrame_GetGlobals
func (self *PyFrameObject) PyFrame_GetGlobals() *PyObject {
	return nil
}

// llgo:link (*PyFrameObject).PyFrame_GetBuiltins C.PyFrame_GetBuiltins
func (self *PyFrameObject) PyFrame_GetBuiltins() *PyObject {
	return nil
}

// llgo:link (*PyFrameObject).PyFrame_GetGenerator C.PyFrame_GetGenerator
func (self *PyFrameObject) PyFrame_GetGenerator() *PyObject {
	return nil
}

// llgo:link (*PyFrameObject).PyFrame_GetLasti C.PyFrame_GetLasti
func (self *PyFrameObject) PyFrame_GetLasti() c.Int {
	return 0
}

// llgo:link (*PyFrameObject).PyFrame_GetVar C.PyFrame_GetVar
func (self *PyFrameObject) PyFrame_GetVar(name *PyObject) *PyObject {
	return nil
}

// llgo:link (*PyFrameObject).PyFrame_GetVarString C.PyFrame_GetVarString
func (self *PyFrameObject) PyFrame_GetVarString(name *c.Char) *PyObject {
	return nil
}

// llgo:link (*X_PyInterpreterFrame).PyUnstable_InterpreterFrame_GetCode C.PyUnstable_InterpreterFrame_GetCode
func (self *X_PyInterpreterFrame) PyUnstable_InterpreterFrame_GetCode() *PyObject {
	return nil
}

// llgo:link (*X_PyInterpreterFrame).PyUnstable_InterpreterFrame_GetLasti C.PyUnstable_InterpreterFrame_GetLasti
func (self *X_PyInterpreterFrame) PyUnstable_InterpreterFrame_GetLasti() c.Int {
	return 0
}

// llgo:link (*X_PyInterpreterFrame).PyUnstable_InterpreterFrame_GetLine C.PyUnstable_InterpreterFrame_GetLine
func (self *X_PyInterpreterFrame) PyUnstable_InterpreterFrame_GetLine() c.Int {
	return 0
}
