// Code generated by llcppg; DO NOT EDIT.

package py

import "github.com/goplus/lib/c"

type X_PyWeakReference struct {
	ObBase     PyObject
	WrObject   *PyObject
	WrCallback *PyObject
	Hash       PyHashT
	WrPrev     *PyWeakReference
	WrNext     *PyWeakReference
	Vectorcall Vectorcallfunc
}

// llgo:link (*PyWeakReference).X_PyWeakref_ClearRef C._PyWeakref_ClearRef
func (self *PyWeakReference) X_PyWeakref_ClearRef() {
}

// llgo:link (*PyObject).PyWeakref_IsDead C.PyWeakref_IsDead
func (self *PyObject) PyWeakref_IsDead() c.Int {
	return 0
}
