// Code generated by llcppg; DO NOT EDIT.

package py

const PySet_MINSIZE = 8

type Setentry struct {
	Key  *PyObject
	Hash PyHashT
}
type PySetObject struct {
	ObBase      PyObject
	Fill        PySsizeT
	Used        PySsizeT
	Mask        PySsizeT
	Table       *Setentry
	Hash        PyHashT
	Finger      PySsizeT
	Smalltable  [8]Setentry
	Weakreflist *PyObject
}
