// Code generated by llcppg; DO NOT EDIT.

package py

import "github.com/goplus/lib/c"

// llgo:link (*PyObject).PyErr_WarnExplicitObject C.PyErr_WarnExplicitObject
func (self *PyObject) PyErr_WarnExplicitObject(message *PyObject, filename *PyObject, lineno c.Int, module *PyObject, registry *PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyErr_WarnExplicitFormat C.PyErr_WarnExplicitFormat
func (self *PyObject) PyErr_WarnExplicitFormat(filename *c.Char, lineno c.Int, module *c.Char, registry *PyObject, format *c.Char, __llgo_va_list ...any) c.Int {
	return 0
}
