// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type PyDict_WatchEvent c.Uint

const (
	PyDict_EVENT_ADDED       PyDict_WatchEvent = 0
	PyDict_EVENT_MODIFIED    PyDict_WatchEvent = 1
	PyDict_EVENT_DELETED     PyDict_WatchEvent = 2
	PyDict_EVENT_CLONED      PyDict_WatchEvent = 3
	PyDict_EVENT_CLEARED     PyDict_WatchEvent = 4
	PyDict_EVENT_DEALLOCATED PyDict_WatchEvent = 5
)

type PyDictKeysObject = X_dictkeysobject
type X_dictvalues struct {
}
type PyDictValues = X_dictvalues
type PyDictObject struct {
	ObBase         PyObject
	MaUsed         PySsizeT
	X_maWatcherTag c.Uint64T
	MaKeys         *PyDictKeysObject
	MaValues       *PyDictValues
}

// llgo:type C
type PyDict_WatchCallback = func(_llcppg_param1 PyDict_WatchEvent, _llcppg_param2 *PyObject, _llcppg_param3 *PyObject, _llcppg_param4 *PyObject) c.Int

// llgo:link (*PyObject).X_PyDict_GetItem_KnownHash C._PyDict_GetItem_KnownHash
func (self *PyObject) X_PyDict_GetItem_KnownHash(key *PyObject, hash PyHashT) *PyObject {
	return self
}

// llgo:link (*PyObject).X_PyDict_GetItemStringWithError C._PyDict_GetItemStringWithError
func (self *PyObject) X_PyDict_GetItemStringWithError(_llcppg_param2 *c.Char) *PyObject {
	return self
}

// llgo:link (*PyObject).PyDict_SetDefault C.PyDict_SetDefault
func (self *PyObject) PyDict_SetDefault(key *PyObject, defaultobj *PyObject) *PyObject {
	return self
}

// llgo:link (*PyObject).PyDict_SetDefaultRef C.PyDict_SetDefaultRef
func (self *PyObject) PyDict_SetDefaultRef(key *PyObject, default_value *PyObject, result **PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyDict_ContainsString C.PyDict_ContainsString
func (self *PyObject) PyDict_ContainsString(key *c.Char) c.Int {
	return 0
}

//go:linkname X_PyDict_NewPresized C._PyDict_NewPresized
func X_PyDict_NewPresized(minused PySsizeT) *PyObject

// llgo:link (*PyObject).PyDict_Pop C.PyDict_Pop
func (self *PyObject) PyDict_Pop(key *PyObject, result **PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyDict_PopString C.PyDict_PopString
func (self *PyObject) PyDict_PopString(key *c.Char, result **PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).X_PyDict_Pop C._PyDict_Pop
func (self *PyObject) X_PyDict_Pop(key *PyObject, default_value *PyObject) *PyObject {
	return self
}

//go:linkname PyDict_AddWatcher C.PyDict_AddWatcher
func PyDict_AddWatcher(callback PyDict_WatchCallback) c.Int

//go:linkname PyDict_ClearWatcher C.PyDict_ClearWatcher
func PyDict_ClearWatcher(watcher_id c.Int) c.Int

//go:linkname PyDict_Watch C.PyDict_Watch
func PyDict_Watch(watcher_id c.Int, dict *PyObject) c.Int

//go:linkname PyDict_Unwatch C.PyDict_Unwatch
func PyDict_Unwatch(watcher_id c.Int, dict *PyObject) c.Int
