// Code generated by llcppg; DO NOT EDIT.

package py

import _ "unsafe"

type CriticalSection struct {
}
type CriticalSection2 struct {
}

//go:linkname CriticalSectionBegin C.PyCriticalSection_Begin
func CriticalSectionBegin(c *CriticalSection, op *Object)

//go:linkname CriticalSectionBeginMutex C.PyCriticalSection_BeginMutex
func CriticalSectionBeginMutex(c *CriticalSection, m *Mutex)

//go:linkname CriticalSectionEnd C.PyCriticalSection_End
func CriticalSectionEnd(c *CriticalSection)

//go:linkname CriticalSection2Begin C.PyCriticalSection2_Begin
func CriticalSection2Begin(c *CriticalSection2, a *Object, b *Object)

//go:linkname CriticalSection2BeginMutex C.PyCriticalSection2_BeginMutex
func CriticalSection2BeginMutex(c *CriticalSection2, m1 *Mutex, m2 *Mutex)

//go:linkname CriticalSection2End C.PyCriticalSection2_End
func CriticalSection2End(c *CriticalSection2)
