// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const Py_T_SHORT = 0
const Py_T_INT = 1
const Py_T_LONG = 2
const Py_T_FLOAT = 3
const Py_T_DOUBLE = 4
const Py_T_STRING = 5
const X_Py_T_OBJECT = 6
const Py_T_CHAR = 7
const Py_T_BYTE = 8
const Py_T_UBYTE = 9
const Py_T_USHORT = 10
const Py_T_UINT = 11
const Py_T_ULONG = 12
const Py_T_STRING_INPLACE = 13
const Py_T_BOOL = 14
const Py_T_OBJECT_EX = 16
const Py_T_LONGLONG = 17
const Py_T_ULONGLONG = 18
const Py_T_PYSSIZET = 19
const X_Py_T_NONE = 20
const Py_READONLY = 1
const Py_AUDIT_READ = 2
const X_Py_WRITE_RESTRICTED = 4
const Py_RELATIVE_OFFSET = 8

type PyGetSetDef struct {
	Name    *c.Char
	Get     Getter
	Set     Setter
	Doc     *c.Char
	Closure unsafe.Pointer
}
type PyMemberDef struct {
	Name   *c.Char
	Type   c.Int
	Offset PySsizeT
	Flags  c.Int
	Doc    *c.Char
}

// llgo:type C
type Getter = func(_llcppg_param1 *PyObject, _llcppg_param2 unsafe.Pointer) *PyObject

// llgo:type C
type Setter = func(_llcppg_param1 *PyObject, _llcppg_param2 *PyObject, _llcppg_param3 unsafe.Pointer) c.Int

//go:linkname PyClassMethodDescr_Type C.PyClassMethodDescr_Type
var PyClassMethodDescr_Type PyTypeObject

//go:linkname PyGetSetDescr_Type C.PyGetSetDescr_Type
var PyGetSetDescr_Type PyTypeObject

//go:linkname PyMemberDescr_Type C.PyMemberDescr_Type
var PyMemberDescr_Type PyTypeObject

//go:linkname PyMethodDescr_Type C.PyMethodDescr_Type
var PyMethodDescr_Type PyTypeObject

//go:linkname PyWrapperDescr_Type C.PyWrapperDescr_Type
var PyWrapperDescr_Type PyTypeObject

//go:linkname PyDictProxy_Type C.PyDictProxy_Type
var PyDictProxy_Type PyTypeObject

//go:linkname PyProperty_Type C.PyProperty_Type
var PyProperty_Type PyTypeObject

// llgo:link (*PyTypeObject).PyDescr_NewMethod C.PyDescr_NewMethod
func (self *PyTypeObject) PyDescr_NewMethod(_llcppg_param2 *PyMethodDef) *PyObject {
	return nil
}

// llgo:link (*PyTypeObject).PyDescr_NewClassMethod C.PyDescr_NewClassMethod
func (self *PyTypeObject) PyDescr_NewClassMethod(_llcppg_param2 *PyMethodDef) *PyObject {
	return nil
}

// llgo:link (*PyTypeObject).PyDescr_NewMember C.PyDescr_NewMember
func (self *PyTypeObject) PyDescr_NewMember(_llcppg_param2 *PyMemberDef) *PyObject {
	return nil
}

// llgo:link (*PyTypeObject).PyDescr_NewGetSet C.PyDescr_NewGetSet
func (self *PyTypeObject) PyDescr_NewGetSet(_llcppg_param2 *PyGetSetDef) *PyObject {
	return nil
}

// llgo:link (*PyObject).PyDictProxy_New C.PyDictProxy_New
func (self *PyObject) PyDictProxy_New() *PyObject {
	return self
}

// llgo:link (*PyObject).PyWrapper_New C.PyWrapper_New
func (self *PyObject) PyWrapper_New(_llcppg_param2 *PyObject) *PyObject {
	return self
}

//go:linkname PyMember_GetOne C.PyMember_GetOne
func PyMember_GetOne(_llcppg_param1 *c.Char, _llcppg_param2 *PyMemberDef) *PyObject

//go:linkname PyMember_SetOne C.PyMember_SetOne
func PyMember_SetOne(_llcppg_param1 *c.Char, _llcppg_param2 *PyMemberDef, _llcppg_param3 *PyObject) c.Int
