// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

type DictWatchEvent c.Uint

const (
	Dict_EVENT_ADDED       DictWatchEvent = 0
	Dict_EVENT_MODIFIED    DictWatchEvent = 1
	Dict_EVENT_DELETED     DictWatchEvent = 2
	Dict_EVENT_CLONED      DictWatchEvent = 3
	Dict_EVENT_CLEARED     DictWatchEvent = 4
	Dict_EVENT_DEALLOCATED DictWatchEvent = 5
)

type DictKeysObject = X_dictkeysobject
type X_dictvalues struct {
}
type DictValues = X_dictvalues

// The ma_values pointer is NULL for a combined table
// or points to an array of PyObject* for a split table
type DictObject struct {
	ObBase         Object
	MaUsed         SsizeT
	X_maWatcherTag c.Uint64T
	MaKeys         *DictKeysObject
	MaValues       *DictValues
}

// Callback to be invoked when a watched dict is cleared, dealloced, or modified.
// In clear/dealloc case, key and new_value will be NULL. Otherwise, new_value will be the
// new value for key, NULL if key is being deleted.
//
// llgo:type C
type DictWatchCallback = func(_llcppg_param1 DictWatchEvent, _llcppg_param2 *Object, _llcppg_param3 *Object, _llcppg_param4 *Object) c.Int

// The distribution includes a separate file, Objects/dictnotes.txt,
// describing explorations into dictionary design and optimization.
// It covers typical dictionary use patterns, the parameters for
// tuning dictionaries, and several ideas for possible optimizations.
//
//go:linkname DictType C.PyDict_Type
var DictType TypeObject

//go:linkname DictNew C.PyDict_New
func DictNew() *Object

// llgo:link (*DictObject).Item C.PyDict_GetItem
func (self *DictObject) Item(key *Object) *Object {
	return nil
}

// llgo:link (*DictObject).ItemWithError C.PyDict_GetItemWithError
func (self *DictObject) ItemWithError(key *Object) *Object {
	return nil
}

// llgo:link (*DictObject).SetItem C.PyDict_SetItem
func (self *DictObject) SetItem(key *Object, item *Object) c.Int {
	return 0
}

// llgo:link (*DictObject).DelItem C.PyDict_DelItem
func (self *DictObject) DelItem(key *Object) c.Int {
	return 0
}

// llgo:link (*DictObject).Clear C.PyDict_Clear
func (self *DictObject) Clear() {
}

// llgo:link (*DictObject).Next C.PyDict_Next
func (self *DictObject) Next(pos *SsizeT, key **Object, value **Object) c.Int {
	return 0
}

// llgo:link (*DictObject).Keys C.PyDict_Keys
func (self *DictObject) Keys() *Object {
	return nil
}

// llgo:link (*DictObject).Values C.PyDict_Values
func (self *DictObject) Values() *Object {
	return nil
}

// llgo:link (*DictObject).Items C.PyDict_Items
func (self *DictObject) Items() *Object {
	return nil
}

// llgo:link (*DictObject).Size C.PyDict_Size
func (self *DictObject) Size() SsizeT {
	return 0
}

// llgo:link (*DictObject).Copy C.PyDict_Copy
func (self *DictObject) Copy() *Object {
	return nil
}

// llgo:link (*DictObject).Contains C.PyDict_Contains
func (self *DictObject) Contains(key *Object) c.Int {
	return 0
}

// PyDict_Update(mp, other) is equivalent to PyDict_Merge(mp, other, 1).
//
// llgo:link (*DictObject).Update C.PyDict_Update
func (self *DictObject) Update(other *Object) c.Int {
	return 0
}

// PyDict_Merge updates/merges from a mapping object (an object that
// supports PyMapping_Keys() and PyObject_GetItem()).  If override is true,
// the last occurrence of a key wins, else the first.  The Python
// dict.update(other) is equivalent to PyDict_Merge(dict, other, 1).
//
// llgo:link (*DictObject).Merge C.PyDict_Merge
func (self *DictObject) Merge(other *Object, override c.Int) c.Int {
	return 0
}

// PyDict_MergeFromSeq2 updates/merges from an iterable object producing
// iterable objects of length 2.  If override is true, the last occurrence
// of a key wins, else the first.  The Python dict constructor dict(seq2)
// is equivalent to dict={}; PyDict_MergeFromSeq(dict, seq2, 1).
//
// llgo:link (*DictObject).MergeFromSeq2 C.PyDict_MergeFromSeq2
func (self *DictObject) MergeFromSeq2(seq2 *Object, override c.Int) c.Int {
	return 0
}

// llgo:link (*DictObject).ItemString C.PyDict_GetItemString
func (self *DictObject) ItemString(key *c.Char) *Object {
	return nil
}

// llgo:link (*DictObject).SetItemString C.PyDict_SetItemString
func (self *DictObject) SetItemString(key *c.Char, item *Object) c.Int {
	return 0
}

// llgo:link (*DictObject).DelItemString C.PyDict_DelItemString
func (self *DictObject) DelItemString(key *c.Char) c.Int {
	return 0
}

// Return the object from dictionary *op* which has a key *key*.
// - If the key is present, set *result to a new strong reference to the value
//   and return 1.
// - If the key is missing, set *result to NULL and return 0 .
// - On error, raise an exception and return -1.
//
// llgo:link (*DictObject).ItemRef C.PyDict_GetItemRef
func (self *DictObject) ItemRef(key *Object, result **Object) c.Int {
	return 0
}

// llgo:link (*DictObject).ItemStringRef C.PyDict_GetItemStringRef
func (self *DictObject) ItemStringRef(key *c.Char, result **Object) c.Int {
	return 0
}

// llgo:link (*Object).GenericGetDict C.PyObject_GenericGetDict
func (self *Object) GenericGetDict(_llcppg_param2 unsafe.Pointer) *Object {
	return self
}

// Dictionary (keys, values, items) views
//
//go:linkname DictKeysType C.PyDictKeys_Type
var DictKeysType TypeObject

//go:linkname DictValuesType C.PyDictValues_Type
var DictValuesType TypeObject

//go:linkname DictItemsType C.PyDictItems_Type
var DictItemsType TypeObject

// Dictionary (key, value, items) iterators
//
//go:linkname DictIterKeyType C.PyDictIterKey_Type
var DictIterKeyType TypeObject

//go:linkname DictIterValueType C.PyDictIterValue_Type
var DictIterValueType TypeObject

//go:linkname DictIterItemType C.PyDictIterItem_Type
var DictIterItemType TypeObject

//go:linkname DictRevIterKeyType C.PyDictRevIterKey_Type
var DictRevIterKeyType TypeObject

//go:linkname DictRevIterItemType C.PyDictRevIterItem_Type
var DictRevIterItemType TypeObject

//go:linkname DictRevIterValueType C.PyDictRevIterValue_Type
var DictRevIterValueType TypeObject

//go:linkname X_DictGetItemKnownHash C._PyDict_GetItem_KnownHash
func X_DictGetItemKnownHash(mp *Object, key *Object, hash HashT) *Object

// PyDict_GetItemStringRef() can be used instead
//
//go:linkname X_DictGetItemStringWithError C._PyDict_GetItemStringWithError
func X_DictGetItemStringWithError(_llcppg_param1 *Object, _llcppg_param2 *c.Char) *Object

// llgo:link (*DictObject).SetDefault C.PyDict_SetDefault
func (self *DictObject) SetDefault(key *Object, defaultobj *Object) *Object {
	return nil
}

// Inserts `key` with a value `default_value`, if `key` is not already present
// in the dictionary.  If `result` is not NULL, then the value associated
// with `key` is returned in `*result` (either the existing value, or the now
// inserted `default_value`).
// Returns:
//   -1 on error
//    0 if `key` was not present and `default_value` was inserted
//    1 if `key` was present and `default_value` was not inserted
//
// llgo:link (*DictObject).SetDefaultRef C.PyDict_SetDefaultRef
func (self *DictObject) SetDefaultRef(key *Object, default_value *Object, result **Object) c.Int {
	return 0
}

// llgo:link (*DictObject).ContainsString C.PyDict_ContainsString
func (self *DictObject) ContainsString(key *c.Char) c.Int {
	return 0
}

//go:linkname X_DictNewPresized C._PyDict_NewPresized
func X_DictNewPresized(minused SsizeT) *Object

// llgo:link (*DictObject).Pop C.PyDict_Pop
func (self *DictObject) Pop(key *Object, result **Object) c.Int {
	return 0
}

// llgo:link (*DictObject).PopString C.PyDict_PopString
func (self *DictObject) PopString(key *c.Char, result **Object) c.Int {
	return 0
}

// Use PyDict_Pop() instead
//
//go:linkname X_DictPop C._PyDict_Pop
func X_DictPop(dict *Object, key *Object, default_value *Object) *Object

// Register/unregister a dict-watcher callback
//
//go:linkname DictAddWatcher C.PyDict_AddWatcher
func DictAddWatcher(callback DictWatchCallback) c.Int

//go:linkname DictClearWatcher C.PyDict_ClearWatcher
func DictClearWatcher(watcher_id c.Int) c.Int

// Mark given dictionary as "watched" (callback will be called if it is modified)
//
//go:linkname DictWatch C.PyDict_Watch
func DictWatch(watcher_id c.Int, dict *Object) c.Int

//go:linkname DictUnwatch C.PyDict_Unwatch
func DictUnwatch(watcher_id c.Int, dict *Object) c.Int
