// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

type PyDict_WatchEvent c.Uint

const (
	PyDict_EVENT_ADDED       PyDict_WatchEvent = 0
	PyDict_EVENT_MODIFIED    PyDict_WatchEvent = 1
	PyDict_EVENT_DELETED     PyDict_WatchEvent = 2
	PyDict_EVENT_CLONED      PyDict_WatchEvent = 3
	PyDict_EVENT_CLEARED     PyDict_WatchEvent = 4
	PyDict_EVENT_DEALLOCATED PyDict_WatchEvent = 5
)

type PyDictKeysObject = X_dictkeysobject
type X_dictvalues struct {
}
type PyDictValues = X_dictvalues
type PyDictObject struct {
	ObBase         PyObject
	MaUsed         PySsizeT
	X_maWatcherTag c.Uint64T
	MaKeys         *PyDictKeysObject
	MaValues       *PyDictValues
}

// llgo:type C
type PyDict_WatchCallback = func(_llcppg_param1 PyDict_WatchEvent, _llcppg_param2 *PyObject, _llcppg_param3 *PyObject, _llcppg_param4 *PyObject) c.Int

//go:linkname PyDict_Type C.PyDict_Type
var PyDict_Type PyTypeObject

//go:linkname PyDict_New C.PyDict_New
func PyDict_New() *PyObject

// llgo:link (*PyObject).PyDict_GetItem C.PyDict_GetItem
func (self *PyObject) PyDict_GetItem(key *PyObject) *PyObject {
	return self
}

// llgo:link (*PyObject).PyDict_GetItemWithError C.PyDict_GetItemWithError
func (self *PyObject) PyDict_GetItemWithError(key *PyObject) *PyObject {
	return self
}

// llgo:link (*PyObject).PyDict_SetItem C.PyDict_SetItem
func (self *PyObject) PyDict_SetItem(key *PyObject, item *PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyDict_DelItem C.PyDict_DelItem
func (self *PyObject) PyDict_DelItem(key *PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyDict_Clear C.PyDict_Clear
func (self *PyObject) PyDict_Clear() {
}

// llgo:link (*PyObject).PyDict_Next C.PyDict_Next
func (self *PyObject) PyDict_Next(pos *PySsizeT, key **PyObject, value **PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyDict_Keys C.PyDict_Keys
func (self *PyObject) PyDict_Keys() *PyObject {
	return self
}

// llgo:link (*PyObject).PyDict_Values C.PyDict_Values
func (self *PyObject) PyDict_Values() *PyObject {
	return self
}

// llgo:link (*PyObject).PyDict_Items C.PyDict_Items
func (self *PyObject) PyDict_Items() *PyObject {
	return self
}

// llgo:link (*PyObject).PyDict_Size C.PyDict_Size
func (self *PyObject) PyDict_Size() PySsizeT {
	return 0
}

// llgo:link (*PyObject).PyDict_Copy C.PyDict_Copy
func (self *PyObject) PyDict_Copy() *PyObject {
	return self
}

// llgo:link (*PyObject).PyDict_Contains C.PyDict_Contains
func (self *PyObject) PyDict_Contains(key *PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyDict_Update C.PyDict_Update
func (self *PyObject) PyDict_Update(other *PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyDict_Merge C.PyDict_Merge
func (self *PyObject) PyDict_Merge(other *PyObject, override c.Int) c.Int {
	return 0
}

// llgo:link (*PyObject).PyDict_MergeFromSeq2 C.PyDict_MergeFromSeq2
func (self *PyObject) PyDict_MergeFromSeq2(seq2 *PyObject, override c.Int) c.Int {
	return 0
}

// llgo:link (*PyObject).PyDict_GetItemString C.PyDict_GetItemString
func (self *PyObject) PyDict_GetItemString(key *c.Char) *PyObject {
	return self
}

// llgo:link (*PyObject).PyDict_SetItemString C.PyDict_SetItemString
func (self *PyObject) PyDict_SetItemString(key *c.Char, item *PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyDict_DelItemString C.PyDict_DelItemString
func (self *PyObject) PyDict_DelItemString(key *c.Char) c.Int {
	return 0
}

// llgo:link (*PyObject).PyDict_GetItemRef C.PyDict_GetItemRef
func (self *PyObject) PyDict_GetItemRef(key *PyObject, result **PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyDict_GetItemStringRef C.PyDict_GetItemStringRef
func (self *PyObject) PyDict_GetItemStringRef(key *c.Char, result **PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).GenericGetDict C.PyObject_GenericGetDict
func (self *PyObject) GenericGetDict(_llcppg_param2 unsafe.Pointer) *PyObject {
	return self
}

//go:linkname PyDictKeys_Type C.PyDictKeys_Type
var PyDictKeys_Type PyTypeObject

//go:linkname PyDictValues_Type C.PyDictValues_Type
var PyDictValues_Type PyTypeObject

//go:linkname PyDictItems_Type C.PyDictItems_Type
var PyDictItems_Type PyTypeObject

//go:linkname PyDictIterKey_Type C.PyDictIterKey_Type
var PyDictIterKey_Type PyTypeObject

//go:linkname PyDictIterValue_Type C.PyDictIterValue_Type
var PyDictIterValue_Type PyTypeObject

//go:linkname PyDictIterItem_Type C.PyDictIterItem_Type
var PyDictIterItem_Type PyTypeObject

//go:linkname PyDictRevIterKey_Type C.PyDictRevIterKey_Type
var PyDictRevIterKey_Type PyTypeObject

//go:linkname PyDictRevIterItem_Type C.PyDictRevIterItem_Type
var PyDictRevIterItem_Type PyTypeObject

//go:linkname PyDictRevIterValue_Type C.PyDictRevIterValue_Type
var PyDictRevIterValue_Type PyTypeObject

// llgo:link (*PyObject).X_PyDict_GetItem_KnownHash C._PyDict_GetItem_KnownHash
func (self *PyObject) X_PyDict_GetItem_KnownHash(key *PyObject, hash PyHashT) *PyObject {
	return self
}

// llgo:link (*PyObject).X_PyDict_GetItemStringWithError C._PyDict_GetItemStringWithError
func (self *PyObject) X_PyDict_GetItemStringWithError(_llcppg_param2 *c.Char) *PyObject {
	return self
}

// llgo:link (*PyObject).PyDict_SetDefault C.PyDict_SetDefault
func (self *PyObject) PyDict_SetDefault(key *PyObject, defaultobj *PyObject) *PyObject {
	return self
}

// llgo:link (*PyObject).PyDict_SetDefaultRef C.PyDict_SetDefaultRef
func (self *PyObject) PyDict_SetDefaultRef(key *PyObject, default_value *PyObject, result **PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyDict_ContainsString C.PyDict_ContainsString
func (self *PyObject) PyDict_ContainsString(key *c.Char) c.Int {
	return 0
}

//go:linkname X_PyDict_NewPresized C._PyDict_NewPresized
func X_PyDict_NewPresized(minused PySsizeT) *PyObject

// llgo:link (*PyObject).PyDict_Pop C.PyDict_Pop
func (self *PyObject) PyDict_Pop(key *PyObject, result **PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyDict_PopString C.PyDict_PopString
func (self *PyObject) PyDict_PopString(key *c.Char, result **PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).X_PyDict_Pop C._PyDict_Pop
func (self *PyObject) X_PyDict_Pop(key *PyObject, default_value *PyObject) *PyObject {
	return self
}

//go:linkname PyDict_AddWatcher C.PyDict_AddWatcher
func PyDict_AddWatcher(callback PyDict_WatchCallback) c.Int

//go:linkname PyDict_ClearWatcher C.PyDict_ClearWatcher
func PyDict_ClearWatcher(watcher_id c.Int) c.Int

//go:linkname PyDict_Watch C.PyDict_Watch
func PyDict_Watch(watcher_id c.Int, dict *PyObject) c.Int

//go:linkname PyDict_Unwatch C.PyDict_Unwatch
func PyDict_Unwatch(watcher_id c.Int, dict *PyObject) c.Int
