// Code generated by llcppg; DO NOT EDIT.

package py

import _ "unsafe"

//go:linkname PyEnum_Type C.PyEnum_Type
var PyEnum_Type PyTypeObject

//go:linkname PyReversed_Type C.PyReversed_Type
var PyReversed_Type PyTypeObject
