// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

const PY_STDIOTEXTMODE = "b"

//go:linkname PyFile_FromFd C.PyFile_FromFd
func PyFile_FromFd(_llcppg_param1 c.Int, _llcppg_param2 *c.Char, _llcppg_param3 *c.Char, _llcppg_param4 c.Int, _llcppg_param5 *c.Char, _llcppg_param6 *c.Char, _llcppg_param7 *c.Char, _llcppg_param8 c.Int) *PyObject

// llgo:link (*PyObject).PyFile_GetLine C.PyFile_GetLine
func (self *PyObject) PyFile_GetLine(_llcppg_param2 c.Int) *PyObject {
	return self
}

// llgo:link (*PyObject).PyFile_WriteObject C.PyFile_WriteObject
func (self *PyObject) PyFile_WriteObject(_llcppg_param2 *PyObject, _llcppg_param3 c.Int) c.Int {
	return 0
}

//go:linkname PyFile_WriteString C.PyFile_WriteString
func PyFile_WriteString(_llcppg_param1 *c.Char, _llcppg_param2 *PyObject) c.Int

// llgo:link (*PyObject).AsFileDescriptor C.PyObject_AsFileDescriptor
func (self *PyObject) AsFileDescriptor() c.Int {
	return 0
}

//go:linkname Py_FileSystemDefaultEncoding C.Py_FileSystemDefaultEncoding
var Py_FileSystemDefaultEncoding *c.Char

//go:linkname Py_FileSystemDefaultEncodeErrors C.Py_FileSystemDefaultEncodeErrors
var Py_FileSystemDefaultEncodeErrors *c.Char

//go:linkname Py_HasFileSystemDefaultEncoding C.Py_HasFileSystemDefaultEncoding
var Py_HasFileSystemDefaultEncoding c.Int

//go:linkname Py_UTF8Mode C.Py_UTF8Mode
var Py_UTF8Mode c.Int
