// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type FloatObject struct {
	ObBase Object
	ObFval c.Double
}

//go:linkname FloatType C.PyFloat_Type
var FloatType TypeObject

//go:linkname FloatGetMax C.PyFloat_GetMax
func FloatGetMax() c.Double

//go:linkname FloatGetMin C.PyFloat_GetMin
func FloatGetMin() c.Double

//go:linkname FloatGetInfo C.PyFloat_GetInfo
func FloatGetInfo() *Object

// Return Python float from string PyObject.
//
// llgo:link (*FloatObject).FromString C.PyFloat_FromString
func (self *FloatObject) FromString() *Object {
	return nil
}

// Return Python float from C double.
//
//go:linkname FloatFromDouble C.PyFloat_FromDouble
func FloatFromDouble(_llcppg_param1 c.Double) *Object

// Extract C double from Python float.  The macro version trades safety for
// speed.
//
// llgo:link (*FloatObject).AsDouble C.PyFloat_AsDouble
func (self *FloatObject) AsDouble() c.Double {
	return 0
}

//go:linkname FloatPack2 C.PyFloat_Pack2
func FloatPack2(x c.Double, p *c.Char, le c.Int) c.Int

//go:linkname FloatPack4 C.PyFloat_Pack4
func FloatPack4(x c.Double, p *c.Char, le c.Int) c.Int

//go:linkname FloatPack8 C.PyFloat_Pack8
func FloatPack8(x c.Double, p *c.Char, le c.Int) c.Int

//go:linkname FloatUnpack2 C.PyFloat_Unpack2
func FloatUnpack2(p *c.Char, le c.Int) c.Double

//go:linkname FloatUnpack4 C.PyFloat_Unpack4
func FloatUnpack4(p *c.Char, le c.Int) c.Double

//go:linkname FloatUnpack8 C.PyFloat_Unpack8
func FloatUnpack8(p *c.Char, le c.Int) c.Double
