// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type FunctionWatchEvent c.Uint

const (
	Function_EVENT_CREATE            FunctionWatchEvent = 0
	Function_EVENT_DESTROY           FunctionWatchEvent = 1
	Function_EVENT_MODIFY_CODE       FunctionWatchEvent = 2
	Function_EVENT_MODIFY_DEFAULTS   FunctionWatchEvent = 3
	Function_EVENT_MODIFY_KWDEFAULTS FunctionWatchEvent = 4
)

type FrameConstructor struct {
	FcGlobals    *Object
	FcBuiltins   *Object
	FcName       *Object
	FcQualname   *Object
	FcCode       *Object
	FcDefaults   *Object
	FcKwdefaults *Object
	FcClosure    *Object
}

// Function objects and code objects should not be confused with each other:
//
// Function objects are created by the execution of the 'def' statement.
// They reference a code object in their __code__ attribute, which is a
// purely syntactic object, i.e. nothing more than a compiled version of some
// source code lines.  There is one code object per source code "fragment",
// but each code object can be referenced by zero or many function objects
// depending only on how many times the 'def' statement in the source was
// executed so far.
type FunctionObject struct {
	ObBase          Object
	FuncGlobals     *Object
	FuncBuiltins    *Object
	FuncName        *Object
	FuncQualname    *Object
	FuncCode        *Object
	FuncDefaults    *Object
	FuncKwdefaults  *Object
	FuncClosure     *Object
	FuncDoc         *Object
	FuncDict        *Object
	FuncWeakreflist *Object
	FuncModule      *Object
	FuncAnnotations *Object
	FuncAnnotate    *Object
	FuncTypeparams  *Object
	Vectorcall      Vectorcallfunc
	FuncVersion     c.Uint32T
}

// A callback that is invoked for different events in a function's lifecycle.
//
// The callback is invoked with a borrowed reference to func, after it is
// created and before it is modified or destroyed. The callback should not
// modify func.
//
// When a function's code object, defaults, or kwdefaults are modified the
// callback will be invoked with the respective event and new_value will
// contain a borrowed reference to the new value that is about to be stored in
// the function. Otherwise the third argument is NULL.
//
// If the callback returns with an exception set, it must return -1. Otherwise
// it should return 0.
//
// llgo:type C
type FunctionWatchCallback = func(_llcppg_param1 FunctionWatchEvent, _llcppg_param2 *FunctionObject, _llcppg_param3 *Object) c.Int

//go:linkname FunctionType C.PyFunction_Type
var FunctionType TypeObject

//go:linkname NewFunction C.PyFunction_New
func NewFunction(_llcppg_param1 *Object, _llcppg_param2 *Object) *FunctionObject

// llgo:link (*FunctionObject).NewWithQualName C.PyFunction_NewWithQualName
func (self *FunctionObject) NewWithQualName(_llcppg_param2 *Object, _llcppg_param3 *Object) *Object {
	return nil
}

// llgo:link (*FunctionObject).Code C.PyFunction_GetCode
func (self *FunctionObject) Code() *Object {
	return nil
}

// llgo:link (*FunctionObject).Globals C.PyFunction_GetGlobals
func (self *FunctionObject) Globals() *Object {
	return nil
}

// llgo:link (*FunctionObject).Module C.PyFunction_GetModule
func (self *FunctionObject) Module() *Object {
	return nil
}

// llgo:link (*FunctionObject).Defaults C.PyFunction_GetDefaults
func (self *FunctionObject) Defaults() *Object {
	return nil
}

// llgo:link (*FunctionObject).SetDefaults C.PyFunction_SetDefaults
func (self *FunctionObject) SetDefaults(_llcppg_param2 *Object) c.Int {
	return 0
}

// llgo:link (*FunctionObject).SetVectorcall C.PyFunction_SetVectorcall
func (self *FunctionObject) SetVectorcall(_llcppg_param2 Vectorcallfunc) {
}

// llgo:link (*FunctionObject).KwDefaults C.PyFunction_GetKwDefaults
func (self *FunctionObject) KwDefaults() *Object {
	return nil
}

// llgo:link (*FunctionObject).SetKwDefaults C.PyFunction_SetKwDefaults
func (self *FunctionObject) SetKwDefaults(_llcppg_param2 *Object) c.Int {
	return 0
}

// llgo:link (*FunctionObject).Closure C.PyFunction_GetClosure
func (self *FunctionObject) Closure() *Object {
	return nil
}

// llgo:link (*FunctionObject).SetClosure C.PyFunction_SetClosure
func (self *FunctionObject) SetClosure(_llcppg_param2 *Object) c.Int {
	return 0
}

// llgo:link (*FunctionObject).Annotations C.PyFunction_GetAnnotations
func (self *FunctionObject) Annotations() *Object {
	return nil
}

// llgo:link (*FunctionObject).SetAnnotations C.PyFunction_SetAnnotations
func (self *FunctionObject) SetAnnotations(_llcppg_param2 *Object) c.Int {
	return 0
}

// The classmethod and staticmethod types lives here, too
//
//go:linkname ClassMethodType C.PyClassMethod_Type
var ClassMethodType TypeObject

//go:linkname StaticMethodType C.PyStaticMethod_Type
var StaticMethodType TypeObject

//go:linkname ClassMethodNew C.PyClassMethod_New
func ClassMethodNew(_llcppg_param1 *Object) *Object

//go:linkname StaticMethodNew C.PyStaticMethod_New
func StaticMethodNew(_llcppg_param1 *Object) *Object

// Register a per-interpreter callback that will be invoked for function lifecycle
// events.
//
// Returns a handle that may be passed to PyFunction_ClearWatcher on success,
// or -1 and sets an error if no more handles are available.
//
//go:linkname FunctionAddWatcher C.PyFunction_AddWatcher
func FunctionAddWatcher(callback FunctionWatchCallback) c.Int

// Clear the watcher associated with the watcher_id handle.
//
// Returns 0 on success or -1 if no watcher exists for the supplied id.
//
//go:linkname FunctionClearWatcher C.PyFunction_ClearWatcher
func FunctionClearWatcher(watcher_id c.Int) c.Int
