// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type PyFunction_WatchEvent c.Uint

const (
	PyFunction_EVENT_CREATE            PyFunction_WatchEvent = 0
	PyFunction_EVENT_DESTROY           PyFunction_WatchEvent = 1
	PyFunction_EVENT_MODIFY_CODE       PyFunction_WatchEvent = 2
	PyFunction_EVENT_MODIFY_DEFAULTS   PyFunction_WatchEvent = 3
	PyFunction_EVENT_MODIFY_KWDEFAULTS PyFunction_WatchEvent = 4
)

type PyFrameConstructor struct {
	FcGlobals    *PyObject
	FcBuiltins   *PyObject
	FcName       *PyObject
	FcQualname   *PyObject
	FcCode       *PyObject
	FcDefaults   *PyObject
	FcKwdefaults *PyObject
	FcClosure    *PyObject
}
type PyFunctionObject struct {
	ObBase          PyObject
	FuncGlobals     *PyObject
	FuncBuiltins    *PyObject
	FuncName        *PyObject
	FuncQualname    *PyObject
	FuncCode        *PyObject
	FuncDefaults    *PyObject
	FuncKwdefaults  *PyObject
	FuncClosure     *PyObject
	FuncDoc         *PyObject
	FuncDict        *PyObject
	FuncWeakreflist *PyObject
	FuncModule      *PyObject
	FuncAnnotations *PyObject
	FuncAnnotate    *PyObject
	FuncTypeparams  *PyObject
	Vectorcall      Vectorcallfunc
	FuncVersion     c.Uint32T
}

// llgo:type C
type PyFunction_WatchCallback = func(_llcppg_param1 PyFunction_WatchEvent, _llcppg_param2 *PyFunctionObject, _llcppg_param3 *PyObject) c.Int

//go:linkname PyFunction_Type C.PyFunction_Type
var PyFunction_Type PyTypeObject

// llgo:link (*PyObject).PyFunction_New C.PyFunction_New
func (self *PyObject) PyFunction_New(_llcppg_param2 *PyObject) *PyObject {
	return self
}

// llgo:link (*PyObject).PyFunction_NewWithQualName C.PyFunction_NewWithQualName
func (self *PyObject) PyFunction_NewWithQualName(_llcppg_param2 *PyObject, _llcppg_param3 *PyObject) *PyObject {
	return self
}

// llgo:link (*PyObject).PyFunction_GetCode C.PyFunction_GetCode
func (self *PyObject) PyFunction_GetCode() *PyObject {
	return self
}

// llgo:link (*PyObject).PyFunction_GetGlobals C.PyFunction_GetGlobals
func (self *PyObject) PyFunction_GetGlobals() *PyObject {
	return self
}

// llgo:link (*PyObject).PyFunction_GetModule C.PyFunction_GetModule
func (self *PyObject) PyFunction_GetModule() *PyObject {
	return self
}

// llgo:link (*PyObject).PyFunction_GetDefaults C.PyFunction_GetDefaults
func (self *PyObject) PyFunction_GetDefaults() *PyObject {
	return self
}

// llgo:link (*PyObject).PyFunction_SetDefaults C.PyFunction_SetDefaults
func (self *PyObject) PyFunction_SetDefaults(_llcppg_param2 *PyObject) c.Int {
	return 0
}

// llgo:link (*PyFunctionObject).PyFunction_SetVectorcall C.PyFunction_SetVectorcall
func (self *PyFunctionObject) PyFunction_SetVectorcall(_llcppg_param2 Vectorcallfunc) {
}

// llgo:link (*PyObject).PyFunction_GetKwDefaults C.PyFunction_GetKwDefaults
func (self *PyObject) PyFunction_GetKwDefaults() *PyObject {
	return self
}

// llgo:link (*PyObject).PyFunction_SetKwDefaults C.PyFunction_SetKwDefaults
func (self *PyObject) PyFunction_SetKwDefaults(_llcppg_param2 *PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyFunction_GetClosure C.PyFunction_GetClosure
func (self *PyObject) PyFunction_GetClosure() *PyObject {
	return self
}

// llgo:link (*PyObject).PyFunction_SetClosure C.PyFunction_SetClosure
func (self *PyObject) PyFunction_SetClosure(_llcppg_param2 *PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyFunction_GetAnnotations C.PyFunction_GetAnnotations
func (self *PyObject) PyFunction_GetAnnotations() *PyObject {
	return self
}

// llgo:link (*PyObject).PyFunction_SetAnnotations C.PyFunction_SetAnnotations
func (self *PyObject) PyFunction_SetAnnotations(_llcppg_param2 *PyObject) c.Int {
	return 0
}

//go:linkname PyClassMethod_Type C.PyClassMethod_Type
var PyClassMethod_Type PyTypeObject

//go:linkname PyStaticMethod_Type C.PyStaticMethod_Type
var PyStaticMethod_Type PyTypeObject

// llgo:link (*PyObject).PyClassMethod_New C.PyClassMethod_New
func (self *PyObject) PyClassMethod_New() *PyObject {
	return self
}

// llgo:link (*PyObject).PyStaticMethod_New C.PyStaticMethod_New
func (self *PyObject) PyStaticMethod_New() *PyObject {
	return self
}

//go:linkname PyFunction_AddWatcher C.PyFunction_AddWatcher
func PyFunction_AddWatcher(callback PyFunction_WatchCallback) c.Int

//go:linkname PyFunction_ClearWatcher C.PyFunction_ClearWatcher
func PyFunction_ClearWatcher(watcher_id c.Int) c.Int
