// Code generated by llcppg; DO NOT EDIT.

package py

import _ "unsafe"

// llgo:link (*PyObject).Py_GenericAlias C.Py_GenericAlias
func (self *PyObject) Py_GenericAlias(_llcppg_param2 *PyObject) *PyObject {
	return self
}

//go:linkname Py_GenericAliasType C.Py_GenericAliasType
var Py_GenericAliasType PyTypeObject
