// Code generated by llcppg; DO NOT EDIT.

package py

import "unsafe"

type X_GenObject struct {
}

// --- Generators ---------------------------------------------------------
type GenObject = X_GenObject
type X_CoroObject struct {
}

// --- PyCoroObject -------------------------------------------------------
type CoroObject = X_CoroObject
type X_AsyncGenObject struct {
}

// --- Asynchronous Generators --------------------------------------------
type AsyncGenObject = X_AsyncGenObject

//go:linkname GenType C.PyGen_Type
var GenType TypeObject

type Gen struct {
	X_frame
}

func (self *FrameObject) AsGen() *Gen {
	return (*Gen)(unsafe.Pointer(self))
}

// llgo:link (*Gen).New C.PyGen_New
func (self *Gen) New() *Object {
	return nil
}

// llgo:link (*Gen).NewWithQualName C.PyGen_NewWithQualName
func (self *Gen) NewWithQualName(name *Object, qualname *Object) *Object {
	return nil
}

// llgo:link (*Gen).Code C.PyGen_GetCode
func (self *Gen) Code() *CodeObject {
	return nil
}

//go:linkname CoroType C.PyCoro_Type
var CoroType TypeObject

type Coro struct {
	X_frame
}

func (self *FrameObject) AsCoro() *Coro {
	return (*Coro)(unsafe.Pointer(self))
}

// llgo:link (*Coro).New C.PyCoro_New
func (self *Coro) New(name *Object, qualname *Object) *Object {
	return nil
}

//go:linkname AsyncGenType C.PyAsyncGen_Type
var AsyncGenType TypeObject

//go:linkname X_AsyncGenASendType C._PyAsyncGenASend_Type
var X_AsyncGenASendType TypeObject

type AsyncGen struct {
	X_frame
}

func (self *FrameObject) AsAsyncGen() *AsyncGen {
	return (*AsyncGen)(unsafe.Pointer(self))
}

// llgo:link (*AsyncGen).New C.PyAsyncGen_New
func (self *AsyncGen) New(name *Object, qualname *Object) *Object {
	return nil
}
