// Code generated by llcppg; DO NOT EDIT.

package py

import _ "unsafe"

type X_GenObject struct {
}

// --- Generators ---------------------------------------------------------
type GenObject = X_GenObject
type X_CoroObject struct {
}

// --- PyCoroObject -------------------------------------------------------
type CoroObject = X_CoroObject
type X_AsyncGenObject struct {
}

// --- Asynchronous Generators --------------------------------------------
type AsyncGenObject = X_AsyncGenObject

//go:linkname GenType C.PyGen_Type
var GenType TypeObject

//go:linkname GenNew C.PyGen_New
func GenNew(_llcppg_param1 *FrameObject) *Object

// llgo:link (*FrameObject).GenNewWithQualName C.PyGen_NewWithQualName
func (self *FrameObject) GenNewWithQualName(name *Object, qualname *Object) *Object {
	return nil
}

// llgo:link (*GenObject).Code C.PyGen_GetCode
func (self *GenObject) Code() *CodeObject {
	return nil
}

//go:linkname CoroType C.PyCoro_Type
var CoroType TypeObject

//go:linkname CoroNew C.PyCoro_New
func CoroNew(_llcppg_param1 *FrameObject, name *Object, qualname *Object) *Object

//go:linkname AsyncGenType C.PyAsyncGen_Type
var AsyncGenType TypeObject

//go:linkname X_AsyncGenASendType C._PyAsyncGenASend_Type
var X_AsyncGenASendType TypeObject

//go:linkname AsyncGenNew C.PyAsyncGen_New
func AsyncGenNew(_llcppg_param1 *FrameObject, name *Object, qualname *Object) *Object
