// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

// --- PyStatus -----------------------------------------------
type Status struct {
	X_type   _llcppg_anon_4
	Func     *c.Char
	ErrMsg   *c.Char
	Exitcode c.Int
}
type _llcppg_anon_4 c.Uint

const (
	X_Status_TYPE_OK    _llcppg_anon_4 = 0
	X_Status_TYPE_ERROR _llcppg_anon_4 = 1
	X_Status_TYPE_EXIT  _llcppg_anon_4 = 2
)

// --- PyWideStringList ------------------------------------------------
type WideStringList struct {
	Length SsizeT
	Items  **c.WcharT
}

// --- PyPreConfig -----------------------------------------------
type PreConfig struct {
	X_configInit      c.Int
	ParseArgv         c.Int
	Isolated          c.Int
	UseEnvironment    c.Int
	ConfigureLocale   c.Int
	CoerceCLocale     c.Int
	CoerceCLocaleWarn c.Int
	Utf8Mode          c.Int
	DevMode           c.Int
	Allocator         c.Int
}

// This structure is best documented in the Doc/c-api/init_config.rst file.
type Config struct {
	X_configInit          c.Int
	Isolated              c.Int
	UseEnvironment        c.Int
	DevMode               c.Int
	InstallSignalHandlers c.Int
	UseHashSeed           c.Int
	HashSeed              c.Ulong
	Faulthandler          c.Int
	Tracemalloc           c.Int
	PerfProfiling         c.Int
	RemoteDebug           c.Int
	ImportTime            c.Int
	CodeDebugRanges       c.Int
	ShowRefCount          c.Int
	DumpRefs              c.Int
	DumpRefsFile          *c.WcharT
	MallocStats           c.Int
	FilesystemEncoding    *c.WcharT
	FilesystemErrors      *c.WcharT
	PycachePrefix         *c.WcharT
	ParseArgv             c.Int
	OrigArgv              WideStringList
	Argv                  WideStringList
	Xoptions              WideStringList
	Warnoptions           WideStringList
	SiteImport            c.Int
	BytesWarning          c.Int
	WarnDefaultEncoding   c.Int
	Inspect               c.Int
	Interactive           c.Int
	OptimizationLevel     c.Int
	ParserDebug           c.Int
	WriteBytecode         c.Int
	Verbose               c.Int
	Quiet                 c.Int
	UserSiteDirectory     c.Int
	ConfigureCStdio       c.Int
	BufferedStdio         c.Int
	StdioEncoding         *c.WcharT
	StdioErrors           *c.WcharT
	CheckHashPycsMode     *c.WcharT
	UseFrozenModules      c.Int
	SafePath              c.Int
	IntMaxStrDigits       c.Int
	ThreadInheritContext  c.Int
	ContextAwareWarnings  c.Int
	UseSystemLogger       c.Int
	CpuCount              c.Int
	PathconfigWarnings    c.Int
	ProgramName           *c.WcharT
	PythonpathEnv         *c.WcharT
	Home                  *c.WcharT
	Platlibdir            *c.WcharT
	ModuleSearchPathsSet  c.Int
	ModuleSearchPaths     WideStringList
	StdlibDir             *c.WcharT
	Executable            *c.WcharT
	BaseExecutable        *c.WcharT
	Prefix                *c.WcharT
	BasePrefix            *c.WcharT
	ExecPrefix            *c.WcharT
	BaseExecPrefix        *c.WcharT
	SkipSourceFirstLine   c.Int
	RunCommand            *c.WcharT
	RunModule             *c.WcharT
	RunFilename           *c.WcharT
	SysPath0              *c.WcharT
	X_installImportlib    c.Int
	X_initMain            c.Int
	X_isPythonBuild       c.Int
}
type InitConfig struct {
}

//go:linkname StatusOk C.PyStatus_Ok
func StatusOk() Status

//go:linkname StatusError C.PyStatus_Error
func StatusError(err_msg *c.Char) Status

//go:linkname StatusNoMemory C.PyStatus_NoMemory
func StatusNoMemory() Status

//go:linkname StatusExit C.PyStatus_Exit
func StatusExit(exitcode c.Int) Status

//go:linkname StatusIsError C.PyStatus_IsError
func StatusIsError(err Status) c.Int

//go:linkname StatusIsExit C.PyStatus_IsExit
func StatusIsExit(err Status) c.Int

//go:linkname StatusException C.PyStatus_Exception
func StatusException(err Status) c.Int

//go:linkname WideStringListAppend C.PyWideStringList_Append
func WideStringListAppend(list *WideStringList, item *c.WcharT) Status

//go:linkname WideStringListInsert C.PyWideStringList_Insert
func WideStringListInsert(list *WideStringList, index SsizeT, item *c.WcharT) Status

//go:linkname PreConfigInitPythonConfig C.PyPreConfig_InitPythonConfig
func PreConfigInitPythonConfig(config *PreConfig)

//go:linkname PreConfigInitIsolatedConfig C.PyPreConfig_InitIsolatedConfig
func PreConfigInitIsolatedConfig(config *PreConfig)

//go:linkname ConfigInitPythonConfig C.PyConfig_InitPythonConfig
func ConfigInitPythonConfig(config *Config)

//go:linkname ConfigInitIsolatedConfig C.PyConfig_InitIsolatedConfig
func ConfigInitIsolatedConfig(config *Config)

//go:linkname ConfigClear C.PyConfig_Clear
func ConfigClear(_llcppg_param1 *Config)

//go:linkname ConfigSetString C.PyConfig_SetString
func ConfigSetString(config *Config, config_str **c.WcharT, str *c.WcharT) Status

//go:linkname ConfigSetBytesString C.PyConfig_SetBytesString
func ConfigSetBytesString(config *Config, config_str **c.WcharT, str *c.Char) Status

//go:linkname ConfigRead C.PyConfig_Read
func ConfigRead(config *Config) Status

//go:linkname ConfigSetBytesArgv C.PyConfig_SetBytesArgv
func ConfigSetBytesArgv(config *Config, argc SsizeT, argv **c.Char) Status

//go:linkname ConfigSetArgv C.PyConfig_SetArgv
func ConfigSetArgv(config *Config, argc SsizeT, argv **c.WcharT) Status

//go:linkname ConfigSetWideStringList C.PyConfig_SetWideStringList
func ConfigSetWideStringList(config *Config, list *WideStringList, length SsizeT, items **c.WcharT) Status

// --- PyConfig_Get() -----------------------------------------
//
//go:linkname ConfigGet C.PyConfig_Get
func ConfigGet(name *c.Char) *Object

//go:linkname ConfigGetInt C.PyConfig_GetInt
func ConfigGetInt(name *c.Char, value *c.Int) c.Int

//go:linkname ConfigNames C.PyConfig_Names
func ConfigNames() *Object

//go:linkname ConfigSet C.PyConfig_Set
func ConfigSet(name *c.Char, value *Object) c.Int

// Get the original command line arguments, before Python modified them.
//
// See also PyConfig.orig_argv.
//
//go:linkname GetArgcArgv C.Py_GetArgcArgv
func GetArgcArgv(argc *c.Int, argv ***c.WcharT)

//go:linkname InitConfigCreate C.PyInitConfig_Create
func InitConfigCreate() *InitConfig

// llgo:link (*InitConfig).Free C.PyInitConfig_Free
func (self *InitConfig) Free() {
}

// llgo:link (*InitConfig).Error C.PyInitConfig_GetError
func (self *InitConfig) Error(err_msg **c.Char) c.Int {
	return 0
}

// llgo:link (*InitConfig).ExitCode C.PyInitConfig_GetExitCode
func (self *InitConfig) ExitCode(exitcode *c.Int) c.Int {
	return 0
}

// llgo:link (*InitConfig).HasOption C.PyInitConfig_HasOption
func (self *InitConfig) HasOption(name *c.Char) c.Int {
	return 0
}

// llgo:link (*InitConfig).Int C.PyInitConfig_GetInt
func (self *InitConfig) Int(name *c.Char, value *c.Int64T) c.Int {
	return 0
}

// llgo:link (*InitConfig).Str C.PyInitConfig_GetStr
func (self *InitConfig) Str(name *c.Char, value **c.Char) c.Int {
	return 0
}

// llgo:link (*InitConfig).StrList C.PyInitConfig_GetStrList
func (self *InitConfig) StrList(name *c.Char, length *c.SizeT, items ***c.Char) c.Int {
	return 0
}

//go:linkname InitConfigFreeStrList C.PyInitConfig_FreeStrList
func InitConfigFreeStrList(length c.SizeT, items **c.Char)

// llgo:link (*InitConfig).SetInt C.PyInitConfig_SetInt
func (self *InitConfig) SetInt(name *c.Char, value c.Int64T) c.Int {
	return 0
}

// llgo:link (*InitConfig).SetStr C.PyInitConfig_SetStr
func (self *InitConfig) SetStr(name *c.Char, value *c.Char) c.Int {
	return 0
}

// llgo:link (*InitConfig).SetStrList C.PyInitConfig_SetStrList
func (self *InitConfig) SetStrList(name *c.Char, length c.SizeT, items **c.Char) c.Int {
	return 0
}

// llgo:link (*InitConfig).AddModule C.PyInitConfig_AddModule
func (self *InitConfig) AddModule(name *c.Char, initfunc func() *Object) c.Int {
	return 0
}

//go:linkname InitializeFromInitConfig C.Py_InitializeFromInitConfig
func InitializeFromInitConfig(config *InitConfig) c.Int
