// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

// --- PyStatus -----------------------------------------------
type PyStatus struct {
	X_type   _llcppg_anon_4
	Func     *c.Char
	ErrMsg   *c.Char
	Exitcode c.Int
}
type _llcppg_anon_4 c.Uint

const (
	X_PyStatus_TYPE_OK    _llcppg_anon_4 = 0
	X_PyStatus_TYPE_ERROR _llcppg_anon_4 = 1
	X_PyStatus_TYPE_EXIT  _llcppg_anon_4 = 2
)

// --- PyWideStringList ------------------------------------------------
type PyWideStringList struct {
	Length PySsizeT
	Items  **c.WcharT
}

// --- PyPreConfig -----------------------------------------------
type PyPreConfig struct {
	X_configInit      c.Int
	ParseArgv         c.Int
	Isolated          c.Int
	UseEnvironment    c.Int
	ConfigureLocale   c.Int
	CoerceCLocale     c.Int
	CoerceCLocaleWarn c.Int
	Utf8Mode          c.Int
	DevMode           c.Int
	Allocator         c.Int
}

// This structure is best documented in the Doc/c-api/init_config.rst file.
type PyConfig struct {
	X_configInit          c.Int
	Isolated              c.Int
	UseEnvironment        c.Int
	DevMode               c.Int
	InstallSignalHandlers c.Int
	UseHashSeed           c.Int
	HashSeed              c.Ulong
	Faulthandler          c.Int
	Tracemalloc           c.Int
	PerfProfiling         c.Int
	RemoteDebug           c.Int
	ImportTime            c.Int
	CodeDebugRanges       c.Int
	ShowRefCount          c.Int
	DumpRefs              c.Int
	DumpRefsFile          *c.WcharT
	MallocStats           c.Int
	FilesystemEncoding    *c.WcharT
	FilesystemErrors      *c.WcharT
	PycachePrefix         *c.WcharT
	ParseArgv             c.Int
	OrigArgv              PyWideStringList
	Argv                  PyWideStringList
	Xoptions              PyWideStringList
	Warnoptions           PyWideStringList
	SiteImport            c.Int
	BytesWarning          c.Int
	WarnDefaultEncoding   c.Int
	Inspect               c.Int
	Interactive           c.Int
	OptimizationLevel     c.Int
	ParserDebug           c.Int
	WriteBytecode         c.Int
	Verbose               c.Int
	Quiet                 c.Int
	UserSiteDirectory     c.Int
	ConfigureCStdio       c.Int
	BufferedStdio         c.Int
	StdioEncoding         *c.WcharT
	StdioErrors           *c.WcharT
	CheckHashPycsMode     *c.WcharT
	UseFrozenModules      c.Int
	SafePath              c.Int
	IntMaxStrDigits       c.Int
	ThreadInheritContext  c.Int
	ContextAwareWarnings  c.Int
	UseSystemLogger       c.Int
	CpuCount              c.Int
	PathconfigWarnings    c.Int
	ProgramName           *c.WcharT
	PythonpathEnv         *c.WcharT
	Home                  *c.WcharT
	Platlibdir            *c.WcharT
	ModuleSearchPathsSet  c.Int
	ModuleSearchPaths     PyWideStringList
	StdlibDir             *c.WcharT
	Executable            *c.WcharT
	BaseExecutable        *c.WcharT
	Prefix                *c.WcharT
	BasePrefix            *c.WcharT
	ExecPrefix            *c.WcharT
	BaseExecPrefix        *c.WcharT
	SkipSourceFirstLine   c.Int
	RunCommand            *c.WcharT
	RunModule             *c.WcharT
	RunFilename           *c.WcharT
	SysPath0              *c.WcharT
	X_installImportlib    c.Int
	X_initMain            c.Int
	X_isPythonBuild       c.Int
}
type PyInitConfig struct {
}

//go:linkname PyStatus_Ok C.PyStatus_Ok
func PyStatus_Ok() PyStatus

//go:linkname PyStatus_Error C.PyStatus_Error
func PyStatus_Error(err_msg *c.Char) PyStatus

//go:linkname PyStatus_NoMemory C.PyStatus_NoMemory
func PyStatus_NoMemory() PyStatus

//go:linkname PyStatus_Exit C.PyStatus_Exit
func PyStatus_Exit(exitcode c.Int) PyStatus

// llgo:link PyStatus.IsError C.PyStatus_IsError
func (self PyStatus) IsError() c.Int {
	return 0
}

// llgo:link PyStatus.IsExit C.PyStatus_IsExit
func (self PyStatus) IsExit() c.Int {
	return 0
}

// llgo:link PyStatus.Exception C.PyStatus_Exception
func (self PyStatus) Exception() c.Int {
	return 0
}

// llgo:link (*PyWideStringList).Append C.PyWideStringList_Append
func (self *PyWideStringList) Append(item *c.WcharT) PyStatus {
	return PyStatus{}
}

// llgo:link (*PyWideStringList).Insert C.PyWideStringList_Insert
func (self *PyWideStringList) Insert(index PySsizeT, item *c.WcharT) PyStatus {
	return PyStatus{}
}

// llgo:link (*PyPreConfig).InitPythonConfig C.PyPreConfig_InitPythonConfig
func (self *PyPreConfig) InitPythonConfig() {
}

// llgo:link (*PyPreConfig).InitIsolatedConfig C.PyPreConfig_InitIsolatedConfig
func (self *PyPreConfig) InitIsolatedConfig() {
}

// llgo:link (*PyConfig).InitPythonConfig C.PyConfig_InitPythonConfig
func (self *PyConfig) InitPythonConfig() {
}

// llgo:link (*PyConfig).InitIsolatedConfig C.PyConfig_InitIsolatedConfig
func (self *PyConfig) InitIsolatedConfig() {
}

// llgo:link (*PyConfig).Clear C.PyConfig_Clear
func (self *PyConfig) Clear() {
}

// llgo:link (*PyConfig).SetString C.PyConfig_SetString
func (self *PyConfig) SetString(config_str **c.WcharT, str *c.WcharT) PyStatus {
	return PyStatus{}
}

// llgo:link (*PyConfig).SetBytesString C.PyConfig_SetBytesString
func (self *PyConfig) SetBytesString(config_str **c.WcharT, str *c.Char) PyStatus {
	return PyStatus{}
}

// llgo:link (*PyConfig).Read C.PyConfig_Read
func (self *PyConfig) Read() PyStatus {
	return PyStatus{}
}

// llgo:link (*PyConfig).SetBytesArgv C.PyConfig_SetBytesArgv
func (self *PyConfig) SetBytesArgv(argc PySsizeT, argv **c.Char) PyStatus {
	return PyStatus{}
}

// llgo:link (*PyConfig).SetArgv C.PyConfig_SetArgv
func (self *PyConfig) SetArgv(argc PySsizeT, argv **c.WcharT) PyStatus {
	return PyStatus{}
}

// llgo:link (*PyConfig).SetWideStringList C.PyConfig_SetWideStringList
func (self *PyConfig) SetWideStringList(list *PyWideStringList, length PySsizeT, items **c.WcharT) PyStatus {
	return PyStatus{}
}

// --- PyConfig_Get() -----------------------------------------
//
//go:linkname PyConfig_Get C.PyConfig_Get
func PyConfig_Get(name *c.Char) *PyObject

//go:linkname PyConfig_GetInt C.PyConfig_GetInt
func PyConfig_GetInt(name *c.Char, value *c.Int) c.Int

//go:linkname PyConfig_Names C.PyConfig_Names
func PyConfig_Names() *PyObject

//go:linkname PyConfig_Set C.PyConfig_Set
func PyConfig_Set(name *c.Char, value *PyObject) c.Int

// Get the original command line arguments, before Python modified them.
//
// See also PyConfig.orig_argv.
//
//go:linkname Py_GetArgcArgv C.Py_GetArgcArgv
func Py_GetArgcArgv(argc *c.Int, argv ***c.WcharT)

//go:linkname PyInitConfig_Create C.PyInitConfig_Create
func PyInitConfig_Create() *PyInitConfig

// llgo:link (*PyInitConfig).Free C.PyInitConfig_Free
func (self *PyInitConfig) Free() {
}

// llgo:link (*PyInitConfig).Error C.PyInitConfig_GetError
func (self *PyInitConfig) Error(err_msg **c.Char) c.Int {
	return 0
}

// llgo:link (*PyInitConfig).ExitCode C.PyInitConfig_GetExitCode
func (self *PyInitConfig) ExitCode(exitcode *c.Int) c.Int {
	return 0
}

// llgo:link (*PyInitConfig).HasOption C.PyInitConfig_HasOption
func (self *PyInitConfig) HasOption(name *c.Char) c.Int {
	return 0
}

// llgo:link (*PyInitConfig).Int C.PyInitConfig_GetInt
func (self *PyInitConfig) Int(name *c.Char, value *c.Int64T) c.Int {
	return 0
}

// llgo:link (*PyInitConfig).Str C.PyInitConfig_GetStr
func (self *PyInitConfig) Str(name *c.Char, value **c.Char) c.Int {
	return 0
}

// llgo:link (*PyInitConfig).StrList C.PyInitConfig_GetStrList
func (self *PyInitConfig) StrList(name *c.Char, length *c.SizeT, items ***c.Char) c.Int {
	return 0
}

//go:linkname PyInitConfig_FreeStrList C.PyInitConfig_FreeStrList
func PyInitConfig_FreeStrList(length c.SizeT, items **c.Char)

// llgo:link (*PyInitConfig).SetInt C.PyInitConfig_SetInt
func (self *PyInitConfig) SetInt(name *c.Char, value c.Int64T) c.Int {
	return 0
}

// llgo:link (*PyInitConfig).SetStr C.PyInitConfig_SetStr
func (self *PyInitConfig) SetStr(name *c.Char, value *c.Char) c.Int {
	return 0
}

// llgo:link (*PyInitConfig).SetStrList C.PyInitConfig_SetStrList
func (self *PyInitConfig) SetStrList(name *c.Char, length c.SizeT, items **c.Char) c.Int {
	return 0
}

// llgo:link (*PyInitConfig).AddModule C.PyInitConfig_AddModule
func (self *PyInitConfig) AddModule(name *c.Char, initfunc func() *PyObject) c.Int {
	return 0
}

// llgo:link (*PyInitConfig).Py_InitializeFromInitConfig C.Py_InitializeFromInitConfig
func (self *PyInitConfig) Py_InitializeFromInitConfig() c.Int {
	return 0
}
