// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

//go:linkname PyOS_InterruptOccurred C.PyOS_InterruptOccurred
func PyOS_InterruptOccurred() c.Int

//go:linkname PyOS_BeforeFork C.PyOS_BeforeFork
func PyOS_BeforeFork()

//go:linkname PyOS_AfterFork_Parent C.PyOS_AfterFork_Parent
func PyOS_AfterFork_Parent()

//go:linkname PyOS_AfterFork_Child C.PyOS_AfterFork_Child
func PyOS_AfterFork_Child()

// Deprecated, please use PyOS_AfterFork_Child() instead
//
//go:linkname PyOS_AfterFork C.PyOS_AfterFork
func PyOS_AfterFork()
