// Code generated by llcppg; DO NOT EDIT.

package py

import "unsafe"

//go:linkname SeqIterType C.PySeqIter_Type
var SeqIterType TypeObject

//go:linkname CallIterType C.PyCallIter_Type
var CallIterType TypeObject

type SeqIter struct {
	X_object
}

func (self *Object) AsSeqIter() *SeqIter {
	return (*SeqIter)(unsafe.Pointer(self))
}

// llgo:link (*SeqIter).New C.PySeqIter_New
func (self *SeqIter) New() *Object {
	return nil
}

type CallIter struct {
	X_object
}

func (self *Object) AsCallIter() *CallIter {
	return (*CallIter)(unsafe.Pointer(self))
}

// llgo:link (*CallIter).New C.PyCallIter_New
func (self *CallIter) New(_llcppg_param2 *Object) *Object {
	return nil
}
