// Code generated by llcppg; DO NOT EDIT.

package py

import _ "unsafe"

//go:linkname PySeqIter_Type C.PySeqIter_Type
var PySeqIter_Type PyTypeObject

//go:linkname PyCallIter_Type C.PyCallIter_Type
var PyCallIter_Type PyTypeObject

// llgo:link (*PyObject).PySeqIter_New C.PySeqIter_New
func (self *PyObject) PySeqIter_New() *PyObject {
	return self
}

// llgo:link (*PyObject).PyCallIter_New C.PyCallIter_New
func (self *PyObject) PyCallIter_New(_llcppg_param2 *PyObject) *PyObject {
	return self
}
