// Code generated by llcppg; DO NOT EDIT.

package py

import _ "unsafe"

//go:linkname SeqIterType C.PySeqIter_Type
var SeqIterType TypeObject

//go:linkname CallIterType C.PyCallIter_Type
var CallIterType TypeObject

//go:linkname SeqIterNew C.PySeqIter_New
func SeqIterNew(_llcppg_param1 *Object) *Object

//go:linkname CallIterNew C.PyCallIter_New
func CallIterNew(_llcppg_param1 *Object, _llcppg_param2 *Object) *Object
