// Code generated by llcppg; DO NOT EDIT.

package py

import "github.com/goplus/lib/c"

const X_Py_UNLOCKED = 0
const X_Py_LOCKED = 1

type PyMutex struct {
	X_bits c.Uint8T
}

// llgo:link (*PyMutex).Lock C.PyMutex_Lock
func (self *PyMutex) Lock() {
}

// llgo:link (*PyMutex).Unlock C.PyMutex_Unlock
func (self *PyMutex) Unlock() {
}

// llgo:link (*PyMutex).IsLocked C.PyMutex_IsLocked
func (self *PyMutex) IsLocked() c.Int {
	return 0
}
