// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const Py_ASNATIVEBYTES_DEFAULTS = -1
const Py_ASNATIVEBYTES_BIG_ENDIAN = 0
const Py_ASNATIVEBYTES_LITTLE_ENDIAN = 1
const Py_ASNATIVEBYTES_NATIVE_ENDIAN = 3
const Py_ASNATIVEBYTES_UNSIGNED_BUFFER = 4
const Py_ASNATIVEBYTES_REJECT_NEGATIVE = 8
const Py_ASNATIVEBYTES_ALLOW_INDEX = 16
const X_Py_PARSE_PID = "i"
const X_Py_PARSE_INTPTR = "l"
const X_Py_PARSE_UINTPTR = "k"

//go:linkname PyLong_FromLong C.PyLong_FromLong
func PyLong_FromLong(_llcppg_param1 c.Long) *PyObject

//go:linkname PyLong_FromUnsignedLong C.PyLong_FromUnsignedLong
func PyLong_FromUnsignedLong(_llcppg_param1 c.Ulong) *PyObject

//go:linkname PyLongFromSizeT C.PyLong_FromSize_t
func PyLongFromSizeT(_llcppg_param1 c.SizeT) *PyObject

//go:linkname PyLongFromSsizeT C.PyLong_FromSsize_t
func PyLongFromSsizeT(_llcppg_param1 PySsizeT) *PyObject

//go:linkname PyLong_FromDouble C.PyLong_FromDouble
func PyLong_FromDouble(_llcppg_param1 c.Double) *PyObject

// llgo:link (*PyObject).PyLong_AsLong C.PyLong_AsLong
func (self *PyObject) PyLong_AsLong() c.Long {
	return 0
}

// llgo:link (*PyObject).PyLong_AsLongAndOverflow C.PyLong_AsLongAndOverflow
func (self *PyObject) PyLong_AsLongAndOverflow(_llcppg_param2 *c.Int) c.Long {
	return 0
}

// llgo:link (*PyObject).PyLongAsSsizeT C.PyLong_AsSsize_t
func (self *PyObject) PyLongAsSsizeT() PySsizeT {
	return 0
}

// llgo:link (*PyObject).PyLongAsSizeT C.PyLong_AsSize_t
func (self *PyObject) PyLongAsSizeT() c.SizeT {
	return 0
}

// llgo:link (*PyObject).PyLong_AsUnsignedLong C.PyLong_AsUnsignedLong
func (self *PyObject) PyLong_AsUnsignedLong() c.Ulong {
	return 0
}

// llgo:link (*PyObject).PyLong_AsUnsignedLongMask C.PyLong_AsUnsignedLongMask
func (self *PyObject) PyLong_AsUnsignedLongMask() c.Ulong {
	return 0
}

// llgo:link (*PyObject).PyLong_AsInt C.PyLong_AsInt
func (self *PyObject) PyLong_AsInt() c.Int {
	return 0
}

//go:linkname PyLong_FromInt32 C.PyLong_FromInt32
func PyLong_FromInt32(value c.Int32T) *PyObject

//go:linkname PyLong_FromUInt32 C.PyLong_FromUInt32
func PyLong_FromUInt32(value c.Uint32T) *PyObject

//go:linkname PyLong_FromInt64 C.PyLong_FromInt64
func PyLong_FromInt64(value c.Int64T) *PyObject

//go:linkname PyLong_FromUInt64 C.PyLong_FromUInt64
func PyLong_FromUInt64(value c.Uint64T) *PyObject

// llgo:link (*PyObject).PyLong_AsInt32 C.PyLong_AsInt32
func (self *PyObject) PyLong_AsInt32(value *c.Int32T) c.Int {
	return 0
}

// llgo:link (*PyObject).PyLong_AsUInt32 C.PyLong_AsUInt32
func (self *PyObject) PyLong_AsUInt32(value *c.Uint32T) c.Int {
	return 0
}

// llgo:link (*PyObject).PyLong_AsInt64 C.PyLong_AsInt64
func (self *PyObject) PyLong_AsInt64(value *c.Int64T) c.Int {
	return 0
}

// llgo:link (*PyObject).PyLong_AsUInt64 C.PyLong_AsUInt64
func (self *PyObject) PyLong_AsUInt64(value *c.Uint64T) c.Int {
	return 0
}

// llgo:link (*PyObject).PyLong_AsNativeBytes C.PyLong_AsNativeBytes
func (self *PyObject) PyLong_AsNativeBytes(buffer unsafe.Pointer, n_bytes PySsizeT, flags c.Int) PySsizeT {
	return 0
}

//go:linkname PyLong_FromNativeBytes C.PyLong_FromNativeBytes
func PyLong_FromNativeBytes(buffer unsafe.Pointer, n_bytes c.SizeT, flags c.Int) *PyObject

//go:linkname PyLong_FromUnsignedNativeBytes C.PyLong_FromUnsignedNativeBytes
func PyLong_FromUnsignedNativeBytes(buffer unsafe.Pointer, n_bytes c.SizeT, flags c.Int) *PyObject

//go:linkname PyLong_GetInfo C.PyLong_GetInfo
func PyLong_GetInfo() *PyObject

// llgo:link (*PyObject).PyLong_AsDouble C.PyLong_AsDouble
func (self *PyObject) PyLong_AsDouble() c.Double {
	return 0
}

//go:linkname PyLong_FromVoidPtr C.PyLong_FromVoidPtr
func PyLong_FromVoidPtr(_llcppg_param1 unsafe.Pointer) *PyObject

// llgo:link (*PyObject).PyLong_AsVoidPtr C.PyLong_AsVoidPtr
func (self *PyObject) PyLong_AsVoidPtr() unsafe.Pointer {
	return nil
}

//go:linkname PyLong_FromLongLong C.PyLong_FromLongLong
func PyLong_FromLongLong(_llcppg_param1 c.LongLong) *PyObject

//go:linkname PyLong_FromUnsignedLongLong C.PyLong_FromUnsignedLongLong
func PyLong_FromUnsignedLongLong(_llcppg_param1 c.UlongLong) *PyObject

// llgo:link (*PyObject).PyLong_AsLongLong C.PyLong_AsLongLong
func (self *PyObject) PyLong_AsLongLong() c.LongLong {
	return 0
}

// llgo:link (*PyObject).PyLong_AsUnsignedLongLong C.PyLong_AsUnsignedLongLong
func (self *PyObject) PyLong_AsUnsignedLongLong() c.UlongLong {
	return 0
}

// llgo:link (*PyObject).PyLong_AsUnsignedLongLongMask C.PyLong_AsUnsignedLongLongMask
func (self *PyObject) PyLong_AsUnsignedLongLongMask() c.UlongLong {
	return 0
}

// llgo:link (*PyObject).PyLong_AsLongLongAndOverflow C.PyLong_AsLongLongAndOverflow
func (self *PyObject) PyLong_AsLongLongAndOverflow(_llcppg_param2 *c.Int) c.LongLong {
	return 0
}

//go:linkname PyLong_FromString C.PyLong_FromString
func PyLong_FromString(_llcppg_param1 *c.Char, _llcppg_param2 **c.Char, _llcppg_param3 c.Int) *PyObject

//go:linkname PyOSStrtoul C.PyOS_strtoul
func PyOSStrtoul(_llcppg_param1 *c.Char, _llcppg_param2 **c.Char, _llcppg_param3 c.Int) c.Ulong

//go:linkname PyOSStrtol C.PyOS_strtol
func PyOSStrtol(_llcppg_param1 *c.Char, _llcppg_param2 **c.Char, _llcppg_param3 c.Int) c.Long
