// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

const METH_VARARGS = 1
const METH_KEYWORDS = 2
const METH_NOARGS = 4
const METH_O = 8
const METH_CLASS = 16
const METH_STATIC = 32
const METH_COEXIST = 64
const METH_FASTCALL = 128
const METH_STACKLESS = 0
const METH_METHOD = 512

type MethodDef struct {
	MlName  *c.Char
	MlMeth  CFunction
	MlFlags c.Int
	MlDoc   *c.Char
}

// llgo:type C
type CFunction = func(_llcppg_param1 *Object, _llcppg_param2 *Object) *Object

// llgo:type C
type CFunctionFast = func(_llcppg_param1 *Object, _llcppg_param2 **Object, _llcppg_param3 SsizeT) *Object

// llgo:type C
type CFunctionWithKeywords = func(_llcppg_param1 *Object, _llcppg_param2 *Object, _llcppg_param3 *Object) *Object

// llgo:type C
type CFunctionFastWithKeywords = func(_llcppg_param1 *Object, _llcppg_param2 **Object, _llcppg_param3 SsizeT, _llcppg_param4 *Object) *Object

// llgo:type C
type CMethod = func(_llcppg_param1 *Object, _llcppg_param2 *TypeObject, _llcppg_param3 **Object, _llcppg_param4 SsizeT, _llcppg_param5 *Object) *Object

// For backwards compatibility. `METH_FASTCALL` was added to the stable API in
// 3.10 alongside `_PyCFunctionFastWithKeywords` and `_PyCFunctionFast`.
// Note that the underscore-prefixed names were documented in public docs;
// people may be using them.
type X_CFunctionFast = CFunctionFast
type X_CFunctionFastWithKeywords = CFunctionFastWithKeywords

// PyCFunctionObject structure
type CFunctionObject struct {
	ObBase       Object
	MMl          *MethodDef
	MSelf        *Object
	MModule      *Object
	MWeakreflist *Object
	Vectorcall   Vectorcallfunc
}

// PyCMethodObject structure
type CMethodObject struct {
	Func    CFunctionObject
	MmClass *TypeObject
}

// This is about the type 'builtin_function_or_method',
// not Python methods in user-defined classes.  See classobject.h
// for the latter.
//
//go:linkname CFunctionType C.PyCFunction_Type
var CFunctionType TypeObject

// llgo:link (*CFunctionObject).Function C.PyCFunction_GetFunction
func (self *CFunctionObject) Function() CFunction {
	return nil
}

// llgo:link (*CFunctionObject).Self C.PyCFunction_GetSelf
func (self *CFunctionObject) Self() *Object {
	return nil
}

// llgo:link (*CFunctionObject).Flags C.PyCFunction_GetFlags
func (self *CFunctionObject) Flags() c.Int {
	return 0
}

// PyCFunction_New is declared as a function for stable ABI (declaration is
// needed for e.g. GCC with -fvisibility=hidden), but redefined as a macro
// that calls PyCFunction_NewEx.
//
//go:linkname NewCFunction C.PyCFunction_New
func NewCFunction(_llcppg_param1 *MethodDef, _llcppg_param2 *Object) *CFunctionObject

// PyCFunction_NewEx is similar: on 3.9+, this calls PyCMethod_New.
//
// llgo:link (*MethodDef).CFunctionNewEx C.PyCFunction_NewEx
func (self *MethodDef) CFunctionNewEx(_llcppg_param2 *Object, _llcppg_param3 *Object) *Object {
	return nil
}

//go:linkname NewCMethod C.PyCMethod_New
func NewCMethod(_llcppg_param1 *MethodDef, _llcppg_param2 *Object, _llcppg_param3 *Object, _llcppg_param4 *TypeObject) *CMethodObject

//go:linkname CMethodType C.PyCMethod_Type
var CMethodType TypeObject
