// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

const METH_VARARGS = 1
const METH_KEYWORDS = 2
const METH_NOARGS = 4
const METH_O = 8
const METH_CLASS = 16
const METH_STATIC = 32
const METH_COEXIST = 64
const METH_FASTCALL = 128
const METH_STACKLESS = 0
const METH_METHOD = 512

type PyMethodDef struct {
	MlName  *c.Char
	MlMeth  PyCFunction
	MlFlags c.Int
	MlDoc   *c.Char
}

// llgo:type C
type PyCFunction = func(_llcppg_param1 *PyObject, _llcppg_param2 *PyObject) *PyObject

// llgo:type C
type PyCFunctionFast = func(_llcppg_param1 *PyObject, _llcppg_param2 **PyObject, _llcppg_param3 PySsizeT) *PyObject

// llgo:type C
type PyCFunctionWithKeywords = func(_llcppg_param1 *PyObject, _llcppg_param2 *PyObject, _llcppg_param3 *PyObject) *PyObject

// llgo:type C
type PyCFunctionFastWithKeywords = func(_llcppg_param1 *PyObject, _llcppg_param2 **PyObject, _llcppg_param3 PySsizeT, _llcppg_param4 *PyObject) *PyObject

// llgo:type C
type PyCMethod = func(_llcppg_param1 *PyObject, _llcppg_param2 *PyTypeObject, _llcppg_param3 **PyObject, _llcppg_param4 PySsizeT, _llcppg_param5 *PyObject) *PyObject
type X_PyCFunctionFast = PyCFunctionFast
type X_PyCFunctionFastWithKeywords = PyCFunctionFastWithKeywords

//go:linkname PyCFunction_Type C.PyCFunction_Type
var PyCFunction_Type PyTypeObject

// llgo:link (*PyObject).PyCFunction_GetFunction C.PyCFunction_GetFunction
func (self *PyObject) PyCFunction_GetFunction() PyCFunction {
	return nil
}

// llgo:link (*PyObject).PyCFunction_GetSelf C.PyCFunction_GetSelf
func (self *PyObject) PyCFunction_GetSelf() *PyObject {
	return self
}

// llgo:link (*PyObject).PyCFunction_GetFlags C.PyCFunction_GetFlags
func (self *PyObject) PyCFunction_GetFlags() c.Int {
	return 0
}

// llgo:link (*PyMethodDef).PyCFunction_New C.PyCFunction_New
func (self *PyMethodDef) PyCFunction_New(_llcppg_param2 *PyObject) *PyObject {
	return nil
}

// llgo:link (*PyMethodDef).PyCFunction_NewEx C.PyCFunction_NewEx
func (self *PyMethodDef) PyCFunction_NewEx(_llcppg_param2 *PyObject, _llcppg_param3 *PyObject) *PyObject {
	return nil
}

// llgo:link (*PyMethodDef).PyCMethod_New C.PyCMethod_New
func (self *PyMethodDef) PyCMethod_New(_llcppg_param2 *PyObject, _llcppg_param3 *PyObject, _llcppg_param4 *PyTypeObject) *PyObject {
	return nil
}
