// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const CLEANUP_SUPPORTED = 131072
const PYTHON_API_VERSION = 1013
const PYTHON_API_STRING = "1013"
const PYTHON_ABI_VERSION = 3
const PYTHON_ABI_STRING = "3"

// A data structure that can be used to run initialization code once in a
// thread-safe manner. The C++11 equivalent is std::call_once.
type X_OnceFlag struct {
	V c.Uint8T
}
type X_ArgParser struct {
	Format         *c.Char
	Keywords       **c.Char
	Fname          *c.Char
	CustomMsg      *c.Char
	Once           X_OnceFlag
	IsKwtupleOwned c.Int
	Pos            c.Int
	Min            c.Int
	Max            c.Int
	Kwtuple        *Object
	Next           *X_ArgParser
}
type Arg struct {
	X_object
}

func (self *Object) AsArg() *Arg {
	return (*Arg)(unsafe.Pointer(self))
}

// llgo:link (*Arg).Parse C.PyArg_Parse
func (self *Arg) Parse(_llcppg_param2 *c.Char, __llgo_va_list ...any) c.Int {
	return 0
}

// llgo:link (*Arg).ParseTuple C.PyArg_ParseTuple
func (self *Arg) ParseTuple(_llcppg_param2 *c.Char, __llgo_va_list ...any) c.Int {
	return 0
}

// llgo:link (*Arg).ParseTupleAndKeywords C.PyArg_ParseTupleAndKeywords
func (self *Arg) ParseTupleAndKeywords(_llcppg_param2 *Object, _llcppg_param3 *c.Char, _llcppg_param4 **c.Char, __llgo_va_list ...any) c.Int {
	return 0
}

// llgo:link (*Arg).VaParse C.PyArg_VaParse
func (self *Arg) VaParse(_llcppg_param2 *c.Char, _llcppg_param3 c.VaList) c.Int {
	return 0
}

// llgo:link (*Arg).VaParseTupleAndKeywords C.PyArg_VaParseTupleAndKeywords
func (self *Arg) VaParseTupleAndKeywords(_llcppg_param2 *Object, _llcppg_param3 *c.Char, _llcppg_param4 **c.Char, _llcppg_param5 c.VaList) c.Int {
	return 0
}

// llgo:link (*Arg).ValidateKeywordArguments C.PyArg_ValidateKeywordArguments
func (self *Arg) ValidateKeywordArguments() c.Int {
	return 0
}

// llgo:link (*Arg).UnpackTuple C.PyArg_UnpackTuple
func (self *Arg) UnpackTuple(_llcppg_param2 *c.Char, _llcppg_param3 SsizeT, _llcppg_param4 SsizeT, __llgo_va_list ...any) c.Int {
	return 0
}

//go:linkname BuildValue C.Py_BuildValue
func BuildValue(_llcppg_param1 *c.Char, __llgo_va_list ...any) *Object

//go:linkname VaBuildValue C.Py_VaBuildValue
func VaBuildValue(_llcppg_param1 *c.Char, _llcppg_param2 c.VaList) *Object

// Add an attribute with name 'name' and value 'obj' to the module 'mod.
// On success, return 0.
// On error, raise an exception and return -1.
//
// llgo:link (*Module).AddObjectRef C.PyModule_AddObjectRef
func (self *Module) AddObjectRef(name *c.Char, value *Object) c.Int {
	return 0
}

// Similar to PyModule_AddObjectRef() but steal a reference to 'value'.
//
// llgo:link (*Module).Add C.PyModule_Add
func (self *Module) Add(name *c.Char, value *Object) c.Int {
	return 0
}

// Similar to PyModule_AddObjectRef() and PyModule_Add() but steal
// a reference to 'value' on success and only on success.
// Errorprone. Should not be used in new code.
//
// llgo:link (*Module).AddObject C.PyModule_AddObject
func (self *Module) AddObject(_llcppg_param2 *c.Char, value *Object) c.Int {
	return 0
}

// llgo:link (*Module).AddIntConstant C.PyModule_AddIntConstant
func (self *Module) AddIntConstant(_llcppg_param2 *c.Char, _llcppg_param3 c.Long) c.Int {
	return 0
}

// llgo:link (*Module).AddStringConstant C.PyModule_AddStringConstant
func (self *Module) AddStringConstant(_llcppg_param2 *c.Char, _llcppg_param3 *c.Char) c.Int {
	return 0
}

// New in 3.9
//
// llgo:link (*Module).AddType C.PyModule_AddType
func (self *Module) AddType(type_ *TypeObject) c.Int {
	return 0
}

// New in 3.5
//
// llgo:link (*Module).SetDocString C.PyModule_SetDocString
func (self *Module) SetDocString(_llcppg_param2 *c.Char) c.Int {
	return 0
}

// llgo:link (*Module).AddFunctions C.PyModule_AddFunctions
func (self *Module) AddFunctions(_llcppg_param2 *MethodDef) c.Int {
	return 0
}

// llgo:link (*Module).ExecDef C.PyModule_ExecDef
func (self *Module) ExecDef(def *ModuleDef) c.Int {
	return 0
}

// llgo:link (*Module).Create2 C.PyModule_Create2
func (self *Module) Create2(apiver c.Int) *Object {
	return nil
}

// New in 3.5
//
// llgo:link (*Module).FromDefAndSpec2 C.PyModule_FromDefAndSpec2
func (self *Module) FromDefAndSpec2(spec *Object, module_api_version c.Int) *Object {
	return nil
}

//go:linkname X_ArgParseTupleAndKeywordsFast C._PyArg_ParseTupleAndKeywordsFast
func X_ArgParseTupleAndKeywordsFast(_llcppg_param1 *Object, _llcppg_param2 *Object, _llcppg_param3 *X_ArgParser, __llgo_va_list ...any) c.Int
