// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

const Py_CLEANUP_SUPPORTED = 131072
const PYTHON_API_VERSION = 1013
const PYTHON_API_STRING = "1013"
const PYTHON_ABI_VERSION = 3
const PYTHON_ABI_STRING = "3"

// llgo:link (*PyObject).PyArg_Parse C.PyArg_Parse
func (self *PyObject) PyArg_Parse(_llcppg_param2 *c.Char, __llgo_va_list ...any) c.Int {
	return 0
}

// llgo:link (*PyObject).PyArg_ParseTuple C.PyArg_ParseTuple
func (self *PyObject) PyArg_ParseTuple(_llcppg_param2 *c.Char, __llgo_va_list ...any) c.Int {
	return 0
}

// llgo:link (*PyObject).PyArg_ParseTupleAndKeywords C.PyArg_ParseTupleAndKeywords
func (self *PyObject) PyArg_ParseTupleAndKeywords(_llcppg_param2 *PyObject, _llcppg_param3 *c.Char, _llcppg_param4 **c.Char, __llgo_va_list ...any) c.Int {
	return 0
}

// llgo:link (*PyObject).PyArg_VaParse C.PyArg_VaParse
func (self *PyObject) PyArg_VaParse(_llcppg_param2 *c.Char, _llcppg_param3 c.VaList) c.Int {
	return 0
}

// llgo:link (*PyObject).PyArg_VaParseTupleAndKeywords C.PyArg_VaParseTupleAndKeywords
func (self *PyObject) PyArg_VaParseTupleAndKeywords(_llcppg_param2 *PyObject, _llcppg_param3 *c.Char, _llcppg_param4 **c.Char, _llcppg_param5 c.VaList) c.Int {
	return 0
}

// llgo:link (*PyObject).PyArg_ValidateKeywordArguments C.PyArg_ValidateKeywordArguments
func (self *PyObject) PyArg_ValidateKeywordArguments() c.Int {
	return 0
}

// llgo:link (*PyObject).PyArg_UnpackTuple C.PyArg_UnpackTuple
func (self *PyObject) PyArg_UnpackTuple(_llcppg_param2 *c.Char, _llcppg_param3 PySsizeT, _llcppg_param4 PySsizeT, __llgo_va_list ...any) c.Int {
	return 0
}

//go:linkname Py_BuildValue C.Py_BuildValue
func Py_BuildValue(_llcppg_param1 *c.Char, __llgo_va_list ...any) *PyObject

//go:linkname Py_VaBuildValue C.Py_VaBuildValue
func Py_VaBuildValue(_llcppg_param1 *c.Char, _llcppg_param2 c.VaList) *PyObject

// llgo:link (*PyObject).PyModule_AddObjectRef C.PyModule_AddObjectRef
func (self *PyObject) PyModule_AddObjectRef(name *c.Char, value *PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyModule_Add C.PyModule_Add
func (self *PyObject) PyModule_Add(name *c.Char, value *PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyModule_AddObject C.PyModule_AddObject
func (self *PyObject) PyModule_AddObject(_llcppg_param2 *c.Char, value *PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyModule_AddIntConstant C.PyModule_AddIntConstant
func (self *PyObject) PyModule_AddIntConstant(_llcppg_param2 *c.Char, _llcppg_param3 c.Long) c.Int {
	return 0
}

// llgo:link (*PyObject).PyModule_AddStringConstant C.PyModule_AddStringConstant
func (self *PyObject) PyModule_AddStringConstant(_llcppg_param2 *c.Char, _llcppg_param3 *c.Char) c.Int {
	return 0
}

// llgo:link (*PyObject).PyModule_AddType C.PyModule_AddType
func (self *PyObject) PyModule_AddType(type_ *PyTypeObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyModule_SetDocString C.PyModule_SetDocString
func (self *PyObject) PyModule_SetDocString(_llcppg_param2 *c.Char) c.Int {
	return 0
}

// llgo:link (*PyObject).PyModule_AddFunctions C.PyModule_AddFunctions
func (self *PyObject) PyModule_AddFunctions(_llcppg_param2 *PyMethodDef) c.Int {
	return 0
}

// llgo:link (*PyObject).PyModule_ExecDef C.PyModule_ExecDef
func (self *PyObject) PyModule_ExecDef(def *PyModuleDef) c.Int {
	return 0
}

// llgo:link (*PyModuleDef).PyModule_Create2 C.PyModule_Create2
func (self *PyModuleDef) PyModule_Create2(apiver c.Int) *PyObject {
	return nil
}

// llgo:link (*PyModuleDef).PyModule_FromDefAndSpec2 C.PyModule_FromDefAndSpec2
func (self *PyModuleDef) PyModule_FromDefAndSpec2(spec *PyObject, module_api_version c.Int) *PyObject {
	return nil
}
