// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const ModCreate = 1
const ModExec = 2
const ModMultipleInterpreters = 3
const ModGil = 4
const X_modLAST_SLOT = 4

type ModuleDef struct {
	MBase     ModuleDefBase
	MName     *c.Char
	MDoc      *c.Char
	MSize     SsizeT
	MMethods  *MethodDef
	MSlots    *ModuleDefSlot
	MTraverse Traverseproc
	MClear    Inquiry
	MFree     Freefunc
}

// New in 3.5
type ModuleDefSlot struct {
	Slot  c.Int
	Value unsafe.Pointer
}

// llgo:type C
type ModuleDefBase struct {
	ObBase Object
	MInit  func() *Object
	MIndex SsizeT
	MCopy  *Object
}

//go:linkname ModuleType C.PyModule_Type
var ModuleType TypeObject

type Module struct {
	X_object
}

func (self *Object) AsModule() *Module {
	return (*Module)(unsafe.Pointer(self))
}

// llgo:link (*Module).NewObject C.PyModule_NewObject
func (self *Module) NewObject() *Object {
	return nil
}

//go:linkname ModuleNew C.PyModule_New
func ModuleNew(name *c.Char) *Object

// llgo:link (*Module).Dict C.PyModule_GetDict
func (self *Module) Dict() *Object {
	return nil
}

// llgo:link (*Module).NameObject C.PyModule_GetNameObject
func (self *Module) NameObject() *Object {
	return nil
}

// llgo:link (*Module).Name C.PyModule_GetName
func (self *Module) Name() *c.Char {
	return nil
}

// llgo:link (*Module).Filename C.PyModule_GetFilename
func (self *Module) Filename() *c.Char {
	return nil
}

// llgo:link (*Module).FilenameObject C.PyModule_GetFilenameObject
func (self *Module) FilenameObject() *Object {
	return nil
}

// llgo:link (*Module).Def C.PyModule_GetDef
func (self *Module) Def() *ModuleDef {
	return nil
}

// llgo:link (*Module).State C.PyModule_GetState
func (self *Module) State() unsafe.Pointer {
	return nil
}

// New in 3.5
//
// llgo:link (*ModuleDef).Init C.PyModuleDef_Init
func (self *ModuleDef) Init() *Object {
	return nil
}

//go:linkname ModuleDefType C.PyModuleDef_Type
var ModuleDefType TypeObject
