// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

const MONITORING_EVENT_PY_START = 0
const MONITORING_EVENT_PY_RESUME = 1
const MONITORING_EVENT_PY_RETURN = 2
const MONITORING_EVENT_PY_YIELD = 3
const MONITORING_EVENT_CALL = 4
const MONITORING_EVENT_LINE = 5
const MONITORING_EVENT_INSTRUCTION = 6
const MONITORING_EVENT_JUMP = 7
const MONITORING_EVENT_BRANCH_LEFT = 8
const MONITORING_EVENT_BRANCH_RIGHT = 9
const MONITORING_EVENT_STOP_ITERATION = 10
const MONITORING_EVENT_RAISE = 11
const MONITORING_EVENT_EXCEPTION_HANDLED = 12
const MONITORING_EVENT_PY_UNWIND = 13
const MONITORING_EVENT_PY_THROW = 14
const MONITORING_EVENT_RERAISE = 15
const MONITORING_EVENT_C_RETURN = 16
const MONITORING_EVENT_C_RAISE = 17
const MONITORING_EVENT_BRANCH = 18

type X_MonitoringState struct {
	Active c.Uint8T
	Opaque c.Uint8T
}
type MonitoringState = X_MonitoringState

//go:linkname MonitoringEnterScope C.PyMonitoring_EnterScope
func MonitoringEnterScope(state_array *MonitoringState, version *c.Uint64T, event_types *c.Uint8T, length SsizeT) c.Int

//go:linkname MonitoringExitScope C.PyMonitoring_ExitScope
func MonitoringExitScope() c.Int

//go:linkname X_MonitoringFirePyStartEvent C._PyMonitoring_FirePyStartEvent
func X_MonitoringFirePyStartEvent(state *MonitoringState, codelike *Object, offset c.Int32T) c.Int

//go:linkname X_MonitoringFirePyResumeEvent C._PyMonitoring_FirePyResumeEvent
func X_MonitoringFirePyResumeEvent(state *MonitoringState, codelike *Object, offset c.Int32T) c.Int

//go:linkname X_MonitoringFirePyReturnEvent C._PyMonitoring_FirePyReturnEvent
func X_MonitoringFirePyReturnEvent(state *MonitoringState, codelike *Object, offset c.Int32T, retval *Object) c.Int

//go:linkname X_MonitoringFirePyYieldEvent C._PyMonitoring_FirePyYieldEvent
func X_MonitoringFirePyYieldEvent(state *MonitoringState, codelike *Object, offset c.Int32T, retval *Object) c.Int

//go:linkname X_MonitoringFireCallEvent C._PyMonitoring_FireCallEvent
func X_MonitoringFireCallEvent(state *MonitoringState, codelike *Object, offset c.Int32T, callable *Object, arg0 *Object) c.Int

//go:linkname X_MonitoringFireLineEvent C._PyMonitoring_FireLineEvent
func X_MonitoringFireLineEvent(state *MonitoringState, codelike *Object, offset c.Int32T, lineno c.Int) c.Int

//go:linkname X_MonitoringFireJumpEvent C._PyMonitoring_FireJumpEvent
func X_MonitoringFireJumpEvent(state *MonitoringState, codelike *Object, offset c.Int32T, target_offset *Object) c.Int

//go:linkname X_MonitoringFireBranchEvent C._PyMonitoring_FireBranchEvent
func X_MonitoringFireBranchEvent(state *MonitoringState, codelike *Object, offset c.Int32T, target_offset *Object) c.Int

//go:linkname X_MonitoringFireBranchRightEvent C._PyMonitoring_FireBranchRightEvent
func X_MonitoringFireBranchRightEvent(state *MonitoringState, codelike *Object, offset c.Int32T, target_offset *Object) c.Int

//go:linkname X_MonitoringFireBranchLeftEvent C._PyMonitoring_FireBranchLeftEvent
func X_MonitoringFireBranchLeftEvent(state *MonitoringState, codelike *Object, offset c.Int32T, target_offset *Object) c.Int

//go:linkname X_MonitoringFireCReturnEvent C._PyMonitoring_FireCReturnEvent
func X_MonitoringFireCReturnEvent(state *MonitoringState, codelike *Object, offset c.Int32T, retval *Object) c.Int

//go:linkname X_MonitoringFirePyThrowEvent C._PyMonitoring_FirePyThrowEvent
func X_MonitoringFirePyThrowEvent(state *MonitoringState, codelike *Object, offset c.Int32T) c.Int

//go:linkname X_MonitoringFireRaiseEvent C._PyMonitoring_FireRaiseEvent
func X_MonitoringFireRaiseEvent(state *MonitoringState, codelike *Object, offset c.Int32T) c.Int

//go:linkname X_MonitoringFireReraiseEvent C._PyMonitoring_FireReraiseEvent
func X_MonitoringFireReraiseEvent(state *MonitoringState, codelike *Object, offset c.Int32T) c.Int

//go:linkname X_MonitoringFireExceptionHandledEvent C._PyMonitoring_FireExceptionHandledEvent
func X_MonitoringFireExceptionHandledEvent(state *MonitoringState, codelike *Object, offset c.Int32T) c.Int

//go:linkname X_MonitoringFireCRaiseEvent C._PyMonitoring_FireCRaiseEvent
func X_MonitoringFireCRaiseEvent(state *MonitoringState, codelike *Object, offset c.Int32T) c.Int

//go:linkname X_MonitoringFirePyUnwindEvent C._PyMonitoring_FirePyUnwindEvent
func X_MonitoringFirePyUnwindEvent(state *MonitoringState, codelike *Object, offset c.Int32T) c.Int

//go:linkname X_MonitoringFireStopIterationEvent C._PyMonitoring_FireStopIterationEvent
func X_MonitoringFireStopIterationEvent(state *MonitoringState, codelike *Object, offset c.Int32T, value *Object) c.Int
