// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const PRINT_RAW = 1
const X_TPFLAGS_STATIC_BUILTIN = 2
const TPFLAGS_INLINE_VALUES = 4
const TPFLAGS_MANAGED_WEAKREF = 8
const TPFLAGS_MANAGED_DICT = 16
const TPFLAGS_PREHEADER = 24
const TPFLAGS_SEQUENCE = 32
const TPFLAGS_MAPPING = 64
const TPFLAGS_HAVE_STACKLESS_EXTENSION = 0
const TPFLAGS_DEFAULT = 0
const CONSTANT_NONE = 0
const CONSTANT_FALSE = 1
const CONSTANT_TRUE = 2
const CONSTANT_ELLIPSIS = 3
const CONSTANT_NOT_IMPLEMENTED = 4
const CONSTANT_ZERO = 5
const CONSTANT_ONE = 6
const CONSTANT_EMPTY_STR = 7
const CONSTANT_EMPTY_BYTES = 8
const CONSTANT_EMPTY_TUPLE = 9
const LT = 0
const LE = 1
const EQ = 2
const NE = 3
const GT = 4
const GE = 5
const X_ATTR_CACHE_UNUSED = 30000

// Result of calling PyIter_Send
type SendResult c.Int

const (
	PYGEN_RETURN SendResult = 0
	PYGEN_ERROR  SendResult = -1
	PYGEN_NEXT   SendResult = 1
)

type RefTracerEvent c.Uint

const (
	RefTracer_CREATE  RefTracerEvent = 0
	RefTracer_DESTROY RefTracerEvent = 1
)

type X_object struct {
	_llcppg_anon_0
	ObType *TypeObject
}

// If this structure is modified, Doc/includes/typestruct.h should be updated
// as well.
type X_typeobject struct {
	ObBase             VarObject
	TpName             *c.Char
	TpBasicsize        SsizeT
	TpItemsize         SsizeT
	TpDealloc          Destructor
	TpVectorcallOffset SsizeT
	TpGetattr          Getattrfunc
	TpSetattr          Setattrfunc
	TpAsAsync          *AsyncMethods
	TpRepr             Reprfunc
	TpAsNumber         *NumberMethods
	TpAsSequence       *SequenceMethods
	TpAsMapping        *MappingMethods
	TpHash             Hashfunc
	TpCall             Ternaryfunc
	TpStr              Reprfunc
	TpGetattro         Getattrofunc
	TpSetattro         Setattrofunc
	TpAsBuffer         *BufferProcs
	TpFlags            c.Ulong
	TpDoc              *c.Char
	TpTraverse         Traverseproc
	TpClear            Inquiry
	TpRichcompare      Richcmpfunc
	TpWeaklistoffset   SsizeT
	TpIter             Getiterfunc
	TpIternext         Iternextfunc
	TpMethods          *MethodDef
	TpMembers          *MemberDef
	TpGetset           *GetSetDef
	TpBase             *TypeObject
	TpDict             *Object
	TpDescrGet         Descrgetfunc
	TpDescrSet         Descrsetfunc
	TpDictoffset       SsizeT
	TpInit             Initproc
	TpAlloc            Allocfunc
	TpNew              Newfunc
	TpFree             Freefunc
	TpIsGc             Inquiry
	TpBases            *Object
	TpMro              *Object
	TpCache            *Object
	TpSubclasses       unsafe.Pointer
	TpWeaklist         *Object
	TpDel              Destructor
	TpVersionTag       c.Uint
	TpFinalize         Destructor
	TpVectorcall       Vectorcallfunc
	TpWatched          uint8
	TpVersionsUsed     c.Uint16T
}
type _llcppg_anon_0 struct {
	_xgo_union [1]uint64
}
type VarObject struct {
	ObBase Object
	ObSize SsizeT
}

// Type objects contain a string containing the type name (to help somewhat
// in debugging), the allocation parameters (see PyObject_New() and
// PyObject_NewVar()),
// and methods for accessing objects of the type.  Methods are optional, a
// nil pointer meaning that particular kind of access is not available for
// this type.  The Py_DECREF() macro uses the tp_dealloc method without
// checking for a nil pointer; it should always be implemented except if
// the implementation can guarantee that the reference count will never
// reach zero (e.g., for statically allocated type objects).
//
// NB: the methods for certain type groups are now contained in separate
// method blocks.
//
// llgo:type C
type Unaryfunc = func(_llcppg_param1 *Object) *Object

// llgo:type C
type Binaryfunc = func(_llcppg_param1 *Object, _llcppg_param2 *Object) *Object

// llgo:type C
type Ternaryfunc = func(_llcppg_param1 *Object, _llcppg_param2 *Object, _llcppg_param3 *Object) *Object

// llgo:type C
type Inquiry = func(_llcppg_param1 *Object) c.Int

// llgo:type C
type Lenfunc = func(_llcppg_param1 *Object) SsizeT

// llgo:type C
type Ssizeargfunc = func(_llcppg_param1 *Object, _llcppg_param2 SsizeT) *Object

// llgo:type C
type Ssizessizeargfunc = func(_llcppg_param1 *Object, _llcppg_param2 SsizeT, _llcppg_param3 SsizeT) *Object

// llgo:type C
type Ssizeobjargproc = func(_llcppg_param1 *Object, _llcppg_param2 SsizeT, _llcppg_param3 *Object) c.Int

// llgo:type C
type Ssizessizeobjargproc = func(_llcppg_param1 *Object, _llcppg_param2 SsizeT, _llcppg_param3 SsizeT, _llcppg_param4 *Object) c.Int

// llgo:type C
type Objobjargproc = func(_llcppg_param1 *Object, _llcppg_param2 *Object, _llcppg_param3 *Object) c.Int

// llgo:type C
type Objobjproc = func(_llcppg_param1 *Object, _llcppg_param2 *Object) c.Int

// llgo:type C
type Visitproc = func(_llcppg_param1 *Object, _llcppg_param2 unsafe.Pointer) c.Int

// llgo:type C
type Traverseproc = func(_llcppg_param1 *Object, _llcppg_param2 Visitproc, _llcppg_param3 unsafe.Pointer) c.Int

// llgo:type C
type Freefunc = func(_llcppg_param1 unsafe.Pointer)

// llgo:type C
type Destructor = func(_llcppg_param1 *Object)

// llgo:type C
type Getattrfunc = func(_llcppg_param1 *Object, _llcppg_param2 *c.Char) *Object

// llgo:type C
type Getattrofunc = func(_llcppg_param1 *Object, _llcppg_param2 *Object) *Object

// llgo:type C
type Setattrfunc = func(_llcppg_param1 *Object, _llcppg_param2 *c.Char, _llcppg_param3 *Object) c.Int

// llgo:type C
type Setattrofunc = func(_llcppg_param1 *Object, _llcppg_param2 *Object, _llcppg_param3 *Object) c.Int

// llgo:type C
type Reprfunc = func(_llcppg_param1 *Object) *Object

// llgo:type C
type Hashfunc = func(_llcppg_param1 *Object) HashT

// llgo:type C
type Richcmpfunc = func(_llcppg_param1 *Object, _llcppg_param2 *Object, _llcppg_param3 c.Int) *Object

// llgo:type C
type Getiterfunc = func(_llcppg_param1 *Object) *Object

// llgo:type C
type Iternextfunc = func(_llcppg_param1 *Object) *Object

// llgo:type C
type Descrgetfunc = func(_llcppg_param1 *Object, _llcppg_param2 *Object, _llcppg_param3 *Object) *Object

// llgo:type C
type Descrsetfunc = func(_llcppg_param1 *Object, _llcppg_param2 *Object, _llcppg_param3 *Object) c.Int

// llgo:type C
type Initproc = func(_llcppg_param1 *Object, _llcppg_param2 *Object, _llcppg_param3 *Object) c.Int

// llgo:type C
type Newfunc = func(_llcppg_param1 *TypeObject, _llcppg_param2 *Object, _llcppg_param3 *Object) *Object

// llgo:type C
type Allocfunc = func(_llcppg_param1 *TypeObject, _llcppg_param2 SsizeT) *Object

// llgo:type C
type Vectorcallfunc = func(_llcppg_param1 *Object, _llcppg_param2 **Object, _llcppg_param3 c.SizeT, _llcppg_param4 *Object) *Object
type TypeSlot struct {
	Slot  c.Int
	Pfunc unsafe.Pointer
}
type TypeSpec struct {
	Name      *c.Char
	Basicsize c.Int
	Itemsize  c.Int
	Flags     c.Uint
	Slots     *TypeSlot
}

// String Literals
// This structure helps managing static strings. The basic usage goes like this:
// Instead of doing
//
// r = PyObject_CallMethod(o, "foo", "args", ...);
//
// do
//
// _Py_IDENTIFIER(foo);
// ...
// r = _PyObject_CallMethodId(o, &PyId_foo, "args", ...);
//
// PyId_foo is a static variable, either on block level or file level. On first
// usage, the string "foo" is interned, and the structures are linked. On interpreter
// shutdown, all strings are released.
//
// Alternatively, _Py_static_string allows choosing the variable name.
// _PyUnicode_FromId returns a borrowed reference to the interned string.
// _PyObject_{Get,Set,Has}AttrId are __getattr__ versions using _Py_Identifier*.
type X_Identifier struct {
	String *c.Char
	Index  SsizeT
	Mutex  _llcppg_anon_1
}

// Hidden PyMutex struct for non free-threaded build.
type _llcppg_anon_1 struct {
	V c.Uint8T
}
type NumberMethods struct {
	NbAdd                   Binaryfunc
	NbSubtract              Binaryfunc
	NbMultiply              Binaryfunc
	NbRemainder             Binaryfunc
	NbDivmod                Binaryfunc
	NbPower                 Ternaryfunc
	NbNegative              Unaryfunc
	NbPositive              Unaryfunc
	NbAbsolute              Unaryfunc
	NbBool                  Inquiry
	NbInvert                Unaryfunc
	NbLshift                Binaryfunc
	NbRshift                Binaryfunc
	NbAnd                   Binaryfunc
	NbXor                   Binaryfunc
	NbOr                    Binaryfunc
	NbInt                   Unaryfunc
	NbReserved              unsafe.Pointer
	NbFloat                 Unaryfunc
	NbInplaceAdd            Binaryfunc
	NbInplaceSubtract       Binaryfunc
	NbInplaceMultiply       Binaryfunc
	NbInplaceRemainder      Binaryfunc
	NbInplacePower          Ternaryfunc
	NbInplaceLshift         Binaryfunc
	NbInplaceRshift         Binaryfunc
	NbInplaceAnd            Binaryfunc
	NbInplaceXor            Binaryfunc
	NbInplaceOr             Binaryfunc
	NbFloorDivide           Binaryfunc
	NbTrueDivide            Binaryfunc
	NbInplaceFloorDivide    Binaryfunc
	NbInplaceTrueDivide     Binaryfunc
	NbIndex                 Unaryfunc
	NbMatrixMultiply        Binaryfunc
	NbInplaceMatrixMultiply Binaryfunc
}
type SequenceMethods struct {
	SqLength        Lenfunc
	SqConcat        Binaryfunc
	SqRepeat        Ssizeargfunc
	SqItem          Ssizeargfunc
	WasSqSlice      unsafe.Pointer
	SqAssItem       Ssizeobjargproc
	WasSqAssSlice   unsafe.Pointer
	SqContains      Objobjproc
	SqInplaceConcat Binaryfunc
	SqInplaceRepeat Ssizeargfunc
}
type MappingMethods struct {
	MpLength       Lenfunc
	MpSubscript    Binaryfunc
	MpAssSubscript Objobjargproc
}

// llgo:type C
type Sendfunc = func(_llcppg_param1 *Object, _llcppg_param2 *Object, _llcppg_param3 **Object) SendResult
type AsyncMethods struct {
	AmAwait Unaryfunc
	AmAiter Unaryfunc
	AmAnext Unaryfunc
	AmSend  Sendfunc
}
type BufferProcs struct {
	BfGetbuffer     Getbufferproc
	BfReleasebuffer Releasebufferproc
}

// Allow printfunc in the tp_vectorcall_offset slot for
// backwards-compatibility
type Printfunc = SsizeT

// This struct is used by the specializer
// It should be treated as an opaque blob
// by code other than the specializer and interpreter.
type X_specializationCache struct {
	Getitem        *Object
	GetitemVersion c.Uint32T
	Init           *Object
}

// The *real* layout of a type object when allocated on the heap
type X_heaptypeobject struct {
	HtType       TypeObject
	AsAsync      AsyncMethods
	AsNumber     NumberMethods
	AsMapping    MappingMethods
	AsSequence   SequenceMethods
	AsBuffer     BufferProcs
	HtName       *Object
	HtSlots      *Object
	HtQualname   *Object
	HtCachedKeys *X_dictkeysobject
	HtModule     *Object
	X_htTpname   *c.Char
	HtToken      unsafe.Pointer
	X_specCache  X_specializationCache
}
type X_dictkeysobject struct {
}

// The *real* layout of a type object when allocated on the heap
type HeapTypeObject = X_heaptypeobject

// llgo:type C
type TypeWatchCallback = func(_llcppg_param1 *TypeObject) c.Int

// llgo:type C
type RefTracer = func(_llcppg_param1 *Object, _llcppg_param2 RefTracerEvent, _llcppg_param3 unsafe.Pointer) c.Int

func (p *_llcppg_anon_0) XGof_ref_ob_refcnt_full() *c.Int64T {
	return (*c.Int64T)(unsafe.Pointer(p))
}

// Test if the 'x' object is the 'y' object, the same as "x is y" in Python.
//
//go:linkname Is C.Py_Is
func Is(x *Object, y *Object) c.Int

// Py_TYPE() implementation for the stable ABI
//
//go:linkname TYPE C.Py_TYPE
func TYPE(ob *Object) *TypeObject

//go:linkname LongType C.PyLong_Type
var LongType TypeObject

//go:linkname BoolType C.PyBool_Type
var BoolType TypeObject

type Type struct {
	TypeSpec
}

func (self *TypeSpec) AsType() *Type {
	return (*Type)(unsafe.Pointer(self))
}

// llgo:link (*Type).FromSpec C.PyType_FromSpec
func (self *Type) FromSpec() *Object {
	return nil
}

// llgo:link (*Type).FromSpecWithBases C.PyType_FromSpecWithBases
func (self *Type) FromSpecWithBases(_llcppg_param2 *Object) *Object {
	return nil
}

// llgo:link (*Type).Slot C.PyType_GetSlot
func (self *Type) Slot(_llcppg_param2 c.Int) unsafe.Pointer {
	return nil
}

// llgo:link (*Type).FromModuleAndSpec C.PyType_FromModuleAndSpec
func (self *Type) FromModuleAndSpec(_llcppg_param2 *TypeSpec, _llcppg_param3 *Object) *Object {
	return nil
}

// llgo:link (*Type).Module C.PyType_GetModule
func (self *Type) Module() *Object {
	return nil
}

// llgo:link (*Type).ModuleState C.PyType_GetModuleState
func (self *Type) ModuleState() unsafe.Pointer {
	return nil
}

// llgo:link (*Type).Name C.PyType_GetName
func (self *Type) Name() *Object {
	return nil
}

// llgo:link (*Type).QualName C.PyType_GetQualName
func (self *Type) QualName() *Object {
	return nil
}

// llgo:link (*Type).FullyQualifiedName C.PyType_GetFullyQualifiedName
func (self *Type) FullyQualifiedName() *Object {
	return nil
}

// llgo:link (*Type).ModuleName C.PyType_GetModuleName
func (self *Type) ModuleName() *Object {
	return nil
}

// llgo:link (*Type).FromMetaclass C.PyType_FromMetaclass
func (self *Type) FromMetaclass(_llcppg_param2 *Object, _llcppg_param3 *TypeSpec, _llcppg_param4 *Object) *Object {
	return nil
}

// llgo:link (*Object).TypeData C.PyObject_GetTypeData
func (self *Object) TypeData(cls *TypeObject) unsafe.Pointer {
	return nil
}

// llgo:link (*Type).DataSize C.PyType_GetTypeDataSize
func (self *Type) DataSize() SsizeT {
	return 0
}

// llgo:link (*Type).BaseByToken C.PyType_GetBaseByToken
func (self *Type) BaseByToken(_llcppg_param2 unsafe.Pointer, _llcppg_param3 **TypeObject) c.Int {
	return 0
}

// Generic type check
//
// llgo:link (*Type).IsSubtype C.PyType_IsSubtype
func (self *Type) IsSubtype(_llcppg_param2 *TypeObject) c.Int {
	return 0
}

// built-in 'type'
//
//go:linkname TypeType C.PyType_Type
var TypeType TypeObject

// built-in 'object'
//
//go:linkname BaseObjectType C.PyBaseObject_Type
var BaseObjectType TypeObject

// built-in 'super'
//
//go:linkname SuperType C.PySuper_Type
var SuperType TypeObject

// llgo:link (*Type).Flags C.PyType_GetFlags
func (self *Type) Flags() c.Ulong {
	return 0
}

// llgo:link (*Type).Ready C.PyType_Ready
func (self *Type) Ready() c.Int {
	return 0
}

// llgo:link (*Type).GenericAlloc C.PyType_GenericAlloc
func (self *Type) GenericAlloc(_llcppg_param2 SsizeT) *Object {
	return nil
}

// llgo:link (*Type).GenericNew C.PyType_GenericNew
func (self *Type) GenericNew(_llcppg_param2 *Object, _llcppg_param3 *Object) *Object {
	return nil
}

//go:linkname TypeClearCache C.PyType_ClearCache
func TypeClearCache() c.Uint

// llgo:link (*Type).Modified C.PyType_Modified
func (self *Type) Modified() {
}

// Generic operations on objects
//
// llgo:link (*Object).Repr C.PyObject_Repr
func (self *Object) Repr() *Object {
	return self
}

// llgo:link (*Object).Str C.PyObject_Str
func (self *Object) Str() *Object {
	return self
}

// llgo:link (*Object).ASCII C.PyObject_ASCII
func (self *Object) ASCII() *Object {
	return self
}

// llgo:link (*Object).Bytes C.PyObject_Bytes
func (self *Object) Bytes() *Object {
	return self
}

// llgo:link (*Object).RichCompare C.PyObject_RichCompare
func (self *Object) RichCompare(_llcppg_param2 *Object, _llcppg_param3 c.Int) *Object {
	return self
}

// llgo:link (*Object).RichCompareBool C.PyObject_RichCompareBool
func (self *Object) RichCompareBool(_llcppg_param2 *Object, _llcppg_param3 c.Int) c.Int {
	return 0
}

// llgo:link (*Object).AttrString C.PyObject_GetAttrString
func (self *Object) AttrString(_llcppg_param2 *c.Char) *Object {
	return self
}

// llgo:link (*Object).SetAttrString C.PyObject_SetAttrString
func (self *Object) SetAttrString(_llcppg_param2 *c.Char, _llcppg_param3 *Object) c.Int {
	return 0
}

// llgo:link (*Object).DelAttrString C.PyObject_DelAttrString
func (self *Object) DelAttrString(name *c.Char) c.Int {
	return 0
}

// llgo:link (*Object).HasAttrString C.PyObject_HasAttrString
func (self *Object) HasAttrString(_llcppg_param2 *c.Char) c.Int {
	return 0
}

// llgo:link (*Object).Attr C.PyObject_GetAttr
func (self *Object) Attr(_llcppg_param2 *Object) *Object {
	return self
}

// llgo:link (*Object).OptionalAttr C.PyObject_GetOptionalAttr
func (self *Object) OptionalAttr(_llcppg_param2 *Object, _llcppg_param3 **Object) c.Int {
	return 0
}

// llgo:link (*Object).OptionalAttrString C.PyObject_GetOptionalAttrString
func (self *Object) OptionalAttrString(_llcppg_param2 *c.Char, _llcppg_param3 **Object) c.Int {
	return 0
}

// llgo:link (*Object).SetAttr C.PyObject_SetAttr
func (self *Object) SetAttr(_llcppg_param2 *Object, _llcppg_param3 *Object) c.Int {
	return 0
}

// llgo:link (*Object).DelAttr C.PyObject_DelAttr
func (self *Object) DelAttr(name *Object) c.Int {
	return 0
}

// llgo:link (*Object).HasAttr C.PyObject_HasAttr
func (self *Object) HasAttr(_llcppg_param2 *Object) c.Int {
	return 0
}

// llgo:link (*Object).HasAttrWithError C.PyObject_HasAttrWithError
func (self *Object) HasAttrWithError(_llcppg_param2 *Object) c.Int {
	return 0
}

// llgo:link (*Object).HasAttrStringWithError C.PyObject_HasAttrStringWithError
func (self *Object) HasAttrStringWithError(_llcppg_param2 *c.Char) c.Int {
	return 0
}

// llgo:link (*Object).SelfIter C.PyObject_SelfIter
func (self *Object) SelfIter() *Object {
	return self
}

// llgo:link (*Object).GenericGetAttr C.PyObject_GenericGetAttr
func (self *Object) GenericGetAttr(_llcppg_param2 *Object) *Object {
	return self
}

// llgo:link (*Object).GenericSetAttr C.PyObject_GenericSetAttr
func (self *Object) GenericSetAttr(_llcppg_param2 *Object, _llcppg_param3 *Object) c.Int {
	return 0
}

// llgo:link (*Object).GenericSetDict C.PyObject_GenericSetDict
func (self *Object) GenericSetDict(_llcppg_param2 *Object, _llcppg_param3 unsafe.Pointer) c.Int {
	return 0
}

// llgo:link (*Object).Hash C.PyObject_Hash
func (self *Object) Hash() HashT {
	return 0
}

// llgo:link (*Object).HashNotImplemented C.PyObject_HashNotImplemented
func (self *Object) HashNotImplemented() HashT {
	return 0
}

// llgo:link (*Object).IsTrue C.PyObject_IsTrue
func (self *Object) IsTrue() c.Int {
	return 0
}

// llgo:link (*Object).Not C.PyObject_Not
func (self *Object) Not() c.Int {
	return 0
}

type Callable struct {
	X_object
}

func (self *Object) AsCallable() *Callable {
	return (*Callable)(unsafe.Pointer(self))
}

// llgo:link (*Callable).Check C.PyCallable_Check
func (self *Callable) Check() c.Int {
	return 0
}

// llgo:link (*Object).ClearWeakRefs C.PyObject_ClearWeakRefs
func (self *Object) ClearWeakRefs() {
}

// PyObject_Dir(obj) acts like Python builtins.dir(obj), returning a
// list of strings.  PyObject_Dir(NULL) is like builtins.dir(),
// returning the names of the current locals.  In this case, if there are
// no current locals, NULL is returned, and PyErr_Occurred() is false.
//
// llgo:link (*Object).Dir C.PyObject_Dir
func (self *Object) Dir() *Object {
	return self
}

// Helpers for printing recursive container types
//
//go:linkname ReprEnter C.Py_ReprEnter
func ReprEnter(_llcppg_param1 *Object) c.Int

//go:linkname ReprLeave C.Py_ReprLeave
func ReprLeave(_llcppg_param1 *Object)

//go:linkname GetConstant C.Py_GetConstant
func GetConstant(constant_id c.Uint) *Object

//go:linkname GetConstantBorrowed C.Py_GetConstantBorrowed
func GetConstantBorrowed(constant_id c.Uint) *Object

// Don't use this directly
//
//go:linkname X_NoneStruct C._Py_NoneStruct
var X_NoneStruct Object

// Test if an object is the None singleton, the same as "x is None" in Python.
//
//go:linkname IsNone C.Py_IsNone
func IsNone(x *Object) c.Int

// Don't use this directly
//
//go:linkname X_NotImplementedStruct C._Py_NotImplementedStruct
var X_NotImplementedStruct Object

//go:linkname X_NewReference C._Py_NewReference
func X_NewReference(op *Object)

//go:linkname X_NewReferenceNoTotal C._Py_NewReferenceNoTotal
func X_NewReferenceNoTotal(op *Object)

//go:linkname X_ResurrectReference C._Py_ResurrectReference
func X_ResurrectReference(op *Object)

//go:linkname X_ForgetReference C._Py_ForgetReference
func X_ForgetReference(op *Object)

//go:linkname X_TypeName C._PyType_Name
func X_TypeName(_llcppg_param1 *TypeObject) *c.Char

//go:linkname X_TypeLookup C._PyType_Lookup
func X_TypeLookup(_llcppg_param1 *TypeObject, _llcppg_param2 *Object) *Object

//go:linkname X_TypeLookupRef C._PyType_LookupRef
func X_TypeLookupRef(_llcppg_param1 *TypeObject, _llcppg_param2 *Object) *Object

// llgo:link (*Type).Dict C.PyType_GetDict
func (self *Type) Dict() *Object {
	return nil
}

// llgo:link (*Object).Print C.PyObject_Print
func (self *Object) Print(_llcppg_param2 *c.FILE, _llcppg_param3 c.Int) c.Int {
	return 0
}

//go:linkname X_BreakPoint C._Py_BreakPoint
func X_BreakPoint()

//go:linkname X_ObjectDump C._PyObject_Dump
func X_ObjectDump(_llcppg_param1 *Object)

//go:linkname X_ObjectGetAttrId C._PyObject_GetAttrId
func X_ObjectGetAttrId(_llcppg_param1 *Object, _llcppg_param2 *X_Identifier) *Object

//go:linkname X_ObjectGetDictPtr C._PyObject_GetDictPtr
func X_ObjectGetDictPtr(_llcppg_param1 *Object) **Object

// llgo:link (*Object).CallFinalizer C.PyObject_CallFinalizer
func (self *Object) CallFinalizer() {
}

// llgo:link (*Object).CallFinalizerFromDealloc C.PyObject_CallFinalizerFromDealloc
func (self *Object) CallFinalizerFromDealloc() c.Int {
	return 0
}

type Unstable struct {
	X_object
}

func (self *Object) AsUnstable() *Unstable {
	return (*Unstable)(unsafe.Pointer(self))
}

// llgo:link (*Unstable).ObjectClearWeakRefsNoCallbacks C.PyUnstable_Object_ClearWeakRefsNoCallbacks
func (self *Unstable) ObjectClearWeakRefsNoCallbacks() {
}

// Same as PyObject_Generic{Get,Set}Attr, but passing the attributes
// dict as the last parameter.
//
//go:linkname X_ObjectGenericGetAttrWithDict C._PyObject_GenericGetAttrWithDict
func X_ObjectGenericGetAttrWithDict(_llcppg_param1 *Object, _llcppg_param2 *Object, _llcppg_param3 *Object, _llcppg_param4 c.Int) *Object

//go:linkname X_ObjectGenericSetAttrWithDict C._PyObject_GenericSetAttrWithDict
func X_ObjectGenericSetAttrWithDict(_llcppg_param1 *Object, _llcppg_param2 *Object, _llcppg_param3 *Object, _llcppg_param4 *Object) c.Int

//go:linkname X_ObjectFunctionStr C._PyObject_FunctionStr
func X_ObjectFunctionStr(_llcppg_param1 *Object) *Object

// Declare and define _PyObject_AssertFailed() even when NDEBUG is defined,
// to avoid causing compiler/linker errors when building extensions without
// NDEBUG against a Python built with NDEBUG defined.
//
// msg, expr and function can be NULL.
//
//go:linkname X_ObjectAssertFailed C._PyObject_AssertFailed
func X_ObjectAssertFailed(obj *Object, expr *c.Char, msg *c.Char, file *c.Char, line c.Int, function *c.Char)

//go:linkname X_TrashThreadDepositObject C._PyTrash_thread_deposit_object
func X_TrashThreadDepositObject(tstate *ThreadState, op *Object)

//go:linkname X_TrashThreadDestroyChain C._PyTrash_thread_destroy_chain
func X_TrashThreadDestroyChain(tstate *ThreadState)

//go:linkname X_ReachedRecursionLimitWithMargin C._Py_ReachedRecursionLimitWithMargin
func X_ReachedRecursionLimitWithMargin(tstate *ThreadState, margin_count c.Int) c.Int

// llgo:link (*Object).ItemData C.PyObject_GetItemData
func (self *Object) ItemData() unsafe.Pointer {
	return nil
}

// llgo:link (*Object).VisitManagedDict C.PyObject_VisitManagedDict
func (self *Object) VisitManagedDict(visit Visitproc, arg unsafe.Pointer) c.Int {
	return 0
}

//go:linkname X_ObjectSetManagedDict C._PyObject_SetManagedDict
func X_ObjectSetManagedDict(obj *Object, new_dict *Object) c.Int

// llgo:link (*Object).ClearManagedDict C.PyObject_ClearManagedDict
func (self *Object) ClearManagedDict() {
}

//go:linkname TypeAddWatcher C.PyType_AddWatcher
func TypeAddWatcher(callback TypeWatchCallback) c.Int

//go:linkname TypeClearWatcher C.PyType_ClearWatcher
func TypeClearWatcher(watcher_id c.Int) c.Int

//go:linkname TypeWatch C.PyType_Watch
func TypeWatch(watcher_id c.Int, type_ *Object) c.Int

//go:linkname TypeUnwatch C.PyType_Unwatch
func TypeUnwatch(watcher_id c.Int, type_ *Object) c.Int

// Attempt to assign a version tag to the given type.
//
// Returns 1 if the type already had a valid version tag or a new one was
// assigned, or 0 if a new tag could not be assigned.
//
// llgo:link (*Unstable).TypeAssignVersionTag C.PyUnstable_Type_AssignVersionTag
func (self *Unstable) TypeAssignVersionTag() c.Int {
	return 0
}

//go:linkname RefTracerSetTracer C.PyRefTracer_SetTracer
func RefTracerSetTracer(tracer RefTracer, data unsafe.Pointer) c.Int

//go:linkname RefTracerGetTracer C.PyRefTracer_GetTracer
func RefTracerGetTracer(_llcppg_param1 *unsafe.Pointer) RefTracer

// Enable PEP-703 deferred reference counting on the object.
//
// Returns 1 if deferred reference counting was successfully enabled, and
// 0 if the runtime ignored it. This function cannot fail.
//
// llgo:link (*Unstable).ObjectEnableDeferredRefcount C.PyUnstable_Object_EnableDeferredRefcount
func (self *Unstable) ObjectEnableDeferredRefcount() c.Int {
	return 0
}

// Determine if the object exists as a unique temporary variable on the
// topmost frame of the interpreter.
//
// llgo:link (*Unstable).ObjectIsUniqueReferencedTemporary C.PyUnstable_Object_IsUniqueReferencedTemporary
func (self *Unstable) ObjectIsUniqueReferencedTemporary() c.Int {
	return 0
}

// Check whether the object is immortal. This cannot fail.
//
// llgo:link (*Unstable).IsImmortal C.PyUnstable_IsImmortal
func (self *Unstable) IsImmortal() c.Int {
	return 0
}

// Increments the reference count of the object, if it's not zero.
// PyUnstable_EnableTryIncRef() should be called on the object
// before calling this function in order to avoid spurious failures.
//
// llgo:link (*Unstable).TryIncRef C.PyUnstable_TryIncRef
func (self *Unstable) TryIncRef() c.Int {
	return 0
}

// llgo:link (*Unstable).EnableTryIncRef C.PyUnstable_EnableTryIncRef
func (self *Unstable) EnableTryIncRef() {
}

// llgo:link (*Unstable).ObjectIsUniquelyReferenced C.PyUnstable_Object_IsUniquelyReferenced
func (self *Unstable) ObjectIsUniquelyReferenced() c.Int {
	return 0
}

// llgo:link (*Type).ModuleByDef C.PyType_GetModuleByDef
func (self *Type) ModuleByDef(_llcppg_param2 *ModuleDef) *Object {
	return nil
}

// llgo:link (*Type).Freeze C.PyType_Freeze
func (self *Type) Freeze() c.Int {
	return 0
}
