// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

// This example code implements an object constructor with a custom
// allocator, where PyObject_New is inlined, and shows the important
// distinction between two steps (at least):
// 1) the actual allocation of the object storage;
// 2) the initialization of the Python specific fields
// in this storage with PyObject_{Init, InitVar}.
//
// PyObject *
// YourObject_New(...)
// {
// PyObject *op;
//
// op = (PyObject *) Your_Allocator(_PyObject_SIZE(YourTypeStruct));
// if (op == NULL) {
// return PyErr_NoMemory();
// }
//
// PyObject_Init(op, &YourTypeStruct);
//
// op->ob_field = value;
// ...
// return op;
// }
//
// Note that in C++, the use of the new operator usually implies that
// the 1st step is performed automatically for you, so in a C++ class
// constructor you would start directly with PyObject_Init/InitVar.
//
// llgo:type C
type ObjectArenaAllocator struct {
	Ctx   unsafe.Pointer
	Alloc func(_llcppg_param1 unsafe.Pointer, _llcppg_param2 c.SizeT) unsafe.Pointer
	Free  func(_llcppg_param1 unsafe.Pointer, _llcppg_param2 unsafe.Pointer, _llcppg_param3 c.SizeT)
}

// Visit all live GC-capable objects, similar to gc.get_objects(None). The
// supplied callback is called on every such object with the void* arg set
// to the supplied arg. Returning 0 from the callback ends iteration, returning
// 1 allows iteration to continue. Returning any other value may result in
// undefined behaviour.
//
// If new objects are (de)allocated by the callback it is undefined if they
// will be visited.
//
// Garbage collection is disabled during operation. Explicitly running a
// collection in the callback may lead to undefined behaviour e.g. visiting the
// same objects multiple times or not at all.
//
// llgo:type C
type GcvisitobjectsT = func(_llcppg_param1 *Object, _llcppg_param2 unsafe.Pointer) c.Int

// Functions to call the same malloc/realloc/free as used by Python's
// object allocator.  If WITH_PYMALLOC is enabled, these may differ from
// the platform malloc/realloc/free.  The Python object allocator is
// designed for fast, cache-conscious allocation of many "small" objects,
// and with low hidden memory overhead.
//
// PyObject_Malloc(0) returns a unique non-NULL pointer if possible.
//
// PyObject_Realloc(NULL, n) acts like PyObject_Malloc(n).
// PyObject_Realloc(p != NULL, 0) does not return  NULL, or free the memory
// at p.
//
// Returned pointers must be checked for NULL explicitly; no action is
// performed on failure other than to return NULL (no warning it printed, no
// exception is set, etc).
//
// For allocating objects, use PyObject_{New, NewVar} instead whenever
// possible.  The PyObject_{Malloc, Realloc, Free} family is exposed
// so that you can exploit Python's small-block allocator for non-object
// uses.  If you must use these routines to allocate object memory, make sure
// the object gets initialized via PyObject_{Init, InitVar} after obtaining
// the raw memory.
//
//go:linkname ObjectMalloc C.PyObject_Malloc
func ObjectMalloc(size c.SizeT) unsafe.Pointer

//go:linkname ObjectCalloc C.PyObject_Calloc
func ObjectCalloc(nelem c.SizeT, elsize c.SizeT) unsafe.Pointer

//go:linkname ObjectRealloc C.PyObject_Realloc
func ObjectRealloc(ptr unsafe.Pointer, new_size c.SizeT) unsafe.Pointer

//go:linkname ObjectFree C.PyObject_Free
func ObjectFree(ptr unsafe.Pointer)

// Functions
//
// llgo:link (*Object).Init C.PyObject_Init
func (self *Object) Init(_llcppg_param2 *TypeObject) *Object {
	return self
}

// llgo:link (*VarObject).ObjectInit C.PyObject_InitVar
func (self *VarObject) ObjectInit(_llcppg_param2 *TypeObject, _llcppg_param3 SsizeT) *VarObject {
	return self
}

//go:linkname X_ObjectNew C._PyObject_New
func X_ObjectNew(_llcppg_param1 *TypeObject) *Object

//go:linkname X_ObjectNewVar C._PyObject_NewVar
func X_ObjectNewVar(_llcppg_param1 *TypeObject, _llcppg_param2 SsizeT) *VarObject

// C equivalent of gc.collect().
//
//go:linkname GC_Collect C.PyGC_Collect
func GC_Collect() SsizeT

// C API for controlling the state of the garbage collector
//
//go:linkname GC_Enable C.PyGC_Enable
func GC_Enable() c.Int

//go:linkname GC_Disable C.PyGC_Disable
func GC_Disable() c.Int

//go:linkname GC_IsEnabled C.PyGC_IsEnabled
func GC_IsEnabled() c.Int

//go:linkname X_Object_GC_Resize C._PyObject_GC_Resize
func X_Object_GC_Resize(_llcppg_param1 *VarObject, _llcppg_param2 SsizeT) *VarObject

//go:linkname X_Object_GC_New C._PyObject_GC_New
func X_Object_GC_New(_llcppg_param1 *TypeObject) *Object

//go:linkname X_Object_GC_NewVar C._PyObject_GC_NewVar
func X_Object_GC_NewVar(_llcppg_param1 *TypeObject, _llcppg_param2 SsizeT) *VarObject

// Tell the GC to track this object.
//
// See also private _PyObject_GC_TRACK() macro.
//
//go:linkname Object_GC_Track C.PyObject_GC_Track
func Object_GC_Track(_llcppg_param1 unsafe.Pointer)

// Tell the GC to stop tracking this object.
//
// See also private _PyObject_GC_UNTRACK() macro.
//
//go:linkname Object_GC_UnTrack C.PyObject_GC_UnTrack
func Object_GC_UnTrack(_llcppg_param1 unsafe.Pointer)

//go:linkname Object_GC_Del C.PyObject_GC_Del
func Object_GC_Del(_llcppg_param1 unsafe.Pointer)

// llgo:link (*Object).GC_IsTracked C.PyObject_GC_IsTracked
func (self *Object) GC_IsTracked() c.Int {
	return 0
}

// llgo:link (*Object).GC_IsFinalized C.PyObject_GC_IsFinalized
func (self *Object) GC_IsFinalized() c.Int {
	return 0
}

// Get the arena allocator.
//
//go:linkname ObjectGetArenaAllocator C.PyObject_GetArenaAllocator
func ObjectGetArenaAllocator(allocator *ObjectArenaAllocator)

// Set the arena allocator.
//
//go:linkname ObjectSetArenaAllocator C.PyObject_SetArenaAllocator
func ObjectSetArenaAllocator(allocator *ObjectArenaAllocator)

// Test if an object implements the garbage collector protocol
//
// llgo:link (*Object).IS_GC C.PyObject_IS_GC
func (self *Object) IS_GC() c.Int {
	return 0
}

// Test if a type supports weak references
//
// llgo:link (*TypeObject).Type_SUPPORTS_WEAKREFS C.PyType_SUPPORTS_WEAKREFS
func (self *TypeObject) Type_SUPPORTS_WEAKREFS() c.Int {
	return 0
}

// llgo:link (*Object).GET_WEAKREFS_LISTPTR C.PyObject_GET_WEAKREFS_LISTPTR
func (self *Object) GET_WEAKREFS_LISTPTR() **Object {
	return nil
}

//go:linkname Unstable_Object_GC_NewWithExtraData C.PyUnstable_Object_GC_NewWithExtraData
func Unstable_Object_GC_NewWithExtraData(_llcppg_param1 *TypeObject, _llcppg_param2 c.SizeT) *Object

//go:linkname Unstable_GC_VisitObjects C.PyUnstable_GC_VisitObjects
func Unstable_GC_VisitObjects(callback GcvisitobjectsT, arg unsafe.Pointer)
