// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type X_odictobject struct {
}
type ODictObject = X_odictobject

//go:linkname ODictType C.PyODict_Type
var ODictType TypeObject

//go:linkname ODictIterType C.PyODictIter_Type
var ODictIterType TypeObject

//go:linkname ODictKeysType C.PyODictKeys_Type
var ODictKeysType TypeObject

//go:linkname ODictItemsType C.PyODictItems_Type
var ODictItemsType TypeObject

//go:linkname ODictValuesType C.PyODictValues_Type
var ODictValuesType TypeObject

//go:linkname ODictNew C.PyODict_New
func ODictNew() *Object

// llgo:link (*Object).ODictSetItem C.PyODict_SetItem
func (self *Object) ODictSetItem(key *Object, item *Object) c.Int {
	return 0
}

// llgo:link (*Object).ODictDelItem C.PyODict_DelItem
func (self *Object) ODictDelItem(key *Object) c.Int {
	return 0
}
