// Code generated by llcppg; DO NOT EDIT.

package py

import "unsafe"

type OS struct {
	X_object
}

func (self *Object) AsOS() *OS {
	return (*OS)(unsafe.Pointer(self))
}

// llgo:link (*OS).FSPath C.PyOS_FSPath
func (self *OS) FSPath() *Object {
	return nil
}
