// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const PyBUF_MAX_NDIM = 64
const PyBUF_SIMPLE = 0
const PyBUF_WRITABLE = 1
const PyBUF_WRITEABLE = 1
const PyBUF_FORMAT = 4
const PyBUF_ND = 8
const PyBUF_STRIDES = 24
const PyBUF_C_CONTIGUOUS = 56
const PyBUF_F_CONTIGUOUS = 88
const PyBUF_ANY_CONTIGUOUS = 152
const PyBUF_INDIRECT = 280
const PyBUF_CONTIG = 9
const PyBUF_CONTIG_RO = 8
const PyBUF_STRIDED = 25
const PyBUF_STRIDED_RO = 24
const PyBUF_RECORDS = 29
const PyBUF_RECORDS_RO = 28
const PyBUF_FULL = 285
const PyBUF_FULL_RO = 284
const PyBUF_READ = 256
const PyBUF_WRITE = 512

type PyBuffer struct {
	Buf        unsafe.Pointer
	Obj        *PyObject
	Len        PySsizeT
	Itemsize   PySsizeT
	Readonly   c.Int
	Ndim       c.Int
	Format     *c.Char
	Shape      *PySsizeT
	Strides    *PySsizeT
	Suboffsets *PySsizeT
	Internal   unsafe.Pointer
}

// llgo:type C
type Getbufferproc = func(_llcppg_param1 *PyObject, _llcppg_param2 *PyBuffer, _llcppg_param3 c.Int) c.Int

// llgo:type C
type Releasebufferproc = func(_llcppg_param1 *PyObject, _llcppg_param2 *PyBuffer)

// llgo:link (*PyObject).CheckBuffer C.PyObject_CheckBuffer
func (self *PyObject) CheckBuffer() c.Int {
	return 0
}

// llgo:link (*PyObject).Buffer C.PyObject_GetBuffer
func (self *PyObject) Buffer(view *PyBuffer, flags c.Int) c.Int {
	return 0
}

// llgo:link (*PyBuffer).Pointer C.PyBuffer_GetPointer
func (self *PyBuffer) Pointer(indices *PySsizeT) unsafe.Pointer {
	return nil
}

//go:linkname PyBuffer_SizeFromFormat C.PyBuffer_SizeFromFormat
func PyBuffer_SizeFromFormat(format *c.Char) PySsizeT

//go:linkname PyBuffer_ToContiguous C.PyBuffer_ToContiguous
func PyBuffer_ToContiguous(buf unsafe.Pointer, view *PyBuffer, len PySsizeT, order c.Char) c.Int

// llgo:link (*PyBuffer).FromContiguous C.PyBuffer_FromContiguous
func (self *PyBuffer) FromContiguous(buf unsafe.Pointer, len PySsizeT, order c.Char) c.Int {
	return 0
}

// llgo:link (*PyObject).CopyData C.PyObject_CopyData
func (self *PyObject) CopyData(src *PyObject) c.Int {
	return 0
}

// llgo:link (*PyBuffer).IsContiguous C.PyBuffer_IsContiguous
func (self *PyBuffer) IsContiguous(fort c.Char) c.Int {
	return 0
}

//go:linkname PyBuffer_FillContiguousStrides C.PyBuffer_FillContiguousStrides
func PyBuffer_FillContiguousStrides(ndims c.Int, shape *PySsizeT, strides *PySsizeT, itemsize c.Int, fort c.Char)

// llgo:link (*PyBuffer).FillInfo C.PyBuffer_FillInfo
func (self *PyBuffer) FillInfo(o *PyObject, buf unsafe.Pointer, len PySsizeT, readonly c.Int, flags c.Int) c.Int {
	return 0
}

// llgo:link (*PyBuffer).Release C.PyBuffer_Release
func (self *PyBuffer) Release() {
}
