// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

// llgo:type C
type PyCapsule_Destructor = func(_llcppg_param1 *PyObject)

//go:linkname PyCapsule_Type C.PyCapsule_Type
var PyCapsule_Type PyTypeObject

//go:linkname PyCapsule_New C.PyCapsule_New
func PyCapsule_New(pointer unsafe.Pointer, name *c.Char, destructor PyCapsule_Destructor) *PyObject

// llgo:link (*PyObject).PyCapsule_GetPointer C.PyCapsule_GetPointer
func (self *PyObject) PyCapsule_GetPointer(name *c.Char) unsafe.Pointer {
	return nil
}

// llgo:link (*PyObject).PyCapsule_GetDestructor C.PyCapsule_GetDestructor
func (self *PyObject) PyCapsule_GetDestructor() PyCapsule_Destructor {
	return nil
}

// llgo:link (*PyObject).PyCapsule_GetName C.PyCapsule_GetName
func (self *PyObject) PyCapsule_GetName() *c.Char {
	return nil
}

// llgo:link (*PyObject).PyCapsule_GetContext C.PyCapsule_GetContext
func (self *PyObject) PyCapsule_GetContext() unsafe.Pointer {
	return nil
}

// llgo:link (*PyObject).PyCapsule_IsValid C.PyCapsule_IsValid
func (self *PyObject) PyCapsule_IsValid(name *c.Char) c.Int {
	return 0
}

// llgo:link (*PyObject).PyCapsule_SetPointer C.PyCapsule_SetPointer
func (self *PyObject) PyCapsule_SetPointer(pointer unsafe.Pointer) c.Int {
	return 0
}

// llgo:link (*PyObject).PyCapsule_SetDestructor C.PyCapsule_SetDestructor
func (self *PyObject) PyCapsule_SetDestructor(destructor PyCapsule_Destructor) c.Int {
	return 0
}

// llgo:link (*PyObject).PyCapsule_SetName C.PyCapsule_SetName
func (self *PyObject) PyCapsule_SetName(name *c.Char) c.Int {
	return 0
}

// llgo:link (*PyObject).PyCapsule_SetContext C.PyCapsule_SetContext
func (self *PyObject) PyCapsule_SetContext(context unsafe.Pointer) c.Int {
	return 0
}

//go:linkname PyCapsule_Import C.PyCapsule_Import
func PyCapsule_Import(name *c.Char, no_block c.Int) unsafe.Pointer
