// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

// llgo:type C
type CapsuleDestructor = func(_llcppg_param1 *Object)

//go:linkname CapsuleType C.PyCapsule_Type
var CapsuleType TypeObject

//go:linkname CapsuleNew C.PyCapsule_New
func CapsuleNew(pointer unsafe.Pointer, name *c.Char, destructor CapsuleDestructor) *Object

//go:linkname CapsuleGetPointer C.PyCapsule_GetPointer
func CapsuleGetPointer(capsule *Object, name *c.Char) unsafe.Pointer

//go:linkname CapsuleGetDestructor C.PyCapsule_GetDestructor
func CapsuleGetDestructor(capsule *Object) CapsuleDestructor

//go:linkname CapsuleGetName C.PyCapsule_GetName
func CapsuleGetName(capsule *Object) *c.Char

//go:linkname CapsuleGetContext C.PyCapsule_GetContext
func CapsuleGetContext(capsule *Object) unsafe.Pointer

//go:linkname CapsuleIsValid C.PyCapsule_IsValid
func CapsuleIsValid(capsule *Object, name *c.Char) c.Int

//go:linkname CapsuleSetPointer C.PyCapsule_SetPointer
func CapsuleSetPointer(capsule *Object, pointer unsafe.Pointer) c.Int

//go:linkname CapsuleSetDestructor C.PyCapsule_SetDestructor
func CapsuleSetDestructor(capsule *Object, destructor CapsuleDestructor) c.Int

//go:linkname CapsuleSetName C.PyCapsule_SetName
func CapsuleSetName(capsule *Object, name *c.Char) c.Int

//go:linkname CapsuleSetContext C.PyCapsule_SetContext
func CapsuleSetContext(capsule *Object, context unsafe.Pointer) c.Int

//go:linkname CapsuleImport C.PyCapsule_Import
func CapsuleImport(name *c.Char, no_block c.Int) unsafe.Pointer
