// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

const CTF_LOWER = 1
const CTF_UPPER = 2
const CTF_ALPHA = 3
const CTF_DIGIT = 4
const CTF_ALNUM = 7
const CTF_SPACE = 8
const CTF_XDIGIT = 16

//go:linkname X_ctypeTable C._Py_ctype_table
var X_ctypeTable [256]c.Uint

//go:linkname X_ctypeTolower C._Py_ctype_tolower
var X_ctypeTolower [256]uint8

//go:linkname X_ctypeToupper C._Py_ctype_toupper
var X_ctypeToupper [256]uint8
