// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type PyBaseExceptionObject struct {
	ObBase          PyObject
	Dict            *PyObject
	Args            *PyObject
	Notes           *PyObject
	Traceback       *PyObject
	Context         *PyObject
	Cause           *PyObject
	SuppressContext c.Char
}
type PyBaseExceptionGroupObject struct {
	ObBase          PyObject
	Dict            *PyObject
	Args            *PyObject
	Notes           *PyObject
	Traceback       *PyObject
	Context         *PyObject
	Cause           *PyObject
	SuppressContext c.Char
	Msg             *PyObject
	Excs            *PyObject
	ExcsStr         *PyObject
}
type PySyntaxErrorObject struct {
	ObBase           PyObject
	Dict             *PyObject
	Args             *PyObject
	Notes            *PyObject
	Traceback        *PyObject
	Context          *PyObject
	Cause            *PyObject
	SuppressContext  c.Char
	Msg              *PyObject
	Filename         *PyObject
	Lineno           *PyObject
	Offset           *PyObject
	EndLineno        *PyObject
	EndOffset        *PyObject
	Text             *PyObject
	PrintFileAndLine *PyObject
	Metadata         *PyObject
}
type PyImportErrorObject struct {
	ObBase          PyObject
	Dict            *PyObject
	Args            *PyObject
	Notes           *PyObject
	Traceback       *PyObject
	Context         *PyObject
	Cause           *PyObject
	SuppressContext c.Char
	Msg             *PyObject
	Name            *PyObject
	Path            *PyObject
	NameFrom        *PyObject
}
type PyUnicodeErrorObject struct {
	ObBase          PyObject
	Dict            *PyObject
	Args            *PyObject
	Notes           *PyObject
	Traceback       *PyObject
	Context         *PyObject
	Cause           *PyObject
	SuppressContext c.Char
	Encoding        *PyObject
	Object          *PyObject
	Start           PySsizeT
	End             PySsizeT
	Reason          *PyObject
}
type PySystemExitObject struct {
	ObBase          PyObject
	Dict            *PyObject
	Args            *PyObject
	Notes           *PyObject
	Traceback       *PyObject
	Context         *PyObject
	Cause           *PyObject
	SuppressContext c.Char
	Code            *PyObject
}
type PyOSErrorObject struct {
	ObBase          PyObject
	Dict            *PyObject
	Args            *PyObject
	Notes           *PyObject
	Traceback       *PyObject
	Context         *PyObject
	Cause           *PyObject
	SuppressContext c.Char
	Myerrno         *PyObject
	Strerror        *PyObject
	Filename        *PyObject
	Filename2       *PyObject
	Written         PySsizeT
}
type PyStopIterationObject struct {
	ObBase          PyObject
	Dict            *PyObject
	Args            *PyObject
	Notes           *PyObject
	Traceback       *PyObject
	Context         *PyObject
	Cause           *PyObject
	SuppressContext c.Char
	Value           *PyObject
}
type PyNameErrorObject struct {
	ObBase          PyObject
	Dict            *PyObject
	Args            *PyObject
	Notes           *PyObject
	Traceback       *PyObject
	Context         *PyObject
	Cause           *PyObject
	SuppressContext c.Char
	Name            *PyObject
}
type PyAttributeErrorObject struct {
	ObBase          PyObject
	Dict            *PyObject
	Args            *PyObject
	Notes           *PyObject
	Traceback       *PyObject
	Context         *PyObject
	Cause           *PyObject
	SuppressContext c.Char
	Obj             *PyObject
	Name            *PyObject
}
type PyEnvironmentErrorObject = PyOSErrorObject

// llgo:link (*PyObject).PyErr_SetNone C.PyErr_SetNone
func (self *PyObject) PyErr_SetNone() {
}

// llgo:link (*PyObject).PyErr_SetObject C.PyErr_SetObject
func (self *PyObject) PyErr_SetObject(_llcppg_param2 *PyObject) {
}

// llgo:link (*PyObject).PyErr_SetString C.PyErr_SetString
func (self *PyObject) PyErr_SetString(string *c.Char) {
}

//go:linkname PyErr_Occurred C.PyErr_Occurred
func PyErr_Occurred() *PyObject

//go:linkname PyErr_Clear C.PyErr_Clear
func PyErr_Clear()

//go:linkname PyErr_Fetch C.PyErr_Fetch
func PyErr_Fetch(_llcppg_param1 **PyObject, _llcppg_param2 **PyObject, _llcppg_param3 **PyObject)

// llgo:link (*PyObject).PyErr_Restore C.PyErr_Restore
func (self *PyObject) PyErr_Restore(_llcppg_param2 *PyObject, _llcppg_param3 *PyObject) {
}

//go:linkname PyErr_GetRaisedException C.PyErr_GetRaisedException
func PyErr_GetRaisedException() *PyObject

// llgo:link (*PyObject).PyErr_SetRaisedException C.PyErr_SetRaisedException
func (self *PyObject) PyErr_SetRaisedException() {
}

//go:linkname PyErr_GetHandledException C.PyErr_GetHandledException
func PyErr_GetHandledException() *PyObject

// llgo:link (*PyObject).PyErr_SetHandledException C.PyErr_SetHandledException
func (self *PyObject) PyErr_SetHandledException() {
}

//go:linkname PyErr_GetExcInfo C.PyErr_GetExcInfo
func PyErr_GetExcInfo(_llcppg_param1 **PyObject, _llcppg_param2 **PyObject, _llcppg_param3 **PyObject)

// llgo:link (*PyObject).PyErr_SetExcInfo C.PyErr_SetExcInfo
func (self *PyObject) PyErr_SetExcInfo(_llcppg_param2 *PyObject, _llcppg_param3 *PyObject) {
}

//go:linkname Py_FatalError C.Py_FatalError
func Py_FatalError(message *c.Char)

// llgo:link (*PyObject).PyErr_GivenExceptionMatches C.PyErr_GivenExceptionMatches
func (self *PyObject) PyErr_GivenExceptionMatches(_llcppg_param2 *PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyErr_ExceptionMatches C.PyErr_ExceptionMatches
func (self *PyObject) PyErr_ExceptionMatches() c.Int {
	return 0
}

//go:linkname PyErr_NormalizeException C.PyErr_NormalizeException
func PyErr_NormalizeException(_llcppg_param1 **PyObject, _llcppg_param2 **PyObject, _llcppg_param3 **PyObject)

// llgo:link (*PyObject).PyException_SetTraceback C.PyException_SetTraceback
func (self *PyObject) PyException_SetTraceback(_llcppg_param2 *PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyException_GetTraceback C.PyException_GetTraceback
func (self *PyObject) PyException_GetTraceback() *PyObject {
	return self
}

// llgo:link (*PyObject).PyException_GetCause C.PyException_GetCause
func (self *PyObject) PyException_GetCause() *PyObject {
	return self
}

// llgo:link (*PyObject).PyException_SetCause C.PyException_SetCause
func (self *PyObject) PyException_SetCause(_llcppg_param2 *PyObject) {
}

// llgo:link (*PyObject).PyException_GetContext C.PyException_GetContext
func (self *PyObject) PyException_GetContext() *PyObject {
	return self
}

// llgo:link (*PyObject).PyException_SetContext C.PyException_SetContext
func (self *PyObject) PyException_SetContext(_llcppg_param2 *PyObject) {
}

// llgo:link (*PyObject).PyException_GetArgs C.PyException_GetArgs
func (self *PyObject) PyException_GetArgs() *PyObject {
	return self
}

// llgo:link (*PyObject).PyException_SetArgs C.PyException_SetArgs
func (self *PyObject) PyException_SetArgs(_llcppg_param2 *PyObject) {
}

// llgo:link (*PyObject).PyExceptionClass_Name C.PyExceptionClass_Name
func (self *PyObject) PyExceptionClass_Name() *c.Char {
	return nil
}

//go:linkname PyExc_BaseException C.PyExc_BaseException
var PyExc_BaseException *PyObject

//go:linkname PyExc_Exception C.PyExc_Exception
var PyExc_Exception *PyObject

//go:linkname PyExc_BaseExceptionGroup C.PyExc_BaseExceptionGroup
var PyExc_BaseExceptionGroup *PyObject

//go:linkname PyExc_StopAsyncIteration C.PyExc_StopAsyncIteration
var PyExc_StopAsyncIteration *PyObject

//go:linkname PyExc_StopIteration C.PyExc_StopIteration
var PyExc_StopIteration *PyObject

//go:linkname PyExc_GeneratorExit C.PyExc_GeneratorExit
var PyExc_GeneratorExit *PyObject

//go:linkname PyExc_ArithmeticError C.PyExc_ArithmeticError
var PyExc_ArithmeticError *PyObject

//go:linkname PyExc_LookupError C.PyExc_LookupError
var PyExc_LookupError *PyObject

//go:linkname PyExc_AssertionError C.PyExc_AssertionError
var PyExc_AssertionError *PyObject

//go:linkname PyExc_AttributeError C.PyExc_AttributeError
var PyExc_AttributeError *PyObject

//go:linkname PyExc_BufferError C.PyExc_BufferError
var PyExc_BufferError *PyObject

//go:linkname PyExc_EOFError C.PyExc_EOFError
var PyExc_EOFError *PyObject

//go:linkname PyExc_FloatingPointError C.PyExc_FloatingPointError
var PyExc_FloatingPointError *PyObject

//go:linkname PyExc_OSError C.PyExc_OSError
var PyExc_OSError *PyObject

//go:linkname PyExc_ImportError C.PyExc_ImportError
var PyExc_ImportError *PyObject

//go:linkname PyExc_ModuleNotFoundError C.PyExc_ModuleNotFoundError
var PyExc_ModuleNotFoundError *PyObject

//go:linkname PyExc_IndexError C.PyExc_IndexError
var PyExc_IndexError *PyObject

//go:linkname PyExc_KeyError C.PyExc_KeyError
var PyExc_KeyError *PyObject

//go:linkname PyExc_KeyboardInterrupt C.PyExc_KeyboardInterrupt
var PyExc_KeyboardInterrupt *PyObject

//go:linkname PyExc_MemoryError C.PyExc_MemoryError
var PyExc_MemoryError *PyObject

//go:linkname PyExc_NameError C.PyExc_NameError
var PyExc_NameError *PyObject

//go:linkname PyExc_OverflowError C.PyExc_OverflowError
var PyExc_OverflowError *PyObject

//go:linkname PyExc_RuntimeError C.PyExc_RuntimeError
var PyExc_RuntimeError *PyObject

//go:linkname PyExc_RecursionError C.PyExc_RecursionError
var PyExc_RecursionError *PyObject

//go:linkname PyExc_NotImplementedError C.PyExc_NotImplementedError
var PyExc_NotImplementedError *PyObject

//go:linkname PyExc_SyntaxError C.PyExc_SyntaxError
var PyExc_SyntaxError *PyObject

//go:linkname PyExc_IndentationError C.PyExc_IndentationError
var PyExc_IndentationError *PyObject

//go:linkname PyExc_TabError C.PyExc_TabError
var PyExc_TabError *PyObject

//go:linkname PyExc_ReferenceError C.PyExc_ReferenceError
var PyExc_ReferenceError *PyObject

//go:linkname PyExc_SystemError C.PyExc_SystemError
var PyExc_SystemError *PyObject

//go:linkname PyExc_SystemExit C.PyExc_SystemExit
var PyExc_SystemExit *PyObject

//go:linkname PyExc_TypeError C.PyExc_TypeError
var PyExc_TypeError *PyObject

//go:linkname PyExc_UnboundLocalError C.PyExc_UnboundLocalError
var PyExc_UnboundLocalError *PyObject

//go:linkname PyExc_UnicodeError C.PyExc_UnicodeError
var PyExc_UnicodeError *PyObject

//go:linkname PyExc_UnicodeEncodeError C.PyExc_UnicodeEncodeError
var PyExc_UnicodeEncodeError *PyObject

//go:linkname PyExc_UnicodeDecodeError C.PyExc_UnicodeDecodeError
var PyExc_UnicodeDecodeError *PyObject

//go:linkname PyExc_UnicodeTranslateError C.PyExc_UnicodeTranslateError
var PyExc_UnicodeTranslateError *PyObject

//go:linkname PyExc_ValueError C.PyExc_ValueError
var PyExc_ValueError *PyObject

//go:linkname PyExc_ZeroDivisionError C.PyExc_ZeroDivisionError
var PyExc_ZeroDivisionError *PyObject

//go:linkname PyExc_BlockingIOError C.PyExc_BlockingIOError
var PyExc_BlockingIOError *PyObject

//go:linkname PyExc_BrokenPipeError C.PyExc_BrokenPipeError
var PyExc_BrokenPipeError *PyObject

//go:linkname PyExc_ChildProcessError C.PyExc_ChildProcessError
var PyExc_ChildProcessError *PyObject

//go:linkname PyExc_ConnectionError C.PyExc_ConnectionError
var PyExc_ConnectionError *PyObject

//go:linkname PyExc_ConnectionAbortedError C.PyExc_ConnectionAbortedError
var PyExc_ConnectionAbortedError *PyObject

//go:linkname PyExc_ConnectionRefusedError C.PyExc_ConnectionRefusedError
var PyExc_ConnectionRefusedError *PyObject

//go:linkname PyExc_ConnectionResetError C.PyExc_ConnectionResetError
var PyExc_ConnectionResetError *PyObject

//go:linkname PyExc_FileExistsError C.PyExc_FileExistsError
var PyExc_FileExistsError *PyObject

//go:linkname PyExc_FileNotFoundError C.PyExc_FileNotFoundError
var PyExc_FileNotFoundError *PyObject

//go:linkname PyExc_InterruptedError C.PyExc_InterruptedError
var PyExc_InterruptedError *PyObject

//go:linkname PyExc_IsADirectoryError C.PyExc_IsADirectoryError
var PyExc_IsADirectoryError *PyObject

//go:linkname PyExc_NotADirectoryError C.PyExc_NotADirectoryError
var PyExc_NotADirectoryError *PyObject

//go:linkname PyExc_PermissionError C.PyExc_PermissionError
var PyExc_PermissionError *PyObject

//go:linkname PyExc_ProcessLookupError C.PyExc_ProcessLookupError
var PyExc_ProcessLookupError *PyObject

//go:linkname PyExc_TimeoutError C.PyExc_TimeoutError
var PyExc_TimeoutError *PyObject

//go:linkname PyExc_EnvironmentError C.PyExc_EnvironmentError
var PyExc_EnvironmentError *PyObject

//go:linkname PyExc_IOError C.PyExc_IOError
var PyExc_IOError *PyObject

//go:linkname PyExc_Warning C.PyExc_Warning
var PyExc_Warning *PyObject

//go:linkname PyExc_UserWarning C.PyExc_UserWarning
var PyExc_UserWarning *PyObject

//go:linkname PyExc_DeprecationWarning C.PyExc_DeprecationWarning
var PyExc_DeprecationWarning *PyObject

//go:linkname PyExc_PendingDeprecationWarning C.PyExc_PendingDeprecationWarning
var PyExc_PendingDeprecationWarning *PyObject

//go:linkname PyExc_SyntaxWarning C.PyExc_SyntaxWarning
var PyExc_SyntaxWarning *PyObject

//go:linkname PyExc_RuntimeWarning C.PyExc_RuntimeWarning
var PyExc_RuntimeWarning *PyObject

//go:linkname PyExc_FutureWarning C.PyExc_FutureWarning
var PyExc_FutureWarning *PyObject

//go:linkname PyExc_ImportWarning C.PyExc_ImportWarning
var PyExc_ImportWarning *PyObject

//go:linkname PyExc_UnicodeWarning C.PyExc_UnicodeWarning
var PyExc_UnicodeWarning *PyObject

//go:linkname PyExc_BytesWarning C.PyExc_BytesWarning
var PyExc_BytesWarning *PyObject

//go:linkname PyExc_EncodingWarning C.PyExc_EncodingWarning
var PyExc_EncodingWarning *PyObject

//go:linkname PyExc_ResourceWarning C.PyExc_ResourceWarning
var PyExc_ResourceWarning *PyObject

//go:linkname PyErr_BadArgument C.PyErr_BadArgument
func PyErr_BadArgument() c.Int

//go:linkname PyErr_NoMemory C.PyErr_NoMemory
func PyErr_NoMemory() *PyObject

// llgo:link (*PyObject).PyErr_SetFromErrno C.PyErr_SetFromErrno
func (self *PyObject) PyErr_SetFromErrno() *PyObject {
	return self
}

// llgo:link (*PyObject).PyErr_SetFromErrnoWithFilenameObject C.PyErr_SetFromErrnoWithFilenameObject
func (self *PyObject) PyErr_SetFromErrnoWithFilenameObject(_llcppg_param2 *PyObject) *PyObject {
	return self
}

// llgo:link (*PyObject).PyErr_SetFromErrnoWithFilenameObjects C.PyErr_SetFromErrnoWithFilenameObjects
func (self *PyObject) PyErr_SetFromErrnoWithFilenameObjects(_llcppg_param2 *PyObject, _llcppg_param3 *PyObject) *PyObject {
	return self
}

// llgo:link (*PyObject).PyErr_SetFromErrnoWithFilename C.PyErr_SetFromErrnoWithFilename
func (self *PyObject) PyErr_SetFromErrnoWithFilename(filename *c.Char) *PyObject {
	return self
}

// llgo:link (*PyObject).PyErr_Format C.PyErr_Format
func (self *PyObject) PyErr_Format(format *c.Char, __llgo_va_list ...any) *PyObject {
	return self
}

// llgo:link (*PyObject).PyErr_FormatV C.PyErr_FormatV
func (self *PyObject) PyErr_FormatV(format *c.Char, vargs c.VaList) *PyObject {
	return self
}

// llgo:link (*PyObject).PyErr_SetImportErrorSubclass C.PyErr_SetImportErrorSubclass
func (self *PyObject) PyErr_SetImportErrorSubclass(_llcppg_param2 *PyObject, _llcppg_param3 *PyObject, _llcppg_param4 *PyObject) *PyObject {
	return self
}

// llgo:link (*PyObject).PyErr_SetImportError C.PyErr_SetImportError
func (self *PyObject) PyErr_SetImportError(_llcppg_param2 *PyObject, _llcppg_param3 *PyObject) *PyObject {
	return self
}

//go:linkname PyErr_BadInternalCall C.PyErr_BadInternalCall
func PyErr_BadInternalCall()

//go:linkname X_PyErr_BadInternalCall C._PyErr_BadInternalCall
func X_PyErr_BadInternalCall(filename *c.Char, lineno c.Int)

//go:linkname PyErr_NewException C.PyErr_NewException
func PyErr_NewException(name *c.Char, base *PyObject, dict *PyObject) *PyObject

//go:linkname PyErr_NewExceptionWithDoc C.PyErr_NewExceptionWithDoc
func PyErr_NewExceptionWithDoc(name *c.Char, doc *c.Char, base *PyObject, dict *PyObject) *PyObject

// llgo:link (*PyObject).PyErr_WriteUnraisable C.PyErr_WriteUnraisable
func (self *PyObject) PyErr_WriteUnraisable() {
}

//go:linkname PyErr_CheckSignals C.PyErr_CheckSignals
func PyErr_CheckSignals() c.Int

//go:linkname PyErr_SetInterrupt C.PyErr_SetInterrupt
func PyErr_SetInterrupt()

//go:linkname PyErr_SetInterruptEx C.PyErr_SetInterruptEx
func PyErr_SetInterruptEx(signum c.Int) c.Int

//go:linkname PyErr_SyntaxLocation C.PyErr_SyntaxLocation
func PyErr_SyntaxLocation(filename *c.Char, lineno c.Int)

//go:linkname PyErr_SyntaxLocationEx C.PyErr_SyntaxLocationEx
func PyErr_SyntaxLocationEx(filename *c.Char, lineno c.Int, col_offset c.Int)

//go:linkname PyErr_ProgramText C.PyErr_ProgramText
func PyErr_ProgramText(filename *c.Char, lineno c.Int) *PyObject

//go:linkname PyUnicodeDecodeError_Create C.PyUnicodeDecodeError_Create
func PyUnicodeDecodeError_Create(encoding *c.Char, object *c.Char, length PySsizeT, start PySsizeT, end PySsizeT, reason *c.Char) *PyObject

// llgo:link (*PyObject).PyUnicodeEncodeError_GetEncoding C.PyUnicodeEncodeError_GetEncoding
func (self *PyObject) PyUnicodeEncodeError_GetEncoding() *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicodeDecodeError_GetEncoding C.PyUnicodeDecodeError_GetEncoding
func (self *PyObject) PyUnicodeDecodeError_GetEncoding() *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicodeEncodeError_GetObject C.PyUnicodeEncodeError_GetObject
func (self *PyObject) PyUnicodeEncodeError_GetObject() *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicodeDecodeError_GetObject C.PyUnicodeDecodeError_GetObject
func (self *PyObject) PyUnicodeDecodeError_GetObject() *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicodeTranslateError_GetObject C.PyUnicodeTranslateError_GetObject
func (self *PyObject) PyUnicodeTranslateError_GetObject() *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicodeEncodeError_GetStart C.PyUnicodeEncodeError_GetStart
func (self *PyObject) PyUnicodeEncodeError_GetStart(_llcppg_param2 *PySsizeT) c.Int {
	return 0
}

// llgo:link (*PyObject).PyUnicodeDecodeError_GetStart C.PyUnicodeDecodeError_GetStart
func (self *PyObject) PyUnicodeDecodeError_GetStart(_llcppg_param2 *PySsizeT) c.Int {
	return 0
}

// llgo:link (*PyObject).PyUnicodeTranslateError_GetStart C.PyUnicodeTranslateError_GetStart
func (self *PyObject) PyUnicodeTranslateError_GetStart(_llcppg_param2 *PySsizeT) c.Int {
	return 0
}

// llgo:link (*PyObject).PyUnicodeEncodeError_SetStart C.PyUnicodeEncodeError_SetStart
func (self *PyObject) PyUnicodeEncodeError_SetStart(_llcppg_param2 PySsizeT) c.Int {
	return 0
}

// llgo:link (*PyObject).PyUnicodeDecodeError_SetStart C.PyUnicodeDecodeError_SetStart
func (self *PyObject) PyUnicodeDecodeError_SetStart(_llcppg_param2 PySsizeT) c.Int {
	return 0
}

// llgo:link (*PyObject).PyUnicodeTranslateError_SetStart C.PyUnicodeTranslateError_SetStart
func (self *PyObject) PyUnicodeTranslateError_SetStart(_llcppg_param2 PySsizeT) c.Int {
	return 0
}

// llgo:link (*PyObject).PyUnicodeEncodeError_GetEnd C.PyUnicodeEncodeError_GetEnd
func (self *PyObject) PyUnicodeEncodeError_GetEnd(_llcppg_param2 *PySsizeT) c.Int {
	return 0
}

// llgo:link (*PyObject).PyUnicodeDecodeError_GetEnd C.PyUnicodeDecodeError_GetEnd
func (self *PyObject) PyUnicodeDecodeError_GetEnd(_llcppg_param2 *PySsizeT) c.Int {
	return 0
}

// llgo:link (*PyObject).PyUnicodeTranslateError_GetEnd C.PyUnicodeTranslateError_GetEnd
func (self *PyObject) PyUnicodeTranslateError_GetEnd(_llcppg_param2 *PySsizeT) c.Int {
	return 0
}

// llgo:link (*PyObject).PyUnicodeEncodeError_SetEnd C.PyUnicodeEncodeError_SetEnd
func (self *PyObject) PyUnicodeEncodeError_SetEnd(_llcppg_param2 PySsizeT) c.Int {
	return 0
}

// llgo:link (*PyObject).PyUnicodeDecodeError_SetEnd C.PyUnicodeDecodeError_SetEnd
func (self *PyObject) PyUnicodeDecodeError_SetEnd(_llcppg_param2 PySsizeT) c.Int {
	return 0
}

// llgo:link (*PyObject).PyUnicodeTranslateError_SetEnd C.PyUnicodeTranslateError_SetEnd
func (self *PyObject) PyUnicodeTranslateError_SetEnd(_llcppg_param2 PySsizeT) c.Int {
	return 0
}

// llgo:link (*PyObject).PyUnicodeEncodeError_GetReason C.PyUnicodeEncodeError_GetReason
func (self *PyObject) PyUnicodeEncodeError_GetReason() *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicodeDecodeError_GetReason C.PyUnicodeDecodeError_GetReason
func (self *PyObject) PyUnicodeDecodeError_GetReason() *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicodeTranslateError_GetReason C.PyUnicodeTranslateError_GetReason
func (self *PyObject) PyUnicodeTranslateError_GetReason() *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicodeEncodeError_SetReason C.PyUnicodeEncodeError_SetReason
func (self *PyObject) PyUnicodeEncodeError_SetReason(reason *c.Char) c.Int {
	return 0
}

// llgo:link (*PyObject).PyUnicodeDecodeError_SetReason C.PyUnicodeDecodeError_SetReason
func (self *PyObject) PyUnicodeDecodeError_SetReason(reason *c.Char) c.Int {
	return 0
}

// llgo:link (*PyObject).PyUnicodeTranslateError_SetReason C.PyUnicodeTranslateError_SetReason
func (self *PyObject) PyUnicodeTranslateError_SetReason(reason *c.Char) c.Int {
	return 0
}

//go:linkname PyOSSnprintf C.PyOS_snprintf
func PyOSSnprintf(str *c.Char, size c.SizeT, format *c.Char, __llgo_va_list ...any) c.Int

//go:linkname PyOSVsnprintf C.PyOS_vsnprintf
func PyOSVsnprintf(str *c.Char, size c.SizeT, format *c.Char, va c.VaList) c.Int

// llgo:link (*PyObject).X_PyErr_ChainExceptions1 C._PyErr_ChainExceptions1
func (self *PyObject) X_PyErr_ChainExceptions1() {
}

// llgo:link (*PyObject).PyUnstable_Exc_PrepReraiseStar C.PyUnstable_Exc_PrepReraiseStar
func (self *PyObject) PyUnstable_Exc_PrepReraiseStar(excs *PyObject) *PyObject {
	return self
}

//go:linkname PySignal_SetWakeupFd C.PySignal_SetWakeupFd
func PySignal_SetWakeupFd(fd c.Int) c.Int

// llgo:link (*PyObject).PyErr_SyntaxLocationObject C.PyErr_SyntaxLocationObject
func (self *PyObject) PyErr_SyntaxLocationObject(lineno c.Int, col_offset c.Int) {
}

// llgo:link (*PyObject).PyErr_RangedSyntaxLocationObject C.PyErr_RangedSyntaxLocationObject
func (self *PyObject) PyErr_RangedSyntaxLocationObject(lineno c.Int, col_offset c.Int, end_lineno c.Int, end_col_offset c.Int) {
}

// llgo:link (*PyObject).PyErr_ProgramTextObject C.PyErr_ProgramTextObject
func (self *PyObject) PyErr_ProgramTextObject(lineno c.Int) *PyObject {
	return self
}

//go:linkname X_Py_FatalErrorFunc C._Py_FatalErrorFunc
func X_Py_FatalErrorFunc(func_ *c.Char, message *c.Char)

//go:linkname PyErr_FormatUnraisable C.PyErr_FormatUnraisable
func PyErr_FormatUnraisable(_llcppg_param1 *c.Char, __llgo_va_list ...any)

//go:linkname PyExc_PythonFinalizationError C.PyExc_PythonFinalizationError
var PyExc_PythonFinalizationError *PyObject
