// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type BaseExceptionObject struct {
	ObBase          Object
	Dict            *Object
	Args            *Object
	Notes           *Object
	Traceback       *Object
	Context         *Object
	Cause           *Object
	SuppressContext c.Char
}
type BaseExceptionGroupObject struct {
	ObBase          Object
	Dict            *Object
	Args            *Object
	Notes           *Object
	Traceback       *Object
	Context         *Object
	Cause           *Object
	SuppressContext c.Char
	Msg             *Object
	Excs            *Object
	ExcsStr         *Object
}
type SyntaxErrorObject struct {
	ObBase           Object
	Dict             *Object
	Args             *Object
	Notes            *Object
	Traceback        *Object
	Context          *Object
	Cause            *Object
	SuppressContext  c.Char
	Msg              *Object
	Filename         *Object
	Lineno           *Object
	Offset           *Object
	EndLineno        *Object
	EndOffset        *Object
	Text             *Object
	PrintFileAndLine *Object
	Metadata         *Object
}
type ImportErrorObject struct {
	ObBase          Object
	Dict            *Object
	Args            *Object
	Notes           *Object
	Traceback       *Object
	Context         *Object
	Cause           *Object
	SuppressContext c.Char
	Msg             *Object
	Name            *Object
	Path            *Object
	NameFrom        *Object
}
type UnicodeErrorObject struct {
	ObBase          Object
	Dict            *Object
	Args            *Object
	Notes           *Object
	Traceback       *Object
	Context         *Object
	Cause           *Object
	SuppressContext c.Char
	Encoding        *Object
	Object          *Object
	Start           SsizeT
	End             SsizeT
	Reason          *Object
}
type SystemExitObject struct {
	ObBase          Object
	Dict            *Object
	Args            *Object
	Notes           *Object
	Traceback       *Object
	Context         *Object
	Cause           *Object
	SuppressContext c.Char
	Code            *Object
}
type OSErrorObject struct {
	ObBase          Object
	Dict            *Object
	Args            *Object
	Notes           *Object
	Traceback       *Object
	Context         *Object
	Cause           *Object
	SuppressContext c.Char
	Myerrno         *Object
	Strerror        *Object
	Filename        *Object
	Filename2       *Object
	Written         SsizeT
}
type StopIterationObject struct {
	ObBase          Object
	Dict            *Object
	Args            *Object
	Notes           *Object
	Traceback       *Object
	Context         *Object
	Cause           *Object
	SuppressContext c.Char
	Value           *Object
}
type NameErrorObject struct {
	ObBase          Object
	Dict            *Object
	Args            *Object
	Notes           *Object
	Traceback       *Object
	Context         *Object
	Cause           *Object
	SuppressContext c.Char
	Name            *Object
}
type AttributeErrorObject struct {
	ObBase          Object
	Dict            *Object
	Args            *Object
	Notes           *Object
	Traceback       *Object
	Context         *Object
	Cause           *Object
	SuppressContext c.Char
	Obj             *Object
	Name            *Object
}

// Compatibility typedefs
type EnvironmentErrorObject = OSErrorObject

//go:linkname ErrSetNone C.PyErr_SetNone
func ErrSetNone(_llcppg_param1 *Object)

//go:linkname ErrSetObject C.PyErr_SetObject
func ErrSetObject(_llcppg_param1 *Object, _llcppg_param2 *Object)

//go:linkname ErrSetString C.PyErr_SetString
func ErrSetString(exception *Object, string *c.Char)

//go:linkname ErrOccurred C.PyErr_Occurred
func ErrOccurred() *Object

//go:linkname ErrClear C.PyErr_Clear
func ErrClear()

//go:linkname ErrFetch C.PyErr_Fetch
func ErrFetch(_llcppg_param1 **Object, _llcppg_param2 **Object, _llcppg_param3 **Object)

//go:linkname ErrRestore C.PyErr_Restore
func ErrRestore(_llcppg_param1 *Object, _llcppg_param2 *Object, _llcppg_param3 *Object)

//go:linkname ErrGetRaisedException C.PyErr_GetRaisedException
func ErrGetRaisedException() *Object

//go:linkname ErrSetRaisedException C.PyErr_SetRaisedException
func ErrSetRaisedException(_llcppg_param1 *Object)

//go:linkname ErrGetHandledException C.PyErr_GetHandledException
func ErrGetHandledException() *Object

//go:linkname ErrSetHandledException C.PyErr_SetHandledException
func ErrSetHandledException(_llcppg_param1 *Object)

//go:linkname ErrGetExcInfo C.PyErr_GetExcInfo
func ErrGetExcInfo(_llcppg_param1 **Object, _llcppg_param2 **Object, _llcppg_param3 **Object)

//go:linkname ErrSetExcInfo C.PyErr_SetExcInfo
func ErrSetExcInfo(_llcppg_param1 *Object, _llcppg_param2 *Object, _llcppg_param3 *Object)

// Defined in Python/pylifecycle.c
//
// The Py_FatalError() function is replaced with a macro which logs
// automatically the name of the current function, unless the Py_LIMITED_API
// macro is defined.
//
//go:linkname FatalError C.Py_FatalError
func FatalError(message *c.Char)

// Error testing and normalization
//
//go:linkname ErrGivenExceptionMatches C.PyErr_GivenExceptionMatches
func ErrGivenExceptionMatches(_llcppg_param1 *Object, _llcppg_param2 *Object) c.Int

//go:linkname ErrExceptionMatches C.PyErr_ExceptionMatches
func ErrExceptionMatches(_llcppg_param1 *Object) c.Int

//go:linkname ErrNormalizeException C.PyErr_NormalizeException
func ErrNormalizeException(_llcppg_param1 **Object, _llcppg_param2 **Object, _llcppg_param3 **Object)

// Traceback manipulation (PEP 3134)
//
//go:linkname ExceptionSetTraceback C.PyException_SetTraceback
func ExceptionSetTraceback(_llcppg_param1 *Object, _llcppg_param2 *Object) c.Int

//go:linkname ExceptionGetTraceback C.PyException_GetTraceback
func ExceptionGetTraceback(_llcppg_param1 *Object) *Object

// Cause manipulation (PEP 3134)
//
//go:linkname ExceptionGetCause C.PyException_GetCause
func ExceptionGetCause(_llcppg_param1 *Object) *Object

//go:linkname ExceptionSetCause C.PyException_SetCause
func ExceptionSetCause(_llcppg_param1 *Object, _llcppg_param2 *Object)

// Context manipulation (PEP 3134)
//
//go:linkname ExceptionGetContext C.PyException_GetContext
func ExceptionGetContext(_llcppg_param1 *Object) *Object

//go:linkname ExceptionSetContext C.PyException_SetContext
func ExceptionSetContext(_llcppg_param1 *Object, _llcppg_param2 *Object)

//go:linkname ExceptionGetArgs C.PyException_GetArgs
func ExceptionGetArgs(_llcppg_param1 *Object) *Object

//go:linkname ExceptionSetArgs C.PyException_SetArgs
func ExceptionSetArgs(_llcppg_param1 *Object, _llcppg_param2 *Object)

//go:linkname ExceptionClassName C.PyExceptionClass_Name
func ExceptionClassName(_llcppg_param1 *Object) *c.Char

// Predefined exceptions
//
//go:linkname ExcBaseException C.PyExc_BaseException
var ExcBaseException *Object

//go:linkname ExcException C.PyExc_Exception
var ExcException *Object

//go:linkname ExcBaseExceptionGroup C.PyExc_BaseExceptionGroup
var ExcBaseExceptionGroup *Object

//go:linkname ExcStopAsyncIteration C.PyExc_StopAsyncIteration
var ExcStopAsyncIteration *Object

//go:linkname ExcStopIteration C.PyExc_StopIteration
var ExcStopIteration *Object

//go:linkname ExcGeneratorExit C.PyExc_GeneratorExit
var ExcGeneratorExit *Object

//go:linkname ExcArithmeticError C.PyExc_ArithmeticError
var ExcArithmeticError *Object

//go:linkname ExcLookupError C.PyExc_LookupError
var ExcLookupError *Object

//go:linkname ExcAssertionError C.PyExc_AssertionError
var ExcAssertionError *Object

//go:linkname ExcAttributeError C.PyExc_AttributeError
var ExcAttributeError *Object

//go:linkname ExcBufferError C.PyExc_BufferError
var ExcBufferError *Object

//go:linkname ExcEOFError C.PyExc_EOFError
var ExcEOFError *Object

//go:linkname ExcFloatingPointError C.PyExc_FloatingPointError
var ExcFloatingPointError *Object

//go:linkname ExcOSError C.PyExc_OSError
var ExcOSError *Object

//go:linkname ExcImportError C.PyExc_ImportError
var ExcImportError *Object

//go:linkname ExcModuleNotFoundError C.PyExc_ModuleNotFoundError
var ExcModuleNotFoundError *Object

//go:linkname ExcIndexError C.PyExc_IndexError
var ExcIndexError *Object

//go:linkname ExcKeyError C.PyExc_KeyError
var ExcKeyError *Object

//go:linkname ExcKeyboardInterrupt C.PyExc_KeyboardInterrupt
var ExcKeyboardInterrupt *Object

//go:linkname ExcMemoryError C.PyExc_MemoryError
var ExcMemoryError *Object

//go:linkname ExcNameError C.PyExc_NameError
var ExcNameError *Object

//go:linkname ExcOverflowError C.PyExc_OverflowError
var ExcOverflowError *Object

//go:linkname ExcRuntimeError C.PyExc_RuntimeError
var ExcRuntimeError *Object

//go:linkname ExcRecursionError C.PyExc_RecursionError
var ExcRecursionError *Object

//go:linkname ExcNotImplementedError C.PyExc_NotImplementedError
var ExcNotImplementedError *Object

//go:linkname ExcSyntaxError C.PyExc_SyntaxError
var ExcSyntaxError *Object

//go:linkname ExcIndentationError C.PyExc_IndentationError
var ExcIndentationError *Object

//go:linkname ExcTabError C.PyExc_TabError
var ExcTabError *Object

//go:linkname ExcReferenceError C.PyExc_ReferenceError
var ExcReferenceError *Object

//go:linkname ExcSystemError C.PyExc_SystemError
var ExcSystemError *Object

//go:linkname ExcSystemExit C.PyExc_SystemExit
var ExcSystemExit *Object

//go:linkname ExcTypeError C.PyExc_TypeError
var ExcTypeError *Object

//go:linkname ExcUnboundLocalError C.PyExc_UnboundLocalError
var ExcUnboundLocalError *Object

//go:linkname ExcUnicodeError C.PyExc_UnicodeError
var ExcUnicodeError *Object

//go:linkname ExcUnicodeEncodeError C.PyExc_UnicodeEncodeError
var ExcUnicodeEncodeError *Object

//go:linkname ExcUnicodeDecodeError C.PyExc_UnicodeDecodeError
var ExcUnicodeDecodeError *Object

//go:linkname ExcUnicodeTranslateError C.PyExc_UnicodeTranslateError
var ExcUnicodeTranslateError *Object

//go:linkname ExcValueError C.PyExc_ValueError
var ExcValueError *Object

//go:linkname ExcZeroDivisionError C.PyExc_ZeroDivisionError
var ExcZeroDivisionError *Object

//go:linkname ExcBlockingIOError C.PyExc_BlockingIOError
var ExcBlockingIOError *Object

//go:linkname ExcBrokenPipeError C.PyExc_BrokenPipeError
var ExcBrokenPipeError *Object

//go:linkname ExcChildProcessError C.PyExc_ChildProcessError
var ExcChildProcessError *Object

//go:linkname ExcConnectionError C.PyExc_ConnectionError
var ExcConnectionError *Object

//go:linkname ExcConnectionAbortedError C.PyExc_ConnectionAbortedError
var ExcConnectionAbortedError *Object

//go:linkname ExcConnectionRefusedError C.PyExc_ConnectionRefusedError
var ExcConnectionRefusedError *Object

//go:linkname ExcConnectionResetError C.PyExc_ConnectionResetError
var ExcConnectionResetError *Object

//go:linkname ExcFileExistsError C.PyExc_FileExistsError
var ExcFileExistsError *Object

//go:linkname ExcFileNotFoundError C.PyExc_FileNotFoundError
var ExcFileNotFoundError *Object

//go:linkname ExcInterruptedError C.PyExc_InterruptedError
var ExcInterruptedError *Object

//go:linkname ExcIsADirectoryError C.PyExc_IsADirectoryError
var ExcIsADirectoryError *Object

//go:linkname ExcNotADirectoryError C.PyExc_NotADirectoryError
var ExcNotADirectoryError *Object

//go:linkname ExcPermissionError C.PyExc_PermissionError
var ExcPermissionError *Object

//go:linkname ExcProcessLookupError C.PyExc_ProcessLookupError
var ExcProcessLookupError *Object

//go:linkname ExcTimeoutError C.PyExc_TimeoutError
var ExcTimeoutError *Object

// Compatibility aliases
//
//go:linkname ExcEnvironmentError C.PyExc_EnvironmentError
var ExcEnvironmentError *Object

//go:linkname ExcIOError C.PyExc_IOError
var ExcIOError *Object

// Predefined warning categories
//
//go:linkname ExcWarning C.PyExc_Warning
var ExcWarning *Object

//go:linkname ExcUserWarning C.PyExc_UserWarning
var ExcUserWarning *Object

//go:linkname ExcDeprecationWarning C.PyExc_DeprecationWarning
var ExcDeprecationWarning *Object

//go:linkname ExcPendingDeprecationWarning C.PyExc_PendingDeprecationWarning
var ExcPendingDeprecationWarning *Object

//go:linkname ExcSyntaxWarning C.PyExc_SyntaxWarning
var ExcSyntaxWarning *Object

//go:linkname ExcRuntimeWarning C.PyExc_RuntimeWarning
var ExcRuntimeWarning *Object

//go:linkname ExcFutureWarning C.PyExc_FutureWarning
var ExcFutureWarning *Object

//go:linkname ExcImportWarning C.PyExc_ImportWarning
var ExcImportWarning *Object

//go:linkname ExcUnicodeWarning C.PyExc_UnicodeWarning
var ExcUnicodeWarning *Object

//go:linkname ExcBytesWarning C.PyExc_BytesWarning
var ExcBytesWarning *Object

//go:linkname ExcEncodingWarning C.PyExc_EncodingWarning
var ExcEncodingWarning *Object

//go:linkname ExcResourceWarning C.PyExc_ResourceWarning
var ExcResourceWarning *Object

// Convenience functions
//
//go:linkname ErrBadArgument C.PyErr_BadArgument
func ErrBadArgument() c.Int

//go:linkname ErrNoMemory C.PyErr_NoMemory
func ErrNoMemory() *Object

//go:linkname ErrSetFromErrno C.PyErr_SetFromErrno
func ErrSetFromErrno(_llcppg_param1 *Object) *Object

//go:linkname ErrSetFromErrnoWithFilenameObject C.PyErr_SetFromErrnoWithFilenameObject
func ErrSetFromErrnoWithFilenameObject(_llcppg_param1 *Object, _llcppg_param2 *Object) *Object

//go:linkname ErrSetFromErrnoWithFilenameObjects C.PyErr_SetFromErrnoWithFilenameObjects
func ErrSetFromErrnoWithFilenameObjects(_llcppg_param1 *Object, _llcppg_param2 *Object, _llcppg_param3 *Object) *Object

//go:linkname ErrSetFromErrnoWithFilename C.PyErr_SetFromErrnoWithFilename
func ErrSetFromErrnoWithFilename(exc *Object, filename *c.Char) *Object

//go:linkname ErrFormat C.PyErr_Format
func ErrFormat(exception *Object, format *c.Char, __llgo_va_list ...any) *Object

//go:linkname Err_FormatV C.PyErr_FormatV
func Err_FormatV(exception *Object, format *c.Char, vargs c.VaList) *Object

//go:linkname ErrSetImportErrorSubclass C.PyErr_SetImportErrorSubclass
func ErrSetImportErrorSubclass(_llcppg_param1 *Object, _llcppg_param2 *Object, _llcppg_param3 *Object, _llcppg_param4 *Object) *Object

//go:linkname ErrSetImportError C.PyErr_SetImportError
func ErrSetImportError(_llcppg_param1 *Object, _llcppg_param2 *Object, _llcppg_param3 *Object) *Object

// Export the old function so that the existing API remains available:
//
//go:linkname ErrBadInternalCall C.PyErr_BadInternalCall
func ErrBadInternalCall()

//go:linkname X_ErrBadInternalCall C._PyErr_BadInternalCall
func X_ErrBadInternalCall(filename *c.Char, lineno c.Int)

// Function to create a new exception
//
//go:linkname ErrNewException C.PyErr_NewException
func ErrNewException(name *c.Char, base *Object, dict *Object) *Object

//go:linkname ErrNewExceptionWithDoc C.PyErr_NewExceptionWithDoc
func ErrNewExceptionWithDoc(name *c.Char, doc *c.Char, base *Object, dict *Object) *Object

//go:linkname ErrWriteUnraisable C.PyErr_WriteUnraisable
func ErrWriteUnraisable(_llcppg_param1 *Object)

// In signalmodule.c
//
//go:linkname ErrCheckSignals C.PyErr_CheckSignals
func ErrCheckSignals() c.Int

//go:linkname ErrSetInterrupt C.PyErr_SetInterrupt
func ErrSetInterrupt()

//go:linkname ErrSetInterruptEx C.PyErr_SetInterruptEx
func ErrSetInterruptEx(signum c.Int) c.Int

// Support for adding program text to SyntaxErrors
//
//go:linkname ErrSyntaxLocation C.PyErr_SyntaxLocation
func ErrSyntaxLocation(filename *c.Char, lineno c.Int)

//go:linkname ErrSyntaxLocationEx C.PyErr_SyntaxLocationEx
func ErrSyntaxLocationEx(filename *c.Char, lineno c.Int, col_offset c.Int)

//go:linkname ErrProgramText C.PyErr_ProgramText
func ErrProgramText(filename *c.Char, lineno c.Int) *Object

// create a UnicodeDecodeError object
//
//go:linkname UnicodeDecodeErrorCreate C.PyUnicodeDecodeError_Create
func UnicodeDecodeErrorCreate(encoding *c.Char, object *c.Char, length SsizeT, start SsizeT, end SsizeT, reason *c.Char) *Object

// get the encoding attribute
//
//go:linkname UnicodeEncodeErrorGetEncoding C.PyUnicodeEncodeError_GetEncoding
func UnicodeEncodeErrorGetEncoding(_llcppg_param1 *Object) *Object

//go:linkname UnicodeDecodeErrorGetEncoding C.PyUnicodeDecodeError_GetEncoding
func UnicodeDecodeErrorGetEncoding(_llcppg_param1 *Object) *Object

// get the object attribute
//
//go:linkname UnicodeEncodeErrorGetObject C.PyUnicodeEncodeError_GetObject
func UnicodeEncodeErrorGetObject(_llcppg_param1 *Object) *Object

//go:linkname UnicodeDecodeErrorGetObject C.PyUnicodeDecodeError_GetObject
func UnicodeDecodeErrorGetObject(_llcppg_param1 *Object) *Object

//go:linkname UnicodeTranslateErrorGetObject C.PyUnicodeTranslateError_GetObject
func UnicodeTranslateErrorGetObject(_llcppg_param1 *Object) *Object

// get the value of the start attribute (the int * may not be NULL)
// return 0 on success, -1 on failure
//
//go:linkname UnicodeEncodeErrorGetStart C.PyUnicodeEncodeError_GetStart
func UnicodeEncodeErrorGetStart(_llcppg_param1 *Object, _llcppg_param2 *SsizeT) c.Int

//go:linkname UnicodeDecodeErrorGetStart C.PyUnicodeDecodeError_GetStart
func UnicodeDecodeErrorGetStart(_llcppg_param1 *Object, _llcppg_param2 *SsizeT) c.Int

//go:linkname UnicodeTranslateErrorGetStart C.PyUnicodeTranslateError_GetStart
func UnicodeTranslateErrorGetStart(_llcppg_param1 *Object, _llcppg_param2 *SsizeT) c.Int

// assign a new value to the start attribute
// return 0 on success, -1 on failure
//
//go:linkname UnicodeEncodeErrorSetStart C.PyUnicodeEncodeError_SetStart
func UnicodeEncodeErrorSetStart(_llcppg_param1 *Object, _llcppg_param2 SsizeT) c.Int

//go:linkname UnicodeDecodeErrorSetStart C.PyUnicodeDecodeError_SetStart
func UnicodeDecodeErrorSetStart(_llcppg_param1 *Object, _llcppg_param2 SsizeT) c.Int

//go:linkname UnicodeTranslateErrorSetStart C.PyUnicodeTranslateError_SetStart
func UnicodeTranslateErrorSetStart(_llcppg_param1 *Object, _llcppg_param2 SsizeT) c.Int

// get the value of the end attribute (the int *may not be NULL)
// return 0 on success, -1 on failure
//
//go:linkname UnicodeEncodeErrorGetEnd C.PyUnicodeEncodeError_GetEnd
func UnicodeEncodeErrorGetEnd(_llcppg_param1 *Object, _llcppg_param2 *SsizeT) c.Int

//go:linkname UnicodeDecodeErrorGetEnd C.PyUnicodeDecodeError_GetEnd
func UnicodeDecodeErrorGetEnd(_llcppg_param1 *Object, _llcppg_param2 *SsizeT) c.Int

//go:linkname UnicodeTranslateErrorGetEnd C.PyUnicodeTranslateError_GetEnd
func UnicodeTranslateErrorGetEnd(_llcppg_param1 *Object, _llcppg_param2 *SsizeT) c.Int

// assign a new value to the end attribute
// return 0 on success, -1 on failure
//
//go:linkname UnicodeEncodeErrorSetEnd C.PyUnicodeEncodeError_SetEnd
func UnicodeEncodeErrorSetEnd(_llcppg_param1 *Object, _llcppg_param2 SsizeT) c.Int

//go:linkname UnicodeDecodeErrorSetEnd C.PyUnicodeDecodeError_SetEnd
func UnicodeDecodeErrorSetEnd(_llcppg_param1 *Object, _llcppg_param2 SsizeT) c.Int

//go:linkname UnicodeTranslateErrorSetEnd C.PyUnicodeTranslateError_SetEnd
func UnicodeTranslateErrorSetEnd(_llcppg_param1 *Object, _llcppg_param2 SsizeT) c.Int

// get the value of the reason attribute
//
//go:linkname UnicodeEncodeErrorGetReason C.PyUnicodeEncodeError_GetReason
func UnicodeEncodeErrorGetReason(_llcppg_param1 *Object) *Object

//go:linkname UnicodeDecodeErrorGetReason C.PyUnicodeDecodeError_GetReason
func UnicodeDecodeErrorGetReason(_llcppg_param1 *Object) *Object

//go:linkname UnicodeTranslateErrorGetReason C.PyUnicodeTranslateError_GetReason
func UnicodeTranslateErrorGetReason(_llcppg_param1 *Object) *Object

// assign a new value to the reason attribute
// return 0 on success, -1 on failure
//
//go:linkname UnicodeEncodeErrorSetReason C.PyUnicodeEncodeError_SetReason
func UnicodeEncodeErrorSetReason(exc *Object, reason *c.Char) c.Int

//go:linkname UnicodeDecodeErrorSetReason C.PyUnicodeDecodeError_SetReason
func UnicodeDecodeErrorSetReason(exc *Object, reason *c.Char) c.Int

//go:linkname UnicodeTranslateErrorSetReason C.PyUnicodeTranslateError_SetReason
func UnicodeTranslateErrorSetReason(exc *Object, reason *c.Char) c.Int

//go:linkname OSSnprintf C.PyOS_snprintf
func OSSnprintf(str *c.Char, size c.SizeT, format *c.Char, __llgo_va_list ...any) c.Int

//go:linkname OSVsnprintf C.PyOS_vsnprintf
func OSVsnprintf(str *c.Char, size c.SizeT, format *c.Char, va c.VaList) c.Int

// Context manipulation (PEP 3134)
//
//go:linkname X_ErrChainExceptions1 C._PyErr_ChainExceptions1
func X_ErrChainExceptions1(_llcppg_param1 *Object)

// In exceptions.c
//
//go:linkname UnstableExcPrepReraiseStar C.PyUnstable_Exc_PrepReraiseStar
func UnstableExcPrepReraiseStar(orig *Object, excs *Object) *Object

// In signalmodule.c
//
//go:linkname SignalSetWakeupFd C.PySignal_SetWakeupFd
func SignalSetWakeupFd(fd c.Int) c.Int

// Support for adding program text to SyntaxErrors
//
//go:linkname ErrSyntaxLocationObject C.PyErr_SyntaxLocationObject
func ErrSyntaxLocationObject(filename *Object, lineno c.Int, col_offset c.Int)

//go:linkname ErrRangedSyntaxLocationObject C.PyErr_RangedSyntaxLocationObject
func ErrRangedSyntaxLocationObject(filename *Object, lineno c.Int, col_offset c.Int, end_lineno c.Int, end_col_offset c.Int)

//go:linkname ErrProgramTextObject C.PyErr_ProgramTextObject
func ErrProgramTextObject(filename *Object, lineno c.Int) *Object

//go:linkname X_FatalErrorFunc C._Py_FatalErrorFunc
func X_FatalErrorFunc(func_ *c.Char, message *c.Char)

//go:linkname ErrFormatUnraisable C.PyErr_FormatUnraisable
func ErrFormatUnraisable(_llcppg_param1 *c.Char, __llgo_va_list ...any)

//go:linkname ExcPythonFinalizationError C.PyExc_PythonFinalizationError
var ExcPythonFinalizationError *Object
