// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

// Version helpers. These are primarily macros, but have exported equivalents.
//
//go:linkname Py_PACK_FULL_VERSION C.Py_PACK_FULL_VERSION
func Py_PACK_FULL_VERSION(x c.Int, y c.Int, z c.Int, level c.Int, serial c.Int) c.Uint32T

//go:linkname Py_PACK_VERSION C.Py_PACK_VERSION
func Py_PACK_VERSION(x c.Int, y c.Int) c.Uint32T
