// Code generated by llcppg; DO NOT EDIT.

package py

import "github.com/goplus/lib/c"

const HAVE_LONG_LONG = 1
const PYLONG_BITS_IN_DIGIT = 30
const SIZEOF_PY_HASH_T = 8
const SIZEOF_PY_UHASH_T = 8
const FORMAT_SIZE_T = "z"
const BIG_ENDIAN = 0
const LITTLE_ENDIAN = 1
const CAN_START_THREADS = 1

// uintptr_t is the C9X name for an unsigned integral type such that a
// legitimate void* can be cast to uintptr_t and then back to void* again
// without loss of information.  Similarly for intptr_t, wrt a signed
// integral type.
type UintptrT = c.UintptrT
type IntptrT = c.IntptrT
type SsizeT = c.SsizeT
type HashT = SsizeT
type UhashT = c.SizeT

// Now PY_SSIZE_T_CLEAN is mandatory. This is just for backward compatibility.
type SsizeCleanT = SsizeT
