// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const MAX_CO_EXTRA_USERS = 255
const PyTrace_CALL = 0
const PyTrace_EXCEPTION = 1
const PyTrace_LINE = 2
const PyTrace_RETURN = 3
const PyTrace_C_CALL = 4
const PyTrace_C_EXCEPTION = 5
const PyTrace_C_RETURN = 6
const PyTrace_OPCODE = 7
const X_Py_MAX_SCRIPT_PATH_SIZE = 512
const X_PY_DATA_STACK_CHUNK_SIZE = 16384

type PyGILState_STATE c.Uint

const (
	PyGILState_LOCKED   PyGILState_STATE = 0
	PyGILState_UNLOCKED PyGILState_STATE = 1
)

type X_ts struct {
	Prev                         *PyThreadState
	Next                         *PyThreadState
	Interp                       *PyInterpreterState
	EvalBreaker                  c.UintptrT
	X_status                     _llcppg_anon_5
	HoldsGil                     c.Int
	X_whence                     c.Int
	State                        c.Int
	PyRecursionRemaining         c.Int
	PyRecursionLimit             c.Int
	RecursionHeadroom            c.Int
	Tracing                      c.Int
	WhatEvent                    c.Int
	CurrentFrame                 *X_PyInterpreterFrame
	CProfilefunc                 PyTracefunc
	CTracefunc                   PyTracefunc
	CProfileobj                  *PyObject
	CTraceobj                    *PyObject
	CurrentException             *PyObject
	ExcInfo                      *X_PyErr_StackItem
	Dict                         *PyObject
	GilstateCounter              c.Int
	AsyncExc                     *PyObject
	ThreadId                     c.Ulong
	NativeThreadId               c.Ulong
	DeleteLater                  *PyObject
	CriticalSection              c.UintptrT
	CoroutineOriginTrackingDepth c.Int
	AsyncGenFirstiter            *PyObject
	AsyncGenFinalizer            *PyObject
	Context                      *PyObject
	ContextVer                   c.Uint64T
	Id                           c.Uint64T
	DatastackChunk               *X_PyStackChunk
	DatastackTop                 **PyObject
	DatastackLimit               **PyObject
	ExcState                     X_PyErr_StackItem
	CurrentExecutor              *PyObject
	DictGlobalVersion            c.Uint64T
	ThreadingLocalKey            *PyObject
	ThreadingLocalSentinel       *PyObject
	RemoteDebuggerSupport        X_PyRemoteDebuggerSupport
	DatastackCachedChunk         *X_PyStackChunk
}

// Py_tracefunc return -1 when raising an exception, or 0 for success.
//
// llgo:type C
type PyTracefunc = func(_llcppg_param1 *PyObject, _llcppg_param2 *PyFrameObject, _llcppg_param3 c.Int, _llcppg_param4 *PyObject) c.Int
type X_PyRemoteDebuggerSupport struct {
	DebuggerPendingCall c.Int32T
	DebuggerScriptPath  [512]c.Char
}
type X_errStackitem struct {
	ExcValue     *PyObject
	PreviousItem *X_errStackitem
}
type X_PyErr_StackItem = X_errStackitem
type X_stackChunk struct {
	Previous *X_stackChunk
	Size     c.SizeT
	Top      c.SizeT
	Data     [1]*PyObject
}
type X_PyStackChunk = X_stackChunk
type _llcppg_anon_5 struct {
	Initialized   c.Uint
	Bound         c.Uint
	Unbound       c.Uint
	BoundGilstate c.Uint
	Active        c.Uint
	Finalizing    c.Uint
	Cleared       c.Uint
	Finalized     c.Uint
	X             c.Uint
}

// Frame evaluation API
//
// llgo:type C
type X_PyFrameEvalFunction = func(_llcppg_param1 *PyThreadState, _llcppg_param2 *X_PyInterpreterFrame, _llcppg_param3 c.Int) *PyObject

//go:linkname PyInterpreterState_New C.PyInterpreterState_New
func PyInterpreterState_New() *PyInterpreterState

// llgo:link (*PyInterpreterState).Clear C.PyInterpreterState_Clear
func (self *PyInterpreterState) Clear() {
}

// llgo:link (*PyInterpreterState).Delete C.PyInterpreterState_Delete
func (self *PyInterpreterState) Delete() {
}

// New in 3.9 */
// /* Get the current interpreter state.
//
// Issue a fatal error if there no current Python thread state or no current
// interpreter. It cannot return NULL.
//
// The caller must hold the GIL.
//
//go:linkname PyInterpreterState_Get C.PyInterpreterState_Get
func PyInterpreterState_Get() *PyInterpreterState

// New in 3.8
//
// llgo:link (*PyInterpreterState).Dict C.PyInterpreterState_GetDict
func (self *PyInterpreterState) Dict() *PyObject {
	return nil
}

// New in 3.7
//
// llgo:link (*PyInterpreterState).ID C.PyInterpreterState_GetID
func (self *PyInterpreterState) ID() c.Int64T {
	return 0
}

// New in 3.3
//
// llgo:link (*PyObject).PyState_AddModule C.PyState_AddModule
func (self *PyObject) PyState_AddModule(_llcppg_param2 *PyModuleDef) c.Int {
	return 0
}

// llgo:link (*PyModuleDef).PyState_RemoveModule C.PyState_RemoveModule
func (self *PyModuleDef) PyState_RemoveModule() c.Int {
	return 0
}

// llgo:link (*PyModuleDef).PyState_FindModule C.PyState_FindModule
func (self *PyModuleDef) PyState_FindModule() *PyObject {
	return nil
}

// llgo:link (*PyInterpreterState).PyThreadState_New C.PyThreadState_New
func (self *PyInterpreterState) PyThreadState_New() *PyThreadState {
	return nil
}

// llgo:link (*PyThreadState).Clear C.PyThreadState_Clear
func (self *PyThreadState) Clear() {
}

// llgo:link (*PyThreadState).Delete C.PyThreadState_Delete
func (self *PyThreadState) Delete() {
}

// Get the current thread state.
//
// When the current thread state is NULL, this issues a fatal error (so that
// the caller needn't check for NULL).
//
// The caller must hold the GIL.
//
// See also PyThreadState_GetUnchecked() and _PyThreadState_GET().
//
//go:linkname PyThreadState_Get C.PyThreadState_Get
func PyThreadState_Get() *PyThreadState

// llgo:link (*PyThreadState).Swap C.PyThreadState_Swap
func (self *PyThreadState) Swap() *PyThreadState {
	return self
}

//go:linkname PyThreadState_GetDict C.PyThreadState_GetDict
func PyThreadState_GetDict() *PyObject

//go:linkname PyThreadState_SetAsyncExc C.PyThreadState_SetAsyncExc
func PyThreadState_SetAsyncExc(_llcppg_param1 c.Ulong, _llcppg_param2 *PyObject) c.Int

// New in 3.9
//
// llgo:link (*PyThreadState).Interpreter C.PyThreadState_GetInterpreter
func (self *PyThreadState) Interpreter() *PyInterpreterState {
	return nil
}

// llgo:link (*PyThreadState).Frame C.PyThreadState_GetFrame
func (self *PyThreadState) Frame() *PyFrameObject {
	return nil
}

// llgo:link (*PyThreadState).ID C.PyThreadState_GetID
func (self *PyThreadState) ID() c.Uint64T {
	return 0
}

// Ensure that the current thread is ready to call the Python
// C API, regardless of the current state of Python, or of its
// thread lock.  This may be called as many times as desired
// by a thread so long as each call is matched with a call to
// PyGILState_Release().  In general, other thread-state APIs may
// be used between _Ensure() and _Release() calls, so long as the
// thread-state is restored to its previous state before the Release().
// For example, normal use of the Py_BEGIN_ALLOW_THREADS/
// Py_END_ALLOW_THREADS macros are acceptable.
//
// The return value is an opaque "handle" to the thread state when
// PyGILState_Ensure() was called, and must be passed to
// PyGILState_Release() to ensure Python is left in the same state. Even
// though recursive calls are allowed, these handles can *not* be shared -
// each unique call to PyGILState_Ensure must save the handle for its
// call to PyGILState_Release.
//
// When the function returns, the current thread will hold the GIL.
//
// Failure is a fatal error.
//
//go:linkname PyGILState_Ensure C.PyGILState_Ensure
func PyGILState_Ensure() PyGILState_STATE

// Release any resources previously acquired.  After this call, Python's
// state will be the same as it was prior to the corresponding
// PyGILState_Ensure() call (but generally this state will be unknown to
// the caller, hence the use of the GILState API.)
//
// Every call to PyGILState_Ensure must be matched by a call to
// PyGILState_Release on the same thread.
//
// llgo:link PyGILState_STATE.PyGILState_Release C.PyGILState_Release
func (self PyGILState_STATE) PyGILState_Release() {
}

// Helper/diagnostic function - get the current thread state for
// this thread.  May return NULL if no GILState API has been used
// on the current thread.  Note that the main thread always has such a
// thread-state, even if no auto-thread-state call has been made
// on the main thread.
//
//go:linkname PyGILState_GetThisThreadState C.PyGILState_GetThisThreadState
func PyGILState_GetThisThreadState() *PyThreadState

// private interpreter helpers
//
// llgo:link (*PyInterpreterState).X_PyInterpreterState_RequiresIDRef C._PyInterpreterState_RequiresIDRef
func (self *PyInterpreterState) X_PyInterpreterState_RequiresIDRef() c.Int {
	return 0
}

// llgo:link (*PyInterpreterState).X_PyInterpreterState_RequireIDRef C._PyInterpreterState_RequireIDRef
func (self *PyInterpreterState) X_PyInterpreterState_RequireIDRef(_llcppg_param2 c.Int) {
}

// Similar to PyThreadState_Get(), but don't issue a fatal error
// if it is NULL.
//
//go:linkname PyThreadState_GetUnchecked C.PyThreadState_GetUnchecked
func PyThreadState_GetUnchecked() *PyThreadState

// Disable tracing and profiling.
//
// llgo:link (*PyThreadState).EnterTracing C.PyThreadState_EnterTracing
func (self *PyThreadState) EnterTracing() {
}

// Reset tracing and profiling: enable them if a trace function or a profile
// function is set, otherwise disable them.
//
// llgo:link (*PyThreadState).LeaveTracing C.PyThreadState_LeaveTracing
func (self *PyThreadState) LeaveTracing() {
}

// Helper/diagnostic function - return 1 if the current thread
// currently holds the GIL, 0 otherwise.
//
// The function returns 1 if _PyGILState_check_enabled is non-zero.
//
//go:linkname PyGILState_Check C.PyGILState_Check
func PyGILState_Check() c.Int

// The implementation of sys._current_frames()  Returns a dict mapping
// thread id to that thread's current frame.
//
//go:linkname X_PyThread_CurrentFrames C._PyThread_CurrentFrames
func X_PyThread_CurrentFrames() *PyObject

// Set the stack protection start address and stack protection size
// of a Python thread state
//
// llgo:link (*PyThreadState).PyUnstable_ThreadState_SetStackProtection C.PyUnstable_ThreadState_SetStackProtection
func (self *PyThreadState) PyUnstable_ThreadState_SetStackProtection(stack_start_addr unsafe.Pointer, stack_size c.SizeT) c.Int {
	return 0
}

// Reset the stack protection start address and stack protection size
// of a Python thread state
//
// llgo:link (*PyThreadState).PyUnstable_ThreadState_ResetStackProtection C.PyUnstable_ThreadState_ResetStackProtection
func (self *PyThreadState) PyUnstable_ThreadState_ResetStackProtection() {
}

// Routines for advanced debuggers, requested by David Beazley.
// Don't use unless you know what you are doing!
//
//go:linkname PyInterpreterState_Main C.PyInterpreterState_Main
func PyInterpreterState_Main() *PyInterpreterState

//go:linkname PyInterpreterState_Head C.PyInterpreterState_Head
func PyInterpreterState_Head() *PyInterpreterState

// llgo:link (*PyInterpreterState).Next C.PyInterpreterState_Next
func (self *PyInterpreterState) Next() *PyInterpreterState {
	return self
}

// llgo:link (*PyInterpreterState).ThreadHead C.PyInterpreterState_ThreadHead
func (self *PyInterpreterState) ThreadHead() *PyThreadState {
	return nil
}

// llgo:link (*PyThreadState).GetNext C.PyThreadState_Next
func (self *PyThreadState) GetNext() *PyThreadState {
	return self
}

//go:linkname PyThreadState_DeleteCurrent C.PyThreadState_DeleteCurrent
func PyThreadState_DeleteCurrent()

// llgo:link (*PyInterpreterState).X_PyInterpreterState_GetEvalFrameFunc C._PyInterpreterState_GetEvalFrameFunc
func (self *PyInterpreterState) X_PyInterpreterState_GetEvalFrameFunc() X_PyFrameEvalFunction {
	return nil
}

// llgo:link (*PyInterpreterState).X_PyInterpreterState_SetEvalFrameFunc C._PyInterpreterState_SetEvalFrameFunc
func (self *PyInterpreterState) X_PyInterpreterState_SetEvalFrameFunc(eval_frame X_PyFrameEvalFunction) {
}
