// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

const MAX_CO_EXTRA_USERS = 255

type PyGILState_STATE c.Uint

const (
	PyGILState_LOCKED   PyGILState_STATE = 0
	PyGILState_UNLOCKED PyGILState_STATE = 1
)

//go:linkname PyInterpreterState_New C.PyInterpreterState_New
func PyInterpreterState_New() *PyInterpreterState

// llgo:link (*PyInterpreterState).Clear C.PyInterpreterState_Clear
func (self *PyInterpreterState) Clear() {
}

// llgo:link (*PyInterpreterState).Delete C.PyInterpreterState_Delete
func (self *PyInterpreterState) Delete() {
}

//go:linkname PyInterpreterState_Get C.PyInterpreterState_Get
func PyInterpreterState_Get() *PyInterpreterState

// llgo:link (*PyInterpreterState).Dict C.PyInterpreterState_GetDict
func (self *PyInterpreterState) Dict() *PyObject {
	return nil
}

// llgo:link (*PyInterpreterState).ID C.PyInterpreterState_GetID
func (self *PyInterpreterState) ID() c.Int64T {
	return 0
}

// llgo:link (*PyObject).PyState_AddModule C.PyState_AddModule
func (self *PyObject) PyState_AddModule(_llcppg_param2 *PyModuleDef) c.Int {
	return 0
}

// llgo:link (*PyModuleDef).PyState_RemoveModule C.PyState_RemoveModule
func (self *PyModuleDef) PyState_RemoveModule() c.Int {
	return 0
}

// llgo:link (*PyModuleDef).PyState_FindModule C.PyState_FindModule
func (self *PyModuleDef) PyState_FindModule() *PyObject {
	return nil
}

// llgo:link (*PyInterpreterState).PyThreadState_New C.PyThreadState_New
func (self *PyInterpreterState) PyThreadState_New() *PyThreadState {
	return nil
}

// llgo:link (*PyThreadState).Clear C.PyThreadState_Clear
func (self *PyThreadState) Clear() {
}

// llgo:link (*PyThreadState).Delete C.PyThreadState_Delete
func (self *PyThreadState) Delete() {
}

//go:linkname PyThreadState_Get C.PyThreadState_Get
func PyThreadState_Get() *PyThreadState

// llgo:link (*PyThreadState).Swap C.PyThreadState_Swap
func (self *PyThreadState) Swap() *PyThreadState {
	return self
}

//go:linkname PyThreadState_GetDict C.PyThreadState_GetDict
func PyThreadState_GetDict() *PyObject

//go:linkname PyThreadState_SetAsyncExc C.PyThreadState_SetAsyncExc
func PyThreadState_SetAsyncExc(_llcppg_param1 c.Ulong, _llcppg_param2 *PyObject) c.Int

// llgo:link (*PyThreadState).Interpreter C.PyThreadState_GetInterpreter
func (self *PyThreadState) Interpreter() *PyInterpreterState {
	return nil
}

// llgo:link (*PyThreadState).Frame C.PyThreadState_GetFrame
func (self *PyThreadState) Frame() *PyFrameObject {
	return nil
}

// llgo:link (*PyThreadState).ID C.PyThreadState_GetID
func (self *PyThreadState) ID() c.Uint64T {
	return 0
}

//go:linkname PyGILState_Ensure C.PyGILState_Ensure
func PyGILState_Ensure() PyGILState_STATE

// llgo:link PyGILState_STATE.PyGILState_Release C.PyGILState_Release
func (self PyGILState_STATE) PyGILState_Release() {
}

//go:linkname PyGILState_GetThisThreadState C.PyGILState_GetThisThreadState
func PyGILState_GetThisThreadState() *PyThreadState
