// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

//go:linkname OSMystrnicmp C.PyOS_mystrnicmp
func OSMystrnicmp(_llcppg_param1 *c.Char, _llcppg_param2 *c.Char, _llcppg_param3 SsizeT) c.Int

//go:linkname OSMystricmp C.PyOS_mystricmp
func OSMystricmp(_llcppg_param1 *c.Char, _llcppg_param2 *c.Char) c.Int
