// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	"github.com/goplus/lib/c/pthread"
	"unsafe"
)

const WAIT_LOCK = 1
const NOWAIT_LOCK = 0

// Return status codes for Python lock acquisition.  Chosen for maximum
// backwards compatibility, ie failure -> 0, success -> 1.
type LockStatus c.Uint

const (
	LOCK_FAILURE  LockStatus = 0
	LOCK_ACQUIRED LockStatus = 1
	LOCK_INTR     LockStatus = 2
)

type ThreadTypeLock uintptr

// When Py_LIMITED_API is not defined, the type layout of Py_tss_t is
// exposed to allow static allocation in the API clients.  Even in this case,
// you must handle TSS keys through API functions due to compatibility.
type X_tssT struct {
	X_isInitialized c.Int
	X_key           pthread.Key
}

// New in 3.7
// Thread Specific Storage (TSS) API
type TssT = X_tssT

//go:linkname ThreadInitThread C.PyThread_init_thread
func ThreadInitThread()

//go:linkname ThreadStartNewThread C.PyThread_start_new_thread
func ThreadStartNewThread(_llcppg_param1 func(_llcppg_param1 unsafe.Pointer), _llcppg_param2 unsafe.Pointer) c.Ulong

// Terminates the current thread. Considered unsafe.
//
// WARNING: This function is only safe to call if all functions in the full call
// stack are written to safely allow it.  Additionally, the behavior is
// platform-dependent.  This function should be avoided, and is no longer called
// by Python itself.  It is retained only for compatibility with existing C
// extension code.
//
// With pthreads, calls `pthread_exit` causes some libcs (glibc?) to attempt to
// unwind the stack and call C++ destructors; if a `noexcept` function is
// reached, they may terminate the process. Others (macOS) do unwinding.
//
// On Windows, calls `_endthreadex` which kills the thread without calling C++
// destructors.
//
// In either case there is a risk of invalid references remaining to data on the
// thread stack.
//
//go:linkname ThreadExitThread C.PyThread_exit_thread
func ThreadExitThread()

//go:linkname ThreadGetThreadIdent C.PyThread_get_thread_ident
func ThreadGetThreadIdent() c.Ulong

//go:linkname ThreadGetThreadNativeId C.PyThread_get_thread_native_id
func ThreadGetThreadNativeId() c.Ulong

//go:linkname ThreadAllocateLock C.PyThread_allocate_lock
func ThreadAllocateLock() ThreadTypeLock

//go:linkname ThreadFreeLock C.PyThread_free_lock
func ThreadFreeLock(_llcppg_param1 ThreadTypeLock)

//go:linkname ThreadAcquireLock C.PyThread_acquire_lock
func ThreadAcquireLock(_llcppg_param1 ThreadTypeLock, _llcppg_param2 c.Int) c.Int

// If microseconds == 0, the call is non-blocking: it returns immediately
// even when the lock can't be acquired.
// If microseconds > 0, the call waits up to the specified duration.
// If microseconds < 0, the call waits until success (or abnormal failure)
//
// If *microseconds* is greater than PY_TIMEOUT_MAX, clamp the timeout to
// PY_TIMEOUT_MAX microseconds.
//
// If intr_flag is true and the acquire is interrupted by a signal, then the
// call will return PY_LOCK_INTR.  The caller may reattempt to acquire the
// lock.
//
//go:linkname ThreadAcquireLockTimed C.PyThread_acquire_lock_timed
func ThreadAcquireLockTimed(_llcppg_param1 ThreadTypeLock, microseconds c.LongLong, intr_flag c.Int) LockStatus

//go:linkname ThreadReleaseLock C.PyThread_release_lock
func ThreadReleaseLock(_llcppg_param1 ThreadTypeLock)

//go:linkname ThreadGetStacksize C.PyThread_get_stacksize
func ThreadGetStacksize() c.SizeT

//go:linkname ThreadSetStacksize C.PyThread_set_stacksize
func ThreadSetStacksize(_llcppg_param1 c.SizeT) c.Int

//go:linkname ThreadGetInfo C.PyThread_GetInfo
func ThreadGetInfo() *Object

// Thread Local Storage (TLS) API
// TLS API is DEPRECATED.  Use Thread Specific Storage (TSS) API.
//
// The existing TLS API has used int to represent TLS keys across all
// platforms, but it is not POSIX-compliant.  Therefore, the new TSS API uses
// opaque data type to represent TSS keys to be compatible (see PEP 539).
//
//go:linkname ThreadCreateKey C.PyThread_create_key
func ThreadCreateKey() c.Int

//go:linkname ThreadDeleteKey C.PyThread_delete_key
func ThreadDeleteKey(key c.Int)

//go:linkname ThreadSetKeyValue C.PyThread_set_key_value
func ThreadSetKeyValue(key c.Int, value unsafe.Pointer) c.Int

//go:linkname ThreadGetKeyValue C.PyThread_get_key_value
func ThreadGetKeyValue(key c.Int) unsafe.Pointer

//go:linkname ThreadDeleteKeyValue C.PyThread_delete_key_value
func ThreadDeleteKeyValue(key c.Int)

// Cleanup after a fork
//
//go:linkname Thread_ReInitTLS C.PyThread_ReInitTLS
func Thread_ReInitTLS()

//go:linkname ThreadTssAlloc C.PyThread_tss_alloc
func ThreadTssAlloc() *TssT

// llgo:link (*TssT).Free C.PyThread_tss_free
func (self *TssT) Free() {
}

// The parameter key must not be NULL.
//
// llgo:link (*TssT).IsCreated C.PyThread_tss_is_created
func (self *TssT) IsCreated() c.Int {
	return 0
}

// llgo:link (*TssT).Create C.PyThread_tss_create
func (self *TssT) Create() c.Int {
	return 0
}

// llgo:link (*TssT).Delete C.PyThread_tss_delete
func (self *TssT) Delete() {
}

// llgo:link (*TssT).Set C.PyThread_tss_set
func (self *TssT) Set(value unsafe.Pointer) c.Int {
	return 0
}

// llgo:link (*TssT).Get C.PyThread_tss_get
func (self *TssT) Get() unsafe.Pointer {
	return nil
}

// PY_TIMEOUT_MAX is the highest usable value (in microseconds) of PY_TIMEOUT_T
// type, and depends on the system threading API.
//
// NOTE: this isn't the same value as `_thread.TIMEOUT_MAX`. The _thread module
// exposes a higher-level API, with timeouts expressed in seconds and
// floating-point numbers allowed.
//
//go:linkname TIMEOUT_MAX C.PY_TIMEOUT_MAX
var TIMEOUT_MAX c.LongLong
