// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

//go:linkname Py_CompileString C.Py_CompileString
func Py_CompileString(_llcppg_param1 *c.Char, _llcppg_param2 *c.Char, _llcppg_param3 c.Int) *PyObject

//go:linkname PyErr_Print C.PyErr_Print
func PyErr_Print()

//go:linkname PyErr_PrintEx C.PyErr_PrintEx
func PyErr_PrintEx(_llcppg_param1 c.Int)

// llgo:link (*PyObject).PyErr_Display C.PyErr_Display
func (self *PyObject) PyErr_Display(_llcppg_param2 *PyObject, _llcppg_param3 *PyObject) {
}

// llgo:link (*PyObject).PyErr_DisplayException C.PyErr_DisplayException
func (self *PyObject) PyErr_DisplayException() {
}

//go:linkname PyOS_InputHook C.PyOS_InputHook
var PyOS_InputHook func() c.Int
