// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	"github.com/goplus/lib/c/pthread"
	"unsafe"
)

const WAIT_LOCK = 1
const NOWAIT_LOCK = 0

type PyLockStatus c.Uint

const (
	PY_LOCK_FAILURE  PyLockStatus = 0
	PY_LOCK_ACQUIRED PyLockStatus = 1
	PY_LOCK_INTR     PyLockStatus = 2
)

type PyThreadTypeLock uintptr
type X_PyTssT struct {
	X_isInitialized c.Int
	X_key           pthread.Key
}
type PyTssT = X_PyTssT

//go:linkname PyThreadInitThread C.PyThread_init_thread
func PyThreadInitThread()

//go:linkname PyThreadStartNewThread C.PyThread_start_new_thread
func PyThreadStartNewThread(_llcppg_param1 func(_llcppg_param1 unsafe.Pointer), _llcppg_param2 unsafe.Pointer) c.Ulong

//go:linkname PyThreadExitThread C.PyThread_exit_thread
func PyThreadExitThread()

//go:linkname PyThreadGetThreadIdent C.PyThread_get_thread_ident
func PyThreadGetThreadIdent() c.Ulong

//go:linkname PyThreadGetThreadNativeId C.PyThread_get_thread_native_id
func PyThreadGetThreadNativeId() c.Ulong

//go:linkname PyThreadAllocateLock C.PyThread_allocate_lock
func PyThreadAllocateLock() PyThreadTypeLock

// llgo:link PyThreadTypeLock.PyThreadFreeLock C.PyThread_free_lock
func (self PyThreadTypeLock) PyThreadFreeLock() {
}

// llgo:link PyThreadTypeLock.PyThreadAcquireLock C.PyThread_acquire_lock
func (self PyThreadTypeLock) PyThreadAcquireLock(_llcppg_param2 c.Int) c.Int {
	return 0
}

// llgo:link PyThreadTypeLock.PyThreadAcquireLockTimed C.PyThread_acquire_lock_timed
func (self PyThreadTypeLock) PyThreadAcquireLockTimed(microseconds c.LongLong, intr_flag c.Int) PyLockStatus {
	return 0
}

// llgo:link PyThreadTypeLock.PyThreadReleaseLock C.PyThread_release_lock
func (self PyThreadTypeLock) PyThreadReleaseLock() {
}

//go:linkname PyThreadGetStacksize C.PyThread_get_stacksize
func PyThreadGetStacksize() c.SizeT

//go:linkname PyThreadSetStacksize C.PyThread_set_stacksize
func PyThreadSetStacksize(_llcppg_param1 c.SizeT) c.Int

//go:linkname PyThread_GetInfo C.PyThread_GetInfo
func PyThread_GetInfo() *PyObject

//go:linkname PyThreadCreateKey C.PyThread_create_key
func PyThreadCreateKey() c.Int

//go:linkname PyThreadDeleteKey C.PyThread_delete_key
func PyThreadDeleteKey(key c.Int)

//go:linkname PyThreadSetKeyValue C.PyThread_set_key_value
func PyThreadSetKeyValue(key c.Int, value unsafe.Pointer) c.Int

//go:linkname PyThreadGetKeyValue C.PyThread_get_key_value
func PyThreadGetKeyValue(key c.Int) unsafe.Pointer

//go:linkname PyThreadDeleteKeyValue C.PyThread_delete_key_value
func PyThreadDeleteKeyValue(key c.Int)

//go:linkname PyThread_ReInitTLS C.PyThread_ReInitTLS
func PyThread_ReInitTLS()

//go:linkname PyThreadTssAlloc C.PyThread_tss_alloc
func PyThreadTssAlloc() *PyTssT

// llgo:link (*PyTssT).PyThreadTssFree C.PyThread_tss_free
func (self *PyTssT) PyThreadTssFree() {
}

// llgo:link (*PyTssT).PyThreadTssIsCreated C.PyThread_tss_is_created
func (self *PyTssT) PyThreadTssIsCreated() c.Int {
	return 0
}

// llgo:link (*PyTssT).PyThreadTssCreate C.PyThread_tss_create
func (self *PyTssT) PyThreadTssCreate() c.Int {
	return 0
}

// llgo:link (*PyTssT).PyThreadTssDelete C.PyThread_tss_delete
func (self *PyTssT) PyThreadTssDelete() {
}

// llgo:link (*PyTssT).PyThreadTssSet C.PyThread_tss_set
func (self *PyTssT) PyThreadTssSet(value unsafe.Pointer) c.Int {
	return 0
}

// llgo:link (*PyTssT).PyThreadTssGet C.PyThread_tss_get
func (self *PyTssT) PyThreadTssGet() unsafe.Pointer {
	return nil
}

//go:linkname PY_TIMEOUT_MAX C.PY_TIMEOUT_MAX
var PY_TIMEOUT_MAX c.LongLong
