// Code generated by llcppg; DO NOT EDIT.

package py

type PyObject = X_object
type PyLongObject = X_longobject
type PyTypeObject = X_typeobject
type X_frame struct {
}
type PyFrameObject = X_frame
type PyThreadState = X_ts
type X_is struct {
}
type PyInterpreterState = X_is
