// Code generated by llcppg; DO NOT EDIT.

package py

type Object = X_object
type LongObject = X_longobject
type TypeObject = X_typeobject
type X_frame struct {
}
type FrameObject = X_frame
type ThreadState = X_ts
type X_is struct {
}
type InterpreterState = X_is
