// Code generated by llcppg; DO NOT EDIT.

package py

import _ "unsafe"

//go:linkname PyRange_Type C.PyRange_Type
var PyRange_Type PyTypeObject

//go:linkname PyRangeIter_Type C.PyRangeIter_Type
var PyRangeIter_Type PyTypeObject

//go:linkname PyLongRangeIter_Type C.PyLongRangeIter_Type
var PyLongRangeIter_Type PyTypeObject
