// Code generated by llcppg; DO NOT EDIT.

package py

import _ "unsafe"

// A range object represents an integer range.  This is an immutable object;
// a range cannot change its value after creation.
//
// Range objects behave like the corresponding tuple objects except that
// they are represented by a start, stop, and step datamembers.
//
//go:linkname PyRange_Type C.PyRange_Type
var PyRange_Type PyTypeObject

//go:linkname PyRangeIter_Type C.PyRangeIter_Type
var PyRangeIter_Type PyTypeObject

//go:linkname PyLongRangeIter_Type C.PyLongRangeIter_Type
var PyLongRangeIter_Type PyTypeObject
