// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

const PySet_MINSIZE = 8

type Setentry struct {
	Key  *PyObject
	Hash PyHashT
}
type PySetObject struct {
	ObBase      PyObject
	Fill        PySsizeT
	Used        PySsizeT
	Mask        PySsizeT
	Table       *Setentry
	Hash        PyHashT
	Finger      PySsizeT
	Smalltable  [8]Setentry
	Weakreflist *PyObject
}

//go:linkname PySet_Type C.PySet_Type
var PySet_Type PyTypeObject

//go:linkname PyFrozenSet_Type C.PyFrozenSet_Type
var PyFrozenSet_Type PyTypeObject

//go:linkname PySetIter_Type C.PySetIter_Type
var PySetIter_Type PyTypeObject

// llgo:link (*PyObject).PySet_New C.PySet_New
func (self *PyObject) PySet_New() *PyObject {
	return self
}

// llgo:link (*PyObject).PyFrozenSet_New C.PyFrozenSet_New
func (self *PyObject) PyFrozenSet_New() *PyObject {
	return self
}

// llgo:link (*PyObject).PySet_Add C.PySet_Add
func (self *PyObject) PySet_Add(key *PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PySet_Clear C.PySet_Clear
func (self *PyObject) PySet_Clear() c.Int {
	return 0
}

// llgo:link (*PyObject).PySet_Contains C.PySet_Contains
func (self *PyObject) PySet_Contains(key *PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PySet_Discard C.PySet_Discard
func (self *PyObject) PySet_Discard(key *PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PySet_Pop C.PySet_Pop
func (self *PyObject) PySet_Pop() *PyObject {
	return self
}

// llgo:link (*PyObject).PySet_Size C.PySet_Size
func (self *PyObject) PySet_Size() PySsizeT {
	return 0
}
