// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type StructSequenceField struct {
	Name *c.Char
	Doc  *c.Char
}
type StructSequenceDesc struct {
	Name        *c.Char
	Doc         *c.Char
	Fields      *StructSequenceField
	NInSequence c.Int
}
type StructSequence = TupleObject

//go:linkname StructSequenceUnnamedField C.PyStructSequence_UnnamedField
var StructSequenceUnnamedField *c.Char

//go:linkname StructSequenceInitType C.PyStructSequence_InitType
func StructSequenceInitType(type_ *TypeObject, desc *StructSequenceDesc)

//go:linkname StructSequenceInitType2 C.PyStructSequence_InitType2
func StructSequenceInitType2(type_ *TypeObject, desc *StructSequenceDesc) c.Int

//go:linkname StructSequenceNewType C.PyStructSequence_NewType
func StructSequenceNewType(desc *StructSequenceDesc) *TypeObject

//go:linkname StructSequenceNew C.PyStructSequence_New
func StructSequenceNew(type_ *TypeObject) *Object

//go:linkname StructSequenceSetItem C.PyStructSequence_SetItem
func StructSequenceSetItem(_llcppg_param1 *Object, _llcppg_param2 SsizeT, _llcppg_param3 *Object)

//go:linkname StructSequenceGetItem C.PyStructSequence_GetItem
func StructSequenceGetItem(_llcppg_param1 *Object, _llcppg_param2 SsizeT) *Object
