// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

//go:linkname PySys_GetObject C.PySys_GetObject
func PySys_GetObject(_llcppg_param1 *c.Char) *PyObject

//go:linkname PySys_SetObject C.PySys_SetObject
func PySys_SetObject(_llcppg_param1 *c.Char, _llcppg_param2 *PyObject) c.Int

//go:linkname PySys_SetArgv C.PySys_SetArgv
func PySys_SetArgv(_llcppg_param1 c.Int, _llcppg_param2 **c.WcharT)

//go:linkname PySys_SetArgvEx C.PySys_SetArgvEx
func PySys_SetArgvEx(_llcppg_param1 c.Int, _llcppg_param2 **c.WcharT, _llcppg_param3 c.Int)

//go:linkname PySys_WriteStdout C.PySys_WriteStdout
func PySys_WriteStdout(format *c.Char, __llgo_va_list ...any)

//go:linkname PySys_WriteStderr C.PySys_WriteStderr
func PySys_WriteStderr(format *c.Char, __llgo_va_list ...any)

//go:linkname PySys_FormatStdout C.PySys_FormatStdout
func PySys_FormatStdout(format *c.Char, __llgo_va_list ...any)

//go:linkname PySys_FormatStderr C.PySys_FormatStderr
func PySys_FormatStderr(format *c.Char, __llgo_va_list ...any)

//go:linkname PySys_ResetWarnOptions C.PySys_ResetWarnOptions
func PySys_ResetWarnOptions()

//go:linkname PySys_GetXOptions C.PySys_GetXOptions
func PySys_GetXOptions() *PyObject
