// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

type X_traceback struct {
	ObBase   Object
	TbNext   *TracebackObject
	TbFrame  *FrameObject
	TbLasti  c.Int
	TbLineno c.Int
}
type TracebackObject = X_traceback
type TraceBack struct {
	X_frame
}

func (self *FrameObject) AsTraceBack() *TraceBack {
	return (*TraceBack)(unsafe.Pointer(self))
}

// Traceback interface
//
// llgo:link (*TraceBack).Here C.PyTraceBack_Here
func (self *TraceBack) Here() c.Int {
	return 0
}

// llgo:link (*TraceBack).Print C.PyTraceBack_Print
func (self *TraceBack) Print(_llcppg_param2 *Object) c.Int {
	return 0
}

// Reveal traceback type so we can typecheck traceback objects
//
//go:linkname TraceBackType C.PyTraceBack_Type
var TraceBackType TypeObject
