// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

// Track an allocated memory block in the tracemalloc module.
// Return 0 on success, return -1 on error (failed to allocate memory to store
// the trace).
//
// Return -2 if tracemalloc is disabled.
//
// If memory block is already tracked, update the existing trace.
//
//go:linkname TraceMallocTrack C.PyTraceMalloc_Track
func TraceMallocTrack(domain c.Uint, ptr c.UintptrT, size c.SizeT) c.Int

// Untrack an allocated memory block in the tracemalloc module.
// Do nothing if the block was not tracked.
//
// Return -2 if tracemalloc is disabled, otherwise return 0.
//
//go:linkname TraceMallocUntrack C.PyTraceMalloc_Untrack
func TraceMallocUntrack(domain c.Uint, ptr c.UintptrT) c.Int
