// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type X_traceback struct {
	ObBase   PyObject
	TbNext   *PyTracebackObject
	TbFrame  *PyFrameObject
	TbLasti  c.Int
	TbLineno c.Int
}
type PyTracebackObject = X_traceback

// Traceback interface
//
// llgo:link (*PyFrameObject).PyTraceBack_Here C.PyTraceBack_Here
func (self *PyFrameObject) PyTraceBack_Here() c.Int {
	return 0
}

// llgo:link (*PyObject).PyTraceBack_Print C.PyTraceBack_Print
func (self *PyObject) PyTraceBack_Print(_llcppg_param2 *PyObject) c.Int {
	return 0
}

// Reveal traceback type so we can typecheck traceback objects
//
//go:linkname PyTraceBack_Type C.PyTraceBack_Type
var PyTraceBack_Type PyTypeObject
