// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type X_traceback struct {
	ObBase   Object
	TbNext   *TracebackObject
	TbFrame  *FrameObject
	TbLasti  c.Int
	TbLineno c.Int
}
type TracebackObject = X_traceback

// Traceback interface
//
//go:linkname TraceBackHere C.PyTraceBack_Here
func TraceBackHere(_llcppg_param1 *FrameObject) c.Int

//go:linkname TraceBackPrint C.PyTraceBack_Print
func TraceBackPrint(_llcppg_param1 *Object, _llcppg_param2 *Object) c.Int

// Reveal traceback type so we can typecheck traceback objects
//
//go:linkname TraceBackType C.PyTraceBack_Type
var TraceBackType TypeObject
