// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const Py_UNICODE_SIZE = 4
const SSTATE_NOT_INTERNED = 0
const SSTATE_INTERNED_MORTAL = 1
const SSTATE_INTERNED_IMMORTAL = 2
const SSTATE_INTERNED_IMMORTAL_STATIC = 3

type PyUnicode_Kind c.Uint

const (
	PyUnicode_1BYTE_KIND PyUnicode_Kind = 1
	PyUnicode_2BYTE_KIND PyUnicode_Kind = 2
	PyUnicode_4BYTE_KIND PyUnicode_Kind = 4
)

type Py_UCS4 = c.Uint32T
type Py_UCS2 = c.Uint16T
type Py_UCS1 = c.Uint8T
type PY_UNICODE_TYPE = c.WcharT
type Py_UNICODE = c.WcharT
type PyASCIIObject struct {
	ObBase PyObject
	Length PySsizeT
	Hash   PyHashT
	State  _llcppg_anon_2
}
type _llcppg_anon_2 struct {
	Interned            c.Uint
	Kind                c.Uint
	Compact             c.Uint
	Ascii               c.Uint
	StaticallyAllocated c.Uint
	X                   c.Uint
}
type PyCompactUnicodeObject struct {
	X_base     PyASCIIObject
	Utf8Length PySsizeT
	Utf8       *c.Char
}
type PyUnicodeObject struct {
	X_base PyCompactUnicodeObject
	Data   _llcppg_anon_3
}
type _llcppg_anon_3 struct {
	_xgo_union [1]uint64
}
type PyUnicodeWriter struct {
}
type X_PyUnicodeWriter struct {
	Buffer       *PyObject
	Data         unsafe.Pointer
	Kind         c.Int
	Maxchar      Py_UCS4
	Size         PySsizeT
	Pos          PySsizeT
	MinLength    PySsizeT
	MinChar      Py_UCS4
	Overallocate uint8
	Readonly     uint8
}

//go:linkname PyUnicode_Type C.PyUnicode_Type
var PyUnicode_Type PyTypeObject

//go:linkname PyUnicodeIter_Type C.PyUnicodeIter_Type
var PyUnicodeIter_Type PyTypeObject

//go:linkname PyUnicode_FromStringAndSize C.PyUnicode_FromStringAndSize
func PyUnicode_FromStringAndSize(u *c.Char, size PySsizeT) *PyObject

//go:linkname PyUnicode_FromString C.PyUnicode_FromString
func PyUnicode_FromString(u *c.Char) *PyObject

// llgo:link (*PyObject).PyUnicode_Substring C.PyUnicode_Substring
func (self *PyObject) PyUnicode_Substring(start PySsizeT, end PySsizeT) *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicode_AsUCS4 C.PyUnicode_AsUCS4
func (self *PyObject) PyUnicode_AsUCS4(buffer *Py_UCS4, buflen PySsizeT, copy_null c.Int) *Py_UCS4 {
	return nil
}

// llgo:link (*PyObject).PyUnicode_AsUCS4Copy C.PyUnicode_AsUCS4Copy
func (self *PyObject) PyUnicode_AsUCS4Copy() *Py_UCS4 {
	return nil
}

// llgo:link (*PyObject).PyUnicode_GetLength C.PyUnicode_GetLength
func (self *PyObject) PyUnicode_GetLength() PySsizeT {
	return 0
}

// llgo:link (*PyObject).PyUnicode_ReadChar C.PyUnicode_ReadChar
func (self *PyObject) PyUnicode_ReadChar(index PySsizeT) Py_UCS4 {
	return 0
}

// llgo:link (*PyObject).PyUnicode_WriteChar C.PyUnicode_WriteChar
func (self *PyObject) PyUnicode_WriteChar(index PySsizeT, character Py_UCS4) c.Int {
	return 0
}

//go:linkname PyUnicode_Resize C.PyUnicode_Resize
func PyUnicode_Resize(unicode **PyObject, length PySsizeT) c.Int

// llgo:link (*PyObject).PyUnicode_FromEncodedObject C.PyUnicode_FromEncodedObject
func (self *PyObject) PyUnicode_FromEncodedObject(encoding *c.Char, errors *c.Char) *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicode_FromObject C.PyUnicode_FromObject
func (self *PyObject) PyUnicode_FromObject() *PyObject {
	return self
}

//go:linkname PyUnicode_FromFormatV C.PyUnicode_FromFormatV
func PyUnicode_FromFormatV(format *c.Char, vargs c.VaList) *PyObject

//go:linkname PyUnicode_FromFormat C.PyUnicode_FromFormat
func PyUnicode_FromFormat(format *c.Char, __llgo_va_list ...any) *PyObject

//go:linkname PyUnicode_InternInPlace C.PyUnicode_InternInPlace
func PyUnicode_InternInPlace(_llcppg_param1 **PyObject)

//go:linkname PyUnicode_InternFromString C.PyUnicode_InternFromString
func PyUnicode_InternFromString(u *c.Char) *PyObject

//go:linkname PyUnicode_FromWideChar C.PyUnicode_FromWideChar
func PyUnicode_FromWideChar(w *c.WcharT, size PySsizeT) *PyObject

// llgo:link (*PyObject).PyUnicode_AsWideChar C.PyUnicode_AsWideChar
func (self *PyObject) PyUnicode_AsWideChar(w *c.WcharT, size PySsizeT) PySsizeT {
	return 0
}

// llgo:link (*PyObject).PyUnicode_AsWideCharString C.PyUnicode_AsWideCharString
func (self *PyObject) PyUnicode_AsWideCharString(size *PySsizeT) *c.WcharT {
	return nil
}

//go:linkname PyUnicode_FromOrdinal C.PyUnicode_FromOrdinal
func PyUnicode_FromOrdinal(ordinal c.Int) *PyObject

//go:linkname PyUnicode_GetDefaultEncoding C.PyUnicode_GetDefaultEncoding
func PyUnicode_GetDefaultEncoding() *c.Char

//go:linkname PyUnicode_Decode C.PyUnicode_Decode
func PyUnicode_Decode(s *c.Char, size PySsizeT, encoding *c.Char, errors *c.Char) *PyObject

// llgo:link (*PyObject).PyUnicode_AsDecodedObject C.PyUnicode_AsDecodedObject
func (self *PyObject) PyUnicode_AsDecodedObject(encoding *c.Char, errors *c.Char) *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicode_AsDecodedUnicode C.PyUnicode_AsDecodedUnicode
func (self *PyObject) PyUnicode_AsDecodedUnicode(encoding *c.Char, errors *c.Char) *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicode_AsEncodedObject C.PyUnicode_AsEncodedObject
func (self *PyObject) PyUnicode_AsEncodedObject(encoding *c.Char, errors *c.Char) *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicode_AsEncodedString C.PyUnicode_AsEncodedString
func (self *PyObject) PyUnicode_AsEncodedString(encoding *c.Char, errors *c.Char) *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicode_AsEncodedUnicode C.PyUnicode_AsEncodedUnicode
func (self *PyObject) PyUnicode_AsEncodedUnicode(encoding *c.Char, errors *c.Char) *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicode_BuildEncodingMap C.PyUnicode_BuildEncodingMap
func (self *PyObject) PyUnicode_BuildEncodingMap() *PyObject {
	return self
}

//go:linkname PyUnicode_DecodeUTF7 C.PyUnicode_DecodeUTF7
func PyUnicode_DecodeUTF7(string *c.Char, length PySsizeT, errors *c.Char) *PyObject

//go:linkname PyUnicode_DecodeUTF7Stateful C.PyUnicode_DecodeUTF7Stateful
func PyUnicode_DecodeUTF7Stateful(string *c.Char, length PySsizeT, errors *c.Char, consumed *PySsizeT) *PyObject

//go:linkname PyUnicode_DecodeUTF8 C.PyUnicode_DecodeUTF8
func PyUnicode_DecodeUTF8(string *c.Char, length PySsizeT, errors *c.Char) *PyObject

//go:linkname PyUnicode_DecodeUTF8Stateful C.PyUnicode_DecodeUTF8Stateful
func PyUnicode_DecodeUTF8Stateful(string *c.Char, length PySsizeT, errors *c.Char, consumed *PySsizeT) *PyObject

// llgo:link (*PyObject).PyUnicode_AsUTF8String C.PyUnicode_AsUTF8String
func (self *PyObject) PyUnicode_AsUTF8String() *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicode_AsUTF8AndSize C.PyUnicode_AsUTF8AndSize
func (self *PyObject) PyUnicode_AsUTF8AndSize(size *PySsizeT) *c.Char {
	return nil
}

//go:linkname PyUnicode_DecodeUTF32 C.PyUnicode_DecodeUTF32
func PyUnicode_DecodeUTF32(string *c.Char, length PySsizeT, errors *c.Char, byteorder *c.Int) *PyObject

//go:linkname PyUnicode_DecodeUTF32Stateful C.PyUnicode_DecodeUTF32Stateful
func PyUnicode_DecodeUTF32Stateful(string *c.Char, length PySsizeT, errors *c.Char, byteorder *c.Int, consumed *PySsizeT) *PyObject

// llgo:link (*PyObject).PyUnicode_AsUTF32String C.PyUnicode_AsUTF32String
func (self *PyObject) PyUnicode_AsUTF32String() *PyObject {
	return self
}

//go:linkname PyUnicode_DecodeUTF16 C.PyUnicode_DecodeUTF16
func PyUnicode_DecodeUTF16(string *c.Char, length PySsizeT, errors *c.Char, byteorder *c.Int) *PyObject

//go:linkname PyUnicode_DecodeUTF16Stateful C.PyUnicode_DecodeUTF16Stateful
func PyUnicode_DecodeUTF16Stateful(string *c.Char, length PySsizeT, errors *c.Char, byteorder *c.Int, consumed *PySsizeT) *PyObject

// llgo:link (*PyObject).PyUnicode_AsUTF16String C.PyUnicode_AsUTF16String
func (self *PyObject) PyUnicode_AsUTF16String() *PyObject {
	return self
}

//go:linkname PyUnicode_DecodeUnicodeEscape C.PyUnicode_DecodeUnicodeEscape
func PyUnicode_DecodeUnicodeEscape(string *c.Char, length PySsizeT, errors *c.Char) *PyObject

// llgo:link (*PyObject).PyUnicode_AsUnicodeEscapeString C.PyUnicode_AsUnicodeEscapeString
func (self *PyObject) PyUnicode_AsUnicodeEscapeString() *PyObject {
	return self
}

//go:linkname PyUnicode_DecodeRawUnicodeEscape C.PyUnicode_DecodeRawUnicodeEscape
func PyUnicode_DecodeRawUnicodeEscape(string *c.Char, length PySsizeT, errors *c.Char) *PyObject

// llgo:link (*PyObject).PyUnicode_AsRawUnicodeEscapeString C.PyUnicode_AsRawUnicodeEscapeString
func (self *PyObject) PyUnicode_AsRawUnicodeEscapeString() *PyObject {
	return self
}

//go:linkname PyUnicode_DecodeLatin1 C.PyUnicode_DecodeLatin1
func PyUnicode_DecodeLatin1(string *c.Char, length PySsizeT, errors *c.Char) *PyObject

// llgo:link (*PyObject).PyUnicode_AsLatin1String C.PyUnicode_AsLatin1String
func (self *PyObject) PyUnicode_AsLatin1String() *PyObject {
	return self
}

//go:linkname PyUnicode_DecodeASCII C.PyUnicode_DecodeASCII
func PyUnicode_DecodeASCII(string *c.Char, length PySsizeT, errors *c.Char) *PyObject

// llgo:link (*PyObject).PyUnicode_AsASCIIString C.PyUnicode_AsASCIIString
func (self *PyObject) PyUnicode_AsASCIIString() *PyObject {
	return self
}

//go:linkname PyUnicode_DecodeCharmap C.PyUnicode_DecodeCharmap
func PyUnicode_DecodeCharmap(string *c.Char, length PySsizeT, mapping *PyObject, errors *c.Char) *PyObject

// llgo:link (*PyObject).PyUnicode_AsCharmapString C.PyUnicode_AsCharmapString
func (self *PyObject) PyUnicode_AsCharmapString(mapping *PyObject) *PyObject {
	return self
}

//go:linkname PyUnicode_DecodeLocaleAndSize C.PyUnicode_DecodeLocaleAndSize
func PyUnicode_DecodeLocaleAndSize(str *c.Char, len PySsizeT, errors *c.Char) *PyObject

//go:linkname PyUnicode_DecodeLocale C.PyUnicode_DecodeLocale
func PyUnicode_DecodeLocale(str *c.Char, errors *c.Char) *PyObject

// llgo:link (*PyObject).PyUnicode_EncodeLocale C.PyUnicode_EncodeLocale
func (self *PyObject) PyUnicode_EncodeLocale(errors *c.Char) *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicode_FSConverter C.PyUnicode_FSConverter
func (self *PyObject) PyUnicode_FSConverter(_llcppg_param2 unsafe.Pointer) c.Int {
	return 0
}

// llgo:link (*PyObject).PyUnicode_FSDecoder C.PyUnicode_FSDecoder
func (self *PyObject) PyUnicode_FSDecoder(_llcppg_param2 unsafe.Pointer) c.Int {
	return 0
}

//go:linkname PyUnicode_DecodeFSDefault C.PyUnicode_DecodeFSDefault
func PyUnicode_DecodeFSDefault(s *c.Char) *PyObject

//go:linkname PyUnicode_DecodeFSDefaultAndSize C.PyUnicode_DecodeFSDefaultAndSize
func PyUnicode_DecodeFSDefaultAndSize(s *c.Char, size PySsizeT) *PyObject

// llgo:link (*PyObject).PyUnicode_EncodeFSDefault C.PyUnicode_EncodeFSDefault
func (self *PyObject) PyUnicode_EncodeFSDefault() *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicode_Concat C.PyUnicode_Concat
func (self *PyObject) PyUnicode_Concat(right *PyObject) *PyObject {
	return self
}

//go:linkname PyUnicode_Append C.PyUnicode_Append
func PyUnicode_Append(pleft **PyObject, right *PyObject)

//go:linkname PyUnicode_AppendAndDel C.PyUnicode_AppendAndDel
func PyUnicode_AppendAndDel(pleft **PyObject, right *PyObject)

// llgo:link (*PyObject).PyUnicode_Split C.PyUnicode_Split
func (self *PyObject) PyUnicode_Split(sep *PyObject, maxsplit PySsizeT) *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicode_Splitlines C.PyUnicode_Splitlines
func (self *PyObject) PyUnicode_Splitlines(keepends c.Int) *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicode_Partition C.PyUnicode_Partition
func (self *PyObject) PyUnicode_Partition(sep *PyObject) *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicode_RPartition C.PyUnicode_RPartition
func (self *PyObject) PyUnicode_RPartition(sep *PyObject) *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicode_RSplit C.PyUnicode_RSplit
func (self *PyObject) PyUnicode_RSplit(sep *PyObject, maxsplit PySsizeT) *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicode_Translate C.PyUnicode_Translate
func (self *PyObject) PyUnicode_Translate(table *PyObject, errors *c.Char) *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicode_Join C.PyUnicode_Join
func (self *PyObject) PyUnicode_Join(seq *PyObject) *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicode_Tailmatch C.PyUnicode_Tailmatch
func (self *PyObject) PyUnicode_Tailmatch(substr *PyObject, start PySsizeT, end PySsizeT, direction c.Int) PySsizeT {
	return 0
}

// llgo:link (*PyObject).PyUnicode_Find C.PyUnicode_Find
func (self *PyObject) PyUnicode_Find(substr *PyObject, start PySsizeT, end PySsizeT, direction c.Int) PySsizeT {
	return 0
}

// llgo:link (*PyObject).PyUnicode_FindChar C.PyUnicode_FindChar
func (self *PyObject) PyUnicode_FindChar(ch Py_UCS4, start PySsizeT, end PySsizeT, direction c.Int) PySsizeT {
	return 0
}

// llgo:link (*PyObject).PyUnicode_Count C.PyUnicode_Count
func (self *PyObject) PyUnicode_Count(substr *PyObject, start PySsizeT, end PySsizeT) PySsizeT {
	return 0
}

// llgo:link (*PyObject).PyUnicode_Replace C.PyUnicode_Replace
func (self *PyObject) PyUnicode_Replace(substr *PyObject, replstr *PyObject, maxcount PySsizeT) *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicode_Compare C.PyUnicode_Compare
func (self *PyObject) PyUnicode_Compare(right *PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyUnicode_CompareWithASCIIString C.PyUnicode_CompareWithASCIIString
func (self *PyObject) PyUnicode_CompareWithASCIIString(right *c.Char) c.Int {
	return 0
}

// llgo:link (*PyObject).PyUnicode_EqualToUTF8 C.PyUnicode_EqualToUTF8
func (self *PyObject) PyUnicode_EqualToUTF8(_llcppg_param2 *c.Char) c.Int {
	return 0
}

// llgo:link (*PyObject).PyUnicode_EqualToUTF8AndSize C.PyUnicode_EqualToUTF8AndSize
func (self *PyObject) PyUnicode_EqualToUTF8AndSize(_llcppg_param2 *c.Char, _llcppg_param3 PySsizeT) c.Int {
	return 0
}

// llgo:link (*PyObject).PyUnicode_Equal C.PyUnicode_Equal
func (self *PyObject) PyUnicode_Equal(str2 *PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyUnicode_RichCompare C.PyUnicode_RichCompare
func (self *PyObject) PyUnicode_RichCompare(right *PyObject, op c.Int) *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicode_Format C.PyUnicode_Format
func (self *PyObject) PyUnicode_Format(args *PyObject) *PyObject {
	return self
}

// llgo:link (*PyObject).PyUnicode_Contains C.PyUnicode_Contains
func (self *PyObject) PyUnicode_Contains(element *PyObject) c.Int {
	return 0
}

// llgo:link (*PyObject).PyUnicode_IsIdentifier C.PyUnicode_IsIdentifier
func (self *PyObject) PyUnicode_IsIdentifier() c.Int {
	return 0
}
func (p *_llcppg_anon_3) XGof_ref_any() *unsafe.Pointer {
	return (*unsafe.Pointer)(unsafe.Pointer(p))
}
func (p *_llcppg_anon_3) XGof_ref_latin1() **Py_UCS1 {
	return (**Py_UCS1)(unsafe.Pointer(p))
}
func (p *_llcppg_anon_3) XGof_ref_ucs2() **Py_UCS2 {
	return (**Py_UCS2)(unsafe.Pointer(p))
}
func (p *_llcppg_anon_3) XGof_ref_ucs4() **Py_UCS4 {
	return (**Py_UCS4)(unsafe.Pointer(p))
}

// llgo:link (*PyObject).PyUnicode_KIND C.PyUnicode_KIND
func (self *PyObject) PyUnicode_KIND() c.Int {
	return 0
}

// llgo:link (*PyObject).PyUnicode_DATA C.PyUnicode_DATA
func (self *PyObject) PyUnicode_DATA() unsafe.Pointer {
	return nil
}

//go:linkname PyUnicode_New C.PyUnicode_New
func PyUnicode_New(size PySsizeT, maxchar Py_UCS4) *PyObject

// llgo:link (*PyObject).PyUnicode_CopyCharacters C.PyUnicode_CopyCharacters
func (self *PyObject) PyUnicode_CopyCharacters(to_start PySsizeT, from *PyObject, from_start PySsizeT, how_many PySsizeT) PySsizeT {
	return 0
}

// llgo:link (*PyObject).PyUnicode_Fill C.PyUnicode_Fill
func (self *PyObject) PyUnicode_Fill(start PySsizeT, length PySsizeT, fill_char Py_UCS4) PySsizeT {
	return 0
}

//go:linkname PyUnicode_FromKindAndData C.PyUnicode_FromKindAndData
func PyUnicode_FromKindAndData(kind c.Int, buffer unsafe.Pointer, size PySsizeT) *PyObject

//go:linkname PyUnicodeWriter_Create C.PyUnicodeWriter_Create
func PyUnicodeWriter_Create(length PySsizeT) *PyUnicodeWriter

// llgo:link (*PyUnicodeWriter).Discard C.PyUnicodeWriter_Discard
func (self *PyUnicodeWriter) Discard() {
}

// llgo:link (*PyUnicodeWriter).Finish C.PyUnicodeWriter_Finish
func (self *PyUnicodeWriter) Finish() *PyObject {
	return nil
}

// llgo:link (*PyUnicodeWriter).WriteChar C.PyUnicodeWriter_WriteChar
func (self *PyUnicodeWriter) WriteChar(ch Py_UCS4) c.Int {
	return 0
}

// llgo:link (*PyUnicodeWriter).WriteUTF8 C.PyUnicodeWriter_WriteUTF8
func (self *PyUnicodeWriter) WriteUTF8(str *c.Char, size PySsizeT) c.Int {
	return 0
}

// llgo:link (*PyUnicodeWriter).WriteASCII C.PyUnicodeWriter_WriteASCII
func (self *PyUnicodeWriter) WriteASCII(str *c.Char, size PySsizeT) c.Int {
	return 0
}

// llgo:link (*PyUnicodeWriter).WriteWideChar C.PyUnicodeWriter_WriteWideChar
func (self *PyUnicodeWriter) WriteWideChar(str *c.WcharT, size PySsizeT) c.Int {
	return 0
}

// llgo:link (*PyUnicodeWriter).WriteUCS4 C.PyUnicodeWriter_WriteUCS4
func (self *PyUnicodeWriter) WriteUCS4(str *Py_UCS4, size PySsizeT) c.Int {
	return 0
}

// llgo:link (*PyUnicodeWriter).WriteStr C.PyUnicodeWriter_WriteStr
func (self *PyUnicodeWriter) WriteStr(obj *PyObject) c.Int {
	return 0
}

// llgo:link (*PyUnicodeWriter).WriteRepr C.PyUnicodeWriter_WriteRepr
func (self *PyUnicodeWriter) WriteRepr(obj *PyObject) c.Int {
	return 0
}

// llgo:link (*PyUnicodeWriter).WriteSubstring C.PyUnicodeWriter_WriteSubstring
func (self *PyUnicodeWriter) WriteSubstring(str *PyObject, start PySsizeT, end PySsizeT) c.Int {
	return 0
}

// llgo:link (*PyUnicodeWriter).Format C.PyUnicodeWriter_Format
func (self *PyUnicodeWriter) Format(format *c.Char, __llgo_va_list ...any) c.Int {
	return 0
}

// llgo:link (*PyUnicodeWriter).DecodeUTF8Stateful C.PyUnicodeWriter_DecodeUTF8Stateful
func (self *PyUnicodeWriter) DecodeUTF8Stateful(string *c.Char, length PySsizeT, errors *c.Char, consumed *PySsizeT) c.Int {
	return 0
}

// llgo:link (*X_PyUnicodeWriter).Init C._PyUnicodeWriter_Init
func (self *X_PyUnicodeWriter) Init() {
}

// llgo:link (*X_PyUnicodeWriter).PrepareInternal C._PyUnicodeWriter_PrepareInternal
func (self *X_PyUnicodeWriter) PrepareInternal(length PySsizeT, maxchar Py_UCS4) c.Int {
	return 0
}

// llgo:link (*X_PyUnicodeWriter).PrepareKindInternal C._PyUnicodeWriter_PrepareKindInternal
func (self *X_PyUnicodeWriter) PrepareKindInternal(kind c.Int) c.Int {
	return 0
}

// llgo:link (*X_PyUnicodeWriter).WriteChar C._PyUnicodeWriter_WriteChar
func (self *X_PyUnicodeWriter) WriteChar(ch Py_UCS4) c.Int {
	return 0
}

// llgo:link (*X_PyUnicodeWriter).WriteStr C._PyUnicodeWriter_WriteStr
func (self *X_PyUnicodeWriter) WriteStr(str *PyObject) c.Int {
	return 0
}

// llgo:link (*X_PyUnicodeWriter).WriteSubstring C._PyUnicodeWriter_WriteSubstring
func (self *X_PyUnicodeWriter) WriteSubstring(str *PyObject, start PySsizeT, end PySsizeT) c.Int {
	return 0
}

// llgo:link (*X_PyUnicodeWriter).WriteASCIIString C._PyUnicodeWriter_WriteASCIIString
func (self *X_PyUnicodeWriter) WriteASCIIString(str *c.Char, len PySsizeT) c.Int {
	return 0
}

// llgo:link (*X_PyUnicodeWriter).WriteLatin1String C._PyUnicodeWriter_WriteLatin1String
func (self *X_PyUnicodeWriter) WriteLatin1String(str *c.Char, len PySsizeT) c.Int {
	return 0
}

// llgo:link (*X_PyUnicodeWriter).Finish C._PyUnicodeWriter_Finish
func (self *X_PyUnicodeWriter) Finish() *PyObject {
	return nil
}

// llgo:link (*X_PyUnicodeWriter).Dealloc C._PyUnicodeWriter_Dealloc
func (self *X_PyUnicodeWriter) Dealloc() {
}

// llgo:link (*PyObject).PyUnicode_AsUTF8 C.PyUnicode_AsUTF8
func (self *PyObject) PyUnicode_AsUTF8() *c.Char {
	return nil
}

//go:linkname X_PyUnicode_IsLowercase C._PyUnicode_IsLowercase
func X_PyUnicode_IsLowercase(ch Py_UCS4) c.Int

//go:linkname X_PyUnicode_IsUppercase C._PyUnicode_IsUppercase
func X_PyUnicode_IsUppercase(ch Py_UCS4) c.Int

//go:linkname X_PyUnicode_IsTitlecase C._PyUnicode_IsTitlecase
func X_PyUnicode_IsTitlecase(ch Py_UCS4) c.Int

//go:linkname X_PyUnicode_IsWhitespace C._PyUnicode_IsWhitespace
func X_PyUnicode_IsWhitespace(ch Py_UCS4) c.Int

//go:linkname X_PyUnicode_IsLinebreak C._PyUnicode_IsLinebreak
func X_PyUnicode_IsLinebreak(ch Py_UCS4) c.Int

//go:linkname X_PyUnicode_ToLowercase C._PyUnicode_ToLowercase
func X_PyUnicode_ToLowercase(ch Py_UCS4) Py_UCS4

//go:linkname X_PyUnicode_ToUppercase C._PyUnicode_ToUppercase
func X_PyUnicode_ToUppercase(ch Py_UCS4) Py_UCS4

//go:linkname X_PyUnicode_ToTitlecase C._PyUnicode_ToTitlecase
func X_PyUnicode_ToTitlecase(ch Py_UCS4) Py_UCS4

//go:linkname X_PyUnicode_ToDecimalDigit C._PyUnicode_ToDecimalDigit
func X_PyUnicode_ToDecimalDigit(ch Py_UCS4) c.Int

//go:linkname X_PyUnicode_ToDigit C._PyUnicode_ToDigit
func X_PyUnicode_ToDigit(ch Py_UCS4) c.Int

//go:linkname X_PyUnicode_ToNumeric C._PyUnicode_ToNumeric
func X_PyUnicode_ToNumeric(ch Py_UCS4) c.Double

//go:linkname X_PyUnicode_IsDecimalDigit C._PyUnicode_IsDecimalDigit
func X_PyUnicode_IsDecimalDigit(ch Py_UCS4) c.Int

//go:linkname X_PyUnicode_IsDigit C._PyUnicode_IsDigit
func X_PyUnicode_IsDigit(ch Py_UCS4) c.Int

//go:linkname X_PyUnicode_IsNumeric C._PyUnicode_IsNumeric
func X_PyUnicode_IsNumeric(ch Py_UCS4) c.Int

//go:linkname X_PyUnicode_IsPrintable C._PyUnicode_IsPrintable
func X_PyUnicode_IsPrintable(ch Py_UCS4) c.Int

//go:linkname X_PyUnicode_IsAlpha C._PyUnicode_IsAlpha
func X_PyUnicode_IsAlpha(ch Py_UCS4) c.Int

//go:linkname X_PyAsciiWhitespace C._Py_ascii_whitespace
var X_PyAsciiWhitespace *uint8

// llgo:link (*X_Py_Identifier).X_PyUnicode_FromId C._PyUnicode_FromId
func (self *X_Py_Identifier) X_PyUnicode_FromId() *PyObject {
	return nil
}
