// Code generated by llcppg; DO NOT EDIT.

package py

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type PyWeakReference = X_PyWeakReference

//go:linkname X_PyWeakref_RefType C._PyWeakref_RefType
var X_PyWeakref_RefType PyTypeObject

//go:linkname X_PyWeakref_ProxyType C._PyWeakref_ProxyType
var X_PyWeakref_ProxyType PyTypeObject

//go:linkname X_PyWeakref_CallableProxyType C._PyWeakref_CallableProxyType
var X_PyWeakref_CallableProxyType PyTypeObject

// llgo:link (*PyObject).PyWeakref_NewRef C.PyWeakref_NewRef
func (self *PyObject) PyWeakref_NewRef(callback *PyObject) *PyObject {
	return self
}

// llgo:link (*PyObject).PyWeakref_NewProxy C.PyWeakref_NewProxy
func (self *PyObject) PyWeakref_NewProxy(callback *PyObject) *PyObject {
	return self
}

// llgo:link (*PyObject).PyWeakref_GetObject C.PyWeakref_GetObject
func (self *PyObject) PyWeakref_GetObject() *PyObject {
	return self
}

// llgo:link (*PyObject).PyWeakref_GetRef C.PyWeakref_GetRef
func (self *PyObject) PyWeakref_GetRef(pobj **PyObject) c.Int {
	return 0
}
